### ISSUE TITLE
Cannot run Sega Master System Ares 132

### ISSUE THREAD

**Issue by geesehoward79** [higan-emu/ares#1011]
-SMS Bios Selected
-Game loaded
-Only bios message. Without bios selected, black screen only.

![image](https://user-images.githubusercontent.com/54275290/223717514-bd5eb7d2-e57e-44ae-81ef-a2b874c5be1a.png)

**Comment by LukeUsher** [comment]
This game works fine on my end; can you make sure your rom is a good dump?

Go to Tools and Manifest and view the information there, I get the following:

```
game
  sha256: 1d28f2a3742ab6d4745af05f73119dfbadd6691c595c553455c0736e8e0dfa41
  name:   Kenseiden (USA, Europe, Brazil) (En)
  title:  Kenseiden (USA, Europe, Brazil) (En)
  region: NTSC-J, NTSC-U, PAL
  board:  Sega
    memory
      type: ROM
      size: 0x40000
      content: Program
    memory
      type: RAM
      size: 0x8000
      content: Save
```

If your sha256 doesn't match, or the memory section don't match, it's possible you had a bad dump.

**Comment by geesehoward79** [comment]
Its different.
I l try with another dump

![image](https://user-images.githubusercontent.com/54275290/223721353-9bbc56bb-18a7-4f0b-ba58-5f3f00856a6d.png)

**Comment by LukeUsher** [comment]
I see the problem; based on the rom size, it appears your rom is a headered image created by a copier device, rather than an accurate dump of the cartridge; ares only supports clean, proper rom dumps, and not all the variations that exist from outdated copier hardware

**Comment by geesehoward79** [comment]
Worked!
I never saw a megadrive emu that checked sha256...sorry!

Thanks!!

**Comment by Kawa-oneechan** [comment]
But it's not the sha256 that matters here?
