### ISSUE TITLE
[MEGADRIVE] Glitches at the top of the screen with Alisia Dragoon (Europe)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#1013]
Emulator : Ares 1.32
Options : Default
Game : Alisia Dragoon (Europe)
System : Megadrive / Genesis

Glitches at the top of the screen. Maybe this glitch exists on the real hardware, I don't have the game to test it.

![alisia](https://user-images.githubusercontent.com/12481242/223994338-6c612e08-302d-4f74-bb40-d5953f36c451.gif)

**Comment by BiZkViT96** [comment]
PAL (50Hz) game on NTSC (60Hz) problem

**Comment by BenjaminSiskoo** [comment]
I'm using this setting !!! I'm wrong !

![image](https://user-images.githubusercontent.com/12481242/224009730-3a2f237c-f195-4ae4-8dab-73049c1285d4.png)

**Comment by BiZkViT96** [comment]
Rom has wrong header that claims it's a JU game. But keep issue open.

**Comment by BenjaminSiskoo** [comment]
ok :)

**Comment by BenjaminSiskoo** [comment]
Thanks :)
