### ISSUE TITLE
[NES] Screen with letters in the window in Parody World - Monster Party (Japan) (Proto)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#1030]
Emulator : Ares 1.32
Nightly build 2023-03-13 12:25:59 UTC
Options : Default
Game : Parody World - Monster Party (Japan) (Proto)
System : NES

with mesen, the screen is properly displayed

![image](https://user-images.githubusercontent.com/12481242/224710910-73fb1cf9-0635-4dd7-93b1-67782ddb2742.png)

**Comment by FitzRoyX** [comment]
Cannot reproduce. Please start pasting your manifest information when you file bug reports btw. Tools>manifest

**Comment by FitzRoyX** [comment]
Invertego has determined that you are running in "Europe" mode even though this is an NTSC-J game. You forgot to set it back.

**Comment by BenjaminSiskoo** [comment]
here the manifest 
![image](https://user-images.githubusercontent.com/12481242/224867617-2522c331-4ca6-4982-bc59-4d426d3e2900.png)

**Comment by BenjaminSiskoo** [comment]
ok, you're right E --> J it's ok
