### ISSUE TITLE
[NES] Cards are messed in Peek-A-Boo Poker (USA) (Unl)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#1031]
Emulator : Ares 1.32
Nightly build 2023-03-13 12:25:59 UTC
Options : Default
Game : Peek-A-Boo Poker (USA) (Unl)
System : NES

Cards are not displayed properly

![image](https://user-images.githubusercontent.com/12481242/224711812-1fd19530-dfab-4916-a7a3-4aee6a65d273.png)

**Comment by FitzRoyX** [comment]
Cannot reproduce again.

**Comment by remutro** [comment]
Please post manifest from Tools> Manifest

There is a good chance the version of the rom you have is headerless, even though it is in a headered set and the hash will confirm this (which would mean we can't determine region properly which defaults to NTSC).

No-Intro validated images & hashes for header/headless can be found here for this game:
https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=1661

**Comment by BenjaminSiskoo** [comment]
Here the manifest

![image](https://user-images.githubusercontent.com/12481242/224867711-0584136e-95c7-4aeb-81ed-26e568bb68f0.png)

**Comment by remutro** [comment]
The sha256 hash you've provided for your image matches the headerless ROM according to No-Intro. You can confirm this further by extracting the *.nes file (if it was zipped) and checking the size. If it is 98304 bytes in length, it has no header.

**Comment by BenjaminSiskoo** [comment]
@remutro here the size 

![image](https://user-images.githubusercontent.com/12481242/225258268-05b4f35e-5e19-4980-a103-f181ee6d7a1e.png)

**Comment by encoded-byte** [comment]
The NES database only contains info for licensed games at this time. This game is unlicensed, so using a headered rom is required.
The size of the file (98320 bytes) matches a headered rom, ~~so it must have corrupted headers~~.

Update: after looking more into it this game uses mapper 148 (Sachen SA-008-A / Tengen 800008) which is unsupported. I can reproduce the glitches.
