### ISSUE TITLE
[32X] Virtua Fighter Bugs

### ISSUE THREAD

**Issue by voidflower-xcii** [higan-emu/ares#1037]
There's a number of glaring bugs.

1. The hit detection is busted. Especially evident with moves that pounce someone on the ground, they will simply not register at all.
2. The AI seems pretty broken. It will even sometimes choose to not move or attack at all.
3. One of Wolf Hawkfield's grabs has a completely broken animation that causes you to float in the air behind him (You should be held above him).

I'm using ares v132. I tested this against PicoDrive.

file: Virtua Fighter (Japan, USA) (En).32x
sha256: C595E136C91A012B1E7D591ACFB9D965926CAC51ACEA998B90969D74391BFA08

**Comment by remutro** [comment]
This seems to have regressed recently. The European version has had major issues for a long time. The CPU character spazzes out, instant ring-outs, etc. AI is completely broken.
