### ISSUE TITLE
Why Not Add a Cheat System?

### ISSUE THREAD

**Issue by XXAshuraXX** [higan-emu/ares#1054]
It would be cool if we got a cheat system [similar to Dolphins AR/Gecko Codes] for depending on the console emulated.

**Comment by jeffythedragonslayer** [comment]
It would be cool, but I'd rather see more systems emulated  accurately first before we focus on nice-to-have features.

**Comment by remutro** [comment]
This is a duplicate request (it's been asked many times). This is harder/bigger effort in a multi-emu like ares as each core could potentially require different implementations.

Duplicate of: https://github.com/ares-emulator/ares/issues/167

**Comment by LukeUsher** [comment]
Closing as duplicate
