### ISSUE TITLE
Blank screen when choosing Directx 11 in video drivers

### ISSUE THREAD

**Issue by petran79** [higan-emu/ares#1082]
Opengl 3.2 , Directx 9 and GDI modes work fine however when I pick dx11 screen becomes blank with only the sound playing.
I am using the latest Nvidia drivers and Windows 10.

**Comment by LukeUsher** [comment]
This is expected behaviour; there is no directx11 driver in ares, a menu option of an incomplete feature accidentally made it into the build, you’ll notice there is no dx11 driver in the nightly builds (which is correct, we don’t have one)
