### ISSUE TITLE
[MD] Puyo Puyo Tsuu: Sound bug

### ISSUE THREAD

**Issue by BiZkViT96** [higan-emu/ares#1103]
**Describe the issue**
During the intro, left and right channels has noticeable problems.

![2023-05-04 03_31_40-Audacity](https://user-images.githubusercontent.com/88586431/236044281-365cd3a6-3a29-4dde-b23f-b8aa6752a068.png)

[ares.zip](https://github.com/ares-emulator/ares/files/11391064/ares.zip)
[BlastEm.zip](https://github.com/ares-emulator/ares/files/11391066/BlastEm.zip)

**Rom Information**

```
file: Puyo Puyo Tsuu (World) (Ja) (Rev A) (Virtual Console)
SHA1 8bec632c90bf4ccee1d43f1cdd3bba963187ca5d
SHA256: 78169afb25ab25867da32f1d740d7a8662da939553d5cc7e7601ac1b4b7edb20
```

ares nightly 2023-05-03

**Comment by LukeUsher** [comment]
Should be fixed after [785edf6](https://github.com/ares-emulator/ares/commit/785edf60c81871568cc3c87579040ca60ed41382)
