### ISSUE TITLE
[GBA] Monster Gate (Japan) - Screen Covered With Dashes With Max Cards

### ISSUE THREAD

**Issue by HeroponRikiBestest** [higan-emu/ares#1105]
**Describe the issue**
If you fill all 10 of your cards/items slots, the screen will be covered with dashes, and this will show up everytime you open your list of cards (which is pretty much all the time, since you need it to use items)
Seems to occur on Rev 1 as well, and the save seems to work there too, but most testing was done with the original version.

This issue was fixed in mGBA in commit https://github.com/mgba-emu/mgba/commit/4ce9b83362ad66b1421afea7372adfc753bce97c between releases 0.1.0 and 0.1.1, and the game has continued functioning properly from there until now, as of the latest nightly. 

Apparently, this is the result of a documentation error in gbatek.

To reproduce, load the following save file, choose to continue, and immediately walk to the right; your 10th card slot will be filled up, and the card screen will display, showing the issue.
[Monster Gate (Japan).ram.zip](https://github.com/ares-emulator/ares/files/11402977/Monster.Gate.Japan.ram.zip)

![image](https://user-images.githubusercontent.com/50224630/236368836-a216167b-4322-44ed-9373-51612087db32.png)

```
file: Monster Gate (Japan).gba
sha256: <3b48a60acb92f0ca17772a0d551656cd550968cfa720e83f8abe48bd0064d5ad>
```

Tested on latest commit
Tested on Linux Mint 21.1

**Comment by LukeUsher** [comment]
Fixed as of 75821d4, but may require further tweaking in future as more research is done on hardware.

**Comment by HeroponRikiBestest** [comment]
Further research done at nanoboy, added with https://github.com/nba-emu/NanoBoyAdvance/commit/87396726e513863bb9d1612a3d6a29ca6f72720a


> If this is it then it is indeed what I suspected: open bus from the internal background VRAM bus. This means that the data that was most recently (successfully) read from background VRAM is read and interpreted as tile data.
> In the simple case where only one background layer is enabled this is the tile map entry that was fetched before the tile data.
> With multiple background layers the situation most likely is more complicated and the data that is returned could be map or tile data from another background layer.
> Monster Gate still works with my change, so that's good.
> 
> I think I pretty much confirmed that it's open bus and background layers can affect other background layers.
> Luckily this is very easy to support with NBA's cycle-accurate PPU emulation.
> Other emulators are advised to just return 0 for the out-of-bounds accesses, since they do not replicate the proper VRAM access patterns for open-bus to return the right values.

Feel free to close again if it is decided the current implementation is sufficient.

**Comment by LukeUsher** [comment]
Closing as sufficient, but may consider opening another issue for improving PPU accuracy/vram access patterns
