### ISSUE TITLE
[N64] Jet Force Gemini

### ISSUE THREAD

**Issue by Alexn64gamer0712** [higan-emu/ares#1107]
Jet Force Gemini hangs in intro with this screen with this screen on ares v131
![image](https://user-images.githubusercontent.com/100775660/236669551-9180fe52-ea11-4886-919f-78459701c8bd.png)

Rom info: Jet Force Gemini(U)
cic: CIC-NUS-6105

**Comment by LukeUsher** [comment]
Duplicate of #129 ?

**Comment by Alexn64gamer0712** [comment]
The gfx numbers are different, dont know if that has something to do btw...

**Comment by kev4cards** [comment]
I can confirm this is a duplicate.

Those some gfx numbers are posted in a later comment. That said, the numbers do change upon every commit related to N64 emulation. That's just the nature of the issue.
