### ISSUE TITLE
Add support for other patch formats than .bps

### ISSUE THREAD

**Issue by amayra** [higan-emu/ares#1111]
this feature that some emulators offer. It can automatically patch the game if the patch and the ROM have the same filename
![like this](https://fantasyanime.com/images/tutorials/patching_ex.gif)

**Comment by LukeUsher** [comment]
This feature has existed for a very long time, but it only works with the .bps format, other formats are not implemented and are not likely to be any time soon.

**Comment by amayra** [comment]
most old patch are in ips format 

and patch dev is long missing or even dead to care about update it 

every other emulator support this too

**Comment by aquova** [comment]
I'd be interested in making a pull request that adds IPS support in a similar vein to how BPS is supported now, if there's interest in having it.

**Comment by LukeUsher** [comment]
Should we close this issue or is there another widespread format we should support?

**Comment by aquova** [comment]
Personally, I think this could be closed. From what I've seen, IPS + BPS covers the vast majority of existing patches, especially for the sizes of games that Ares supports. More can be looked at on a case-by-case basis, but it does open a can of worms.

**Comment by LukeUsher** [comment]
agreed , ips and bps is plenty
