### ISSUE TITLE
[32X] Broken SH2 Watchdog Timer support

### ISSUE THREAD

**Issue by viciious** [higan-emu/ares#1119]
**Describe the bug**
The Hitach SH-2 CPU features the so-called "WatchDog Timer" aka WDT, which can be used for both program synchronization and profiling. Please see section 12 of the Hardware Manual: https://github.com/viciious/32XDK/releases/download/v1.0/Hitachi_SH2_Hardware_Manual.pdf

Afaik some commercial games do make use of the WDT, along with some homebrew demos and hacks.

**To Reproduce**
Launch Doom 32X Resurrection, load a map, press START and then MODE two times. A debug screen will be brought up, which is supposed to display millisecond timings for different rendering phases. As of now, all timings that make use of the WDT report 0 msec.

![image](https://github.com/ares-emulator/ares/assets/1173058/895c33a8-f2ea-451e-9867-e1ceec204fe0)

**Expected behavior**
The debug screen should look something like this:

![image](https://github.com/ares-emulator/ares/assets/1173058/112af589-b8f5-46b4-a16a-0fc31ee7203b)

**Comment by LukeUsher** [comment]
![image](https://github.com/ares-emulator/ares/assets/740003/6665c609-2537-4950-baff-33518c0e1343)

Seems to be solved in latest nightly, can you confirm @viciious

**Comment by viciious** [comment]
I can confirm the feature as working. Thanks a lot!
