### ISSUE TITLE
[Feature Request] Run Satellaview, Super Game Boy, and Sufami Turbo ROMs directly through the Command Line

### ISSUE THREAD

**Issue by ghost** [higan-emu/ares#1129]
**Is your feature request related to a problem? Please describe.**
Would be great to run these three systems,  Satellaview, Super Game Boy, and Sufami Turbo, directly through the command line. 

**Describe the solution you'd like**
All 3 of these systems rely on a bootROM of some sort, so maybe adding a way to point to the bootROM in the firmware screen and using a flag to boot one of these systems. 

Something like:

`ares --system Super Famicom example.rom --satellaview`

`ares --system Super Famicom example.rom --sgb`

`ares --system Super Famicom example.rom --sufamiturbo`

**Describe alternatives you've considered**

Maybe pointing to two ROMs instead? First line would be the bootROM, second line would be the game ROM. 

`ares --system Super Famicom /path/to/SGB1.sfc /path/to/example.sfc `

**Additional context**

At the moment, you can either open these bootROMs directly through command-line and then you're given a prompt to open the respective system's ROM or you can open ares and open it through the GUI. 

Opening these system's ROMs directly through command line would be nice and convenient.

**Comment by LukeUsher** [comment]
Addressed with [dafb570](https://github.com/ares-emulator/ares/commit/dafb57010c0e7ad30f40df1970b23afb821960db)

Specifying multiple files via CLI at load time is now supported; for example, to load the Super GameBoy with Super Mario Land inserted, you can do:

`ares "Super Game Boy (Japan, USA) (En).sfc" "Super Mario Land 2 - 6 Golden Coins (USA, Europe).gb"`

**Comment by ghost** [comment]
Thank you! Excited to see this :)
