### ISSUE TITLE
[MEGA CD] The Terminator: Doesn't boot

### ISSUE THREAD

**Issue by BiZkViT96** [higan-emu/ares#1130]
**Describe the issue**
BIOS freezes on SEGA with Sonic screen, right before game should start loading.

Game was converted to CHD and works on v132

**Rom Information**
http://redump.org/disc/21510/

ares nightly 2023-06-15

**Comment by invertego** [comment]
Regressing change; 076d73fafbad77b5fa24f0e424c83cf9e3f19de3

@TascoDLX FYI

**Comment by LukeUsher** [comment]
Fixed in [5f55b6c](https://github.com/ares-emulator/ares/commit/5f55b6cf2718f01ad447d1aa9feb60f1f3f627ed)
