### ISSUE TITLE
Required package names appear to be out of date on ubuntu 23.04

### ISSUE THREAD

**Issue by jeffythedragonslayer** [higan-emu/ares#1139]
Running this command from the readme on an ubuntu 23.04 vm inside virtualbox 7.0.8 on windows,

`sudo apt-get install g++ make pkg-config libgtk2.0-dev libcanberra-gtk-module libgl-dev libasound2-dev`

prints this:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libgtk2.0-dev
E: Couldn't find any package by glob 'libgtk2.0-dev'
E: Couldn't find any package by regex 'libgtk2.0-dev'
E: Unable to locate package libcanberra-gtk-module
```

**Comment by LukeUsher** [comment]
Due to the age of GTK2, I believe these packages have been moved to Universe rather than main; try enabling the Universe repository; alternatively, install the GTK3+ packages and build with hiro=gtk3

**Comment by jeffythedragonslayer** [comment]
I checked and universe was enabled.

**Comment by jeffythedragonslayer** [comment]
`make hiro=gtk3` did work, but I still can't successfully test.

**Comment by LukeUsher** [comment]
We have addressed this by defaulting to gtk3 rather than gtk2, since the gtk2 libraries are no longer provided on Ubuntu.
