### ISSUE TITLE
[MEGA CD] ares fails to load a SegaCD image

### ISSUE THREAD

**Issue by viciious** [higan-emu/ares#1161]
**Describe the bug**
Emulator drops to default CD player interface instead of starting the program.

**To Reproduce**
1. Go to https://www.mediafire.com/file/08bi93gd1vxlxa9/cdmodplayer-20130401.7z/file
2. Click on the download link
3. Un-7zip the file
4. Start ares, load the ISO file CDModPlayer-US.iso found in the 'cdmodplayer' directory via Load -> Sega -> Mega CD...

**Expected behavior**
After the initial startup sequence, the mod player should start. Instead the player is greeted by the default CD player interface, which reports no CDDA tracks.

**Screenshots**
![image](https://github.com/ares-emulator/ares/assets/1173058/225f36bb-0ffc-4c18-9562-2aeb735d575d)

**Additional context**
Loading the same ISO file works as expected in Kega Fusion and blast-em.

**Comment by LukeUsher** [comment]
ISO files are not supported by ares; please convert to bin/cue or CHD.

**Comment by viciious** [comment]
Tried converting the aforementioned ISO into bin+cue pair, ares still dropped to default CD player after the "CHECKING DISK" message.

UP: tried a different conversion tool and it worked fine this time around. Sorry for the trouble!
