### ISSUE TITLE
FAT16 file system support/detection. Concise save file extensions: .eep and .fla instead of .eeprom and .flash

### ISSUE THREAD

**Issue by nopjne** [higan-emu/ares#1166]
**Is your feature request related to a problem? Please describe.**
I extended a fun N64 project, with the capability to expose a physical N64 cartridge as a usb flash drive to the OS, essentially allowing you to play your cartridge games on an emulator without creating roms: https://github.com/nopjne/drmdmp64_mass

To minimize complexity I used a FAT16 example to expose a filesystem that any OS can understand.
I want to use Ares to directly emulate from that "virtual flashdrive" which also means read and write saves. 
FAT16 has limitations on filename length and extension length (max 3 chars), therefore it would be great if Ares can attempt and use .eep and .fla files first before searching for .eeprom and .flash. This also means it needs to save to .eep and .fla instead if/when .eep or .fla presence is detected prior.

**Describe the solution you'd like**
Additional .eep and .fla file support which takes precedence over .eeprom and .flash file loading.

**Describe alternatives you've considered**
Allow .eep and .fla to be specified through UI or cmdline instead. Not ideal as the integration for the enduser would not be seamless.

**Additional context**
This is what the virtual disk looks like.
D:\>dir /s
 Volume in drive D is DreamDump64
 Volume Serial Number is 0022-DC8F

 Directory of D:\

09/05/2008  04:20 PM               512 ROM.EEP
09/05/2008  04:20 PM           131,072 ROM.FLA
09/05/2008  04:20 PM        12,582,912 ROM.N64
09/05/2008  04:20 PM        12,582,912 ROMF.Z64  (byte flipped)
09/05/2008  04:20 PM           131,072 ROMF.RAM  (byte flipped)
09/05/2008  04:20 PM               512 ROMF.EEP       (naming consistency for byteflipped)
09/05/2008  04:20 PM             2,048 CARTTEST.TXT

**Comment by LukeUsher** [comment]
This is not going to ever happen upstream; reducing filenames to 8.3 for the purpose of supporting FAT16 is not something we would consider

If you require this, perhaps consider maintaining a fork for your product,

**Comment by hackgrid** [comment]
Maybe make the file extensions configurable in a config file? So anybody could change it as they want and ares could ship with the default names by default?

**Comment by nopjne** [comment]
@LukeUsher Is there any reasoning why the extension cannot be .eep and .fla? I dont care about the 8 char name length. That will be driven by the romname which I do have control over.
Also I am specifically not asking you to drop your default, just to add searching for .eep and .fla first.

Your suggestion of maintaining an entire fork for something this small seems strange to me.
