### ISSUE TITLE
Feature Request: Controller Profiles

### ISSUE THREAD

**Issue by PABastien1** [higan-emu/ares#1168]
**Is your feature request related to a problem? Please describe.**
Hello. I am having a bit of frustration with having to constantly rebind my controllers every time I change what platform I'm playing on (I have a six face button controller I use for N64 and a snes style controller for snes games) 

**Describe the solution you'd like**
I would like the ability to save configuration profiles that I can load. Or at the least the ability for whatever I bind for one system to not affect the other systems.

**Describe alternatives you've considered**
I've been rebinding every time I switch between my SNES library and my N64 library. It's manageable but its tiring.

**Comment by remutro** [comment]
Similar to open issue: https://github.com/ares-emulator/ares/issues/173

**Comment by LukeUsher** [comment]
Yeah, close enough I'd consider duplicate, see #173
