### ISSUE TITLE
[Feature Request] Per Game Input Profiles.

### ISSUE THREAD

**Issue by CourageT3** [higan-emu/ares#1172]
Hello, first of all, let me apologize for opening a feature request so similar to #1168 and #173.
I understand that it could be interpreted as identical to the ones mentioned above.

But honestly, I feel that this one is different (and even better) for the reason below.
In #1168 and #173, Input Profiles per System/Console were requested, which I believe has significant restrictions, as it would only allow to set a single Input Profile per Emulated System/Console.

But in this Issue, I kindly request the possibility of creating Input Profiles on a per game basis (not just per System/Console).
This delivers an even improved experience tailored to the needs of each user, depending on the game they are playing at the time.

For example:
For N64 and SNES: It would allow you to Set custom mappings for TLoZ: OoT/SM64 and F-Zero/Super Mario World respectively.

If you feel that this Feature Request should be closed because it was previously requested, I will understand.
Thank you very much for everything, I love the work the Ares developers have done.

**Comment by LukeUsher** [comment]
I feel like this should be merged under the same umbrella as #173
