### ISSUE TITLE
Upstream Aur/Flatpak patches

### ISSUE THREAD

**Issue by ghost** [higan-emu/ares#1173]
**Describe the bug**

Both the aur package and the Flatpak have issues with not picking up the shader and database folder by default.

The aur package circumvents this issue with a patch: https://aur.archlinux.org/cgit/aur.git/tree/ares-paths.patch?h=ares-emu

I've ported over that patch to the Flatpak here: https://github.com/flathub/dev.ares.ares/pull/29 and it also seems to fix the Flatpak. 

The maintainer of the Flatpak commented on the patch and suggested a way ares could incorporate the patch: https://github.com/flathub/dev.ares.ares/pull/29#issuecomment-1662363481

I am not the most experienced with coding so I am a little out of my league here. Could the patch somehow be upstreamed and incorporated into ares?

**Comment by Mastergatto** [comment]
Maintainer of the AUR package in question here: yes, I already plan to make a PR to upstream the patch (expunged of some lines that shouldn't belong in the emulator), but I want first to see if there are potential issues with the patch.

Regarding the possibility that this patch makes it to the upstream, I'll leave the decision to others.

**Comment by LukeUsher** [comment]
I don't see an issue; I'll be happy to accept @Mastergatto
