### ISSUE TITLE
Adjust hardcoded /usr/share line in path.cpp

### ISSUE THREAD

**Issue by ghost** [higan-emu/ares#1179]
Thank you @ Mastergatto for the PR (# 1178)! 

The only other small piece to the puzzle is that the hardcoded `/usr/share` line in `path.cpp` (https://github.com/ares-emulator/ares/blob/master/nall/path.cpp#L122) also causes the Flatpak specifically to not pick up the Database/Shaders folder. Patching it to look in `/app/share/` does fix the Flatpak (but would probably break upstream ares).  

You can see some of the discussion here: https://github.com/flathub/dev.ares.ares/pull/29#issuecomment-1662363481 and the patch here: https://github.com/flathub/dev.ares.ares/pull/29/files

I think this is the last piece of the puzzle for the Flatpak to properly pick up the shaders and the database folders.

Is there potentially a way to not hardcode the `usr/share` line?

**Comment by Mastergatto** [comment]
One way might be that of a compile flag during the build that when set it uses the user-input path instead of the default one? For example `make hiro=gtk3 prefix='/app/share/'` ?
