### ISSUE TITLE
[Feature Request] Sound Controlling Hotkeys.

### ISSUE THREAD

**Issue by sm3b3** [higan-emu/ares#1181]
**Describe the solution you'd like**
Hi, if it would not be too much trouble, I would like to request a QoL Feature: Sound related hotkeys, which are:
1) Mute/Unmute Volume (Toggle). 
2) Raise Volume.
3) Lower Volume.

**Describe alternatives you've considered**
Manually muting/unmuting, raising/lowering the volume via entering the settings.

**Additional context**
If they were to be added, I believe that ideally they should be freely configurable by the user.

Thank you very much for your hard work.

**Comment by LukeUsher** [comment]
Solved in PR #1185
