### ISSUE TITLE
Controllers plugged in after starting ares not detected

### ISSUE THREAD

**Issue by RetroEdit** [higan-emu/ares#1190]
If I plug in my controller before starting ares, it's detected fine. If I plug it in after, it isn't detected.

I'm running ares v133 on Windows 10, using an iBuffalo Classic USB Gamepad, model BSGP815GY.

**Comment by rambo919** [comment]
Bug not present in version 126

**Comment by RetroEdit** [comment]
I just now tested this on v126 myself, and for me it *is* present on that version as well.

There are some additional details: ares will properly handle the case where you start with it plugged in when ares launches, and then you unplug it and replug it back in. But if it wasn't plugged in when ares starts, it won't be recognized.

**Comment by rambo919** [comment]
Sorry read wrong, the bug I have registers no key presses at all.

**Comment by LukeUsher** [comment]
We need more info on this; for example which input driver is using used in ares settings? Does it impact ALL drivers on all platforms, or just some of them?

**Comment by RetroEdit** [comment]
Can't speak to other platforms, but on Win11, the only option I see in the configuration page under `Drivers > Input` is the `Windows` driver.

**Comment by remutro** [comment]
SDL should now be available as an input driver on current versions of ares. Does this problem still occur when using the SDL input driver?

**Comment by RetroEdit** [comment]
Doesn't seem to be an issue with the SDL input driver.

**Comment by LukeUsher** [comment]
Limitation of the "Windows" input driver, SDL should be the recommendation going forward.
