### ISSUE TITLE
[N64] Jet Force Gemini Black Screen After Ichor boss

### ISSUE THREAD

**Issue by VGF64** [higan-emu/ares#1195]
After getting the last hit on the boss, the screen immediately turns black and stays like that indefinitely. The game didn't technically crash, as the game was still running at 60fps. Anyone have a clue?

Before: 
![Screenshot (8)](https://github.com/ares-emulator/ares/assets/126835875/95c17b13-6956-46c3-bb45-a146b0a6abe8)

After: 
![Screenshot (10)](https://github.com/ares-emulator/ares/assets/126835875/2a828246-5c6e-42c7-b8c7-a1115dc7ad7f)

Edit: I'm running with Ares v133.

**Comment by kev4cards** [comment]
I can confirm this issue still exists using a build from the commit from August 19th. Attached are two save states. The first was made in the room prior to the boss. The second is during the boss battle. For the second, unpause and just strafe left just a nudge as the explosives go off.
[Jet-Force-Gemini-USA-ares-e8b8552.zip](https://github.com/ares-emulator/ares/files/12404467/Jet-Force-Gemini-USA-ares-e8b8552.zip)

**Comment by kev4cards** [comment]
[Jet-Force-Gemini-USA-ares-e8b8552-interpreters.zip](https://github.com/ares-emulator/ares/files/12425154/Jet-Force-Gemini-USA-ares-e8b8552-interpreters.zip)
Attached are two save states just like before. This time they are from a build where both the CPU and RSP interpreters enabled (the remaining accuracy.hpp flags were left unmodified). Slot 3 is the room before the boss. Slot 4 is during the boss fight. Unpause, strafe left, and wait out the explosions.
Additionally, the provided log was created off of the save state (first needed to confirm the bug was still happening) and includes every item checked by the tracer.

**Comment by VGF64** [comment]
> [Jet-Force-Gemini-USA-ares-e8b8552-interpreters.zip](https://github.com/ares-emulator/ares/files/12425154/Jet-Force-Gemini-USA-ares-e8b8552-interpreters.zip) Attached are two save states just like before. This time they are from a build where both the CPU and RSP interpreters enabled (the remaining accuracy.hpp flags were left unmodified). Slot 3 is the room before the boss. Slot 4 is during the boss fight. Unpause, strafe left, and wait out the explosions. Additionally, the provided log was created off of the save state (first needed to confirm the bug was still happening) and includes every item checked by the tracer.

Hello, I can't load the four save states you provided. Unless I'm doing something wrong?

**Comment by kev4cards** [comment]
VGF64: You should be able to. Make sure that the save state names match your ROM name. For the latter zip, you will need to compile ares, setting both the CPU and RSP interpreter flags to 1 (lines 6 and 14 of accuracy.hpp) beforehand, if you want to check out those save states.

**Comment by kev4cards** [comment]
@VGF64 As of commit 3f4334e, I am no longer encountering a black screen hang and can finish out the Ichor level. May you confirm?
Link to GitHub Actions CI build summary: https://github.com/ares-emulator/ares/actions/runs/7541232760

**Comment by kev4cards** [comment]
@LukeUsher Can be closed. The commit mentioned above does indeed fix the issue.
