### ISSUE TITLE
[Feature Request] Customizable Load Menu: Ability to Hide Entries.

### ISSUE THREAD

**Issue by Zilgaf** [higan-emu/ares#1202]
Dear Ares team, I would like to suggest the possiblity to customize the "Load" menu by manually choosing which system entries will be displayed.

As you may know, the "Load" menu displays a large number of system-specific entries.
This makes navigating the menu cumbersome and time-consuming, which can be overwhelming for some users.

By providing the option to manually select which entries appear in the menu, users can streamline the menu and focus on the systems they actually need.

The requested feature would avoid the need to sift through numerous entries that are not relevant to them.

I believe that this customization feature would greatly improve the user experience of the Ares emulator, making it more streamlined and efficient to use.

Best regards.

**Comment by Mastergatto** [comment]
Ares once had this useful function, sadly it was removed with commit https://github.com/ares-emulator/ares/commit/b03a942bf4d642009de1b2d6408f152db9359760  .

**Comment by remutro** [comment]
If you compile yourself, you can specify the cores option like this

cores="n64 sfc fc"

ares will only compile specified cores, and the Load menu will update accordingly.

**Comment by LukeUsher** [comment]
restored as of [c7c80d0](https://github.com/ares-emulator/ares/commit/c7c80d07ee7f1a578df03fdfe523448ced9a03fb)
