### ISSUE TITLE
Can't assign gamepad butons with version 133 from Flathub

### ISSUE THREAD

**Issue by bmsuseluda** [higan-emu/ares#1219]
**Describe the bug**
I use ares on my steam deck from flathub. With the version 133 i can't assign buttons to my gamepad. Assigning a keyboard key works, but not from a gamepad. It worked in the past.

On my manjaro desktop i could reproduce the bug from flathub, but if use the aur version assigning works, so the bug is flathub specific.

**To Reproduce**
1. Download ares version 133 form flathub
2. go to settings -> input
3. assign a button to your gamepad

**Expected behavior**
Assigning buttons to a gamepad works like before and like the aur version.

**Comment by remutro** [comment]
The ares team doesn't provide Linux builds or packaging directly, this is handled by third party package maintainers. 

If you haven't already, most people have the best luck using the SDL input driver, which can be set in Settings > Drivers. If this option isn't available as a driver, the package maintainer didn't have the necessary SDL dev libs installed when they built ares (they are listed in the Readme).

**Comment by bmsuseluda** [comment]
oh i did not know that i can change the input driver. with sdl it works.
thank you
