### ISSUE TITLE
[N64] Pyoro 64 - Missing eeprom512

### ISSUE THREAD

**Issue by wwark** [higan-emu/ares#1244]
Before submitting an issue, please use the search to make sure an issue doesn't already exist, you should also make sure your rom is not a bad dump, by comparing against the hashes in the No-Intro (Cartridges) or Redump (CD-ROM) databases.

**Describe the issue**
On the manifest of Pyoro 64 game, it says no memory but the game required the eeprom512 and we have this screen on game
![image](https://github.com/ares-emulator/ares/assets/469461/6e161a86-06dd-48b0-aaf4-03705a3ea3ba)

**Rom Information**
Specify the impacted rom filename and any associated hashes (sha256 preferred);.
The easiest way to do this is to open the game in ares, and go to "Tools -> Manifest" and copy/paste the contents.

```
file: Some Game (REGION).ext
sha256: <hash>
```
Sha256
fc3539c45589f79fea2b30a7d5586b4f5d7c3dfbed4eef263bbecec1bfbefcd8  Pyoro 64 (Unknown) (NTSC) (Aftermarket) (Unl).z64

Thanks,

**Comment by rasky** [comment]
Homebrew N64 games are expected to follow the advanced header format to declare their save game requirements:
https://n64brew.dev/wiki/ROM_Header

The author should update the game to include that, and Ares would then automatically emulate the EEPROM.

**Comment by wwark** [comment]
Sure not following the header is not good.
But on Ares emulator I didn't find the option to set the EEPROM manually. Is it possible ? 

Thanks

**Comment by rasky** [comment]
No, it's not possible. Ares doesn't allow to configure additional peripherals in cartridges -- it normally knows what's in each game via a database of games, or using special support like the homebrew header.

**Comment by wwark** [comment]
thank you for your time :+1:
