### ISSUE TITLE
~10% performance regression in Mega Drive core

### ISSUE THREAD

**Issue by invertego** [higan-emu/ares#1246]
Commit 379091bada81215eb642200b018cdb1b1235e387 effectively forces the emulation thread and the video thread into serial execution, as `Screen::setColorBleedWidth()` is called every scanline and acquires a mutex that is held for the duration of `Screen::refresh()`.

**Comment by LukeUsher** [comment]
Fixed at f976cdc3a8ca952bdb781ba9b819acf62a291e50
