### ISSUE TITLE
[N64] Turok Level 4 Bug

### ISSUE THREAD

**Issue by voidflower-xcii** [higan-emu/ares#1256]
When going through the portal for level 4, the transition effect isn't as smooth as the previous portals, and when the level finally loads the ammo counter completely disappears. I tried it on the nightly build and it works as intended.

Rom Information
Turok - Dinosaur Hunter (USA) (Rev 2).z64
3F46508AFD36173886F8A6EA65066663C431BE9E1EDB8D299356569D87E48BAB
Ares V133

**Comment by PeterSamuels** [comment]
If it works on the nightly build then it is already fixed.

**Comment by voidflower-xcii** [comment]
Ah, my bad then. I only reported it still because I notice sometimes the nightly will have some regressions, like DK64's demo breaking on it again for me.
