### ISSUE TITLE
[Master System] Hokuto No Ken not working

### ISSUE THREAD

**Issue by OmegaOmega** [higan-emu/ares#1257]
Hokuto no Ken doesn't boot. The emulated Master System displays the following error:

> V1.3
> Master System © SEGA 1996
> Software Error

**Rom Information**
Downloaded from a No Intro set

game
  sha256: a92f7a68fb5bd9835eeaacb6bb0682f9982ff946ac922345439022feda9b9b45
  name:   Hokuto no Ken (Japan)
  title:  Hokuto no Ken (Japan)
  region: NTSC-J, NTSC-U, PAL
  board:  Sega
    memory
      type: ROM
      size: 0x20000
      content: Program
    memory
      type: RAM
      size: 0x8000
      content: Save

```
file: Some Game (REGION).ext
sha256: <hash>
```

**Comment by FitzRoyX** [comment]
This game requires the region to be set to Japan

**Comment by LukeUsher** [comment]
Not a bug: unlicensed and japanese games do not have valid signatures and can NOT be started by a US or EU master system bios;

Make sure your emulation region is Japan, and that the bios you're using for the Japan region is a proper Japanese bios, not an international one.
