### ISSUE TITLE
[Master System] I tried booting some Unlicensed and/or Aftermarket games. These are my findings

### ISSUE THREAD

**Issue by OmegaOmega** [higan-emu/ares#1258]
These ROMs are part of the No Intro set. There are 3 types of errors that I've found.

**>Console boots without recognizing the cartridge, directly to the BIOS**

>Bobble Bobble (Korea) (En) (Unl)
>Zemina Rompack - Q-Bert + Sports 3 + Gulkave + Pooyan (Korea) (Unl)
>Ttoriui Moheom (Korea) (En) (Unl)
>Three Dragon Story, The (Korea) (Unl)
>Tank Battalion (Korea) (Unl)
>Tangram (Brazil) (Aftermarket) (Unl)
>Super Tetris (Korea) (Unl)
>Super Penguin (Korea) (Unl)
>Super Boy I (Korea)
>Super Boy II (Korea) (En) (Unl)
>Super Boy 4 (Korea) (Unl)
>Sudoku (Brazil) (Aftermarket) (Unl)
>Sky Jaguar (Korea) (Unl)
>Senha (Brazil) (Aftermarket) (Unl)
>Sagak-ui Bimil (Korea) (En) (Unl)
>Road Fighter (Korea) (En) (Unl)
>Puzzle Game (Korea) (En) (Unl)
>Ppang Gongjang (Korea) (En) (Unl)
>Power Boggle Boggle (Korea) (En) (Unl)
>Pooyan (Korea) (En) (Unl)
>Pigu-Wang 7 Hap - Jaemiiss-neun Game Mo-eumjip (Korea) (Unl)
>Palhacos (Brazil) (Aftermarket) (Unl)
>Nouka Densetsu (World) (Ja) (Aftermarket) (Unl)

**Error displayed by the console:
>V1.3
>Master System © SEGA 1996
>Software Error**

>11 Hap Gam-Boy (Korea) (Unl)
>94 Super World Cup Soccer (Korea) (Unl)
>Astro Warrior & Pit Pot (Brazil) (En) (2011 Master System Evolution) [Not a bootleg]
>Thunder Blade (Taiwan) (En) (Unl)
>Super Arkanoid (Korea) (Unl)
>Suho Jeonsa (Korea) (Unl)
>Strider, The (Taiwan) (En) (Unl)
>Shangwei Mingling (Taiwan) (En) (Unl)
>Quartet (Taiwan) (En) (Unl)
>Northen Ken (Taiwan) (Ja) (Unl)

>Game doesn't go even past the "SEGA" screen:

>Super Boy III

Some games actually work! These are:

>Wonsiin (Korea) (Unl)
>Waternet (Unknown) (Aftermarket) (Unl)
>Toto World 3 (Korea) (Unl)
>Street Master (Korea) (Unl)
>Skazka (Unknown) (v2.0) (Aftermarket) (Unl)
>Simpsons Trivia (Unknown) (v2.0) (Aftermarket) (Unl)
>Penguin Adventure (Korea) (En) (Unl)

**Comment by PeterSamuels** [comment]
All the Super Boy games except 3 work for me on the latest nightly.

**Comment by FitzRoyX** [comment]
These games require the Japan region to be set

**Comment by LukeUsher** [comment]
Not a bug: most unlicensed and Japanese games do not have valid signatures and can NOT be started by a US or EU master system bios;

Make sure your emulation region is Japan, and that the bios you're using for the Japan region is a proper Japanese bios, not an international one.

@PikaSamus any chance you can create an issue for those three?

**Comment by PeterSamuels** [comment]
> Not a bug: most unlicensed and Japanese games do not have valid signatures and can NOT be started by a US or EU master system bios;
> 
> Make sure your emulation region is Japan, and that the bios you're using for the Japan region is a proper Japanese bios, not an international one.
> 
> @PikaSamus any chance you can create an issue for those three?

I have my preferred region set to Japan so that is likely why it worked. I don't think it's problematic.

**Comment by OmegaOmega** [comment]
Ooohhh I see. I guess the Japanese BIOS is more compatible then?
Ares doesn't change the region automatically then?
