### ISSUE TITLE
[MD] Post-credits boss list in Alien Soldier (J) doesn't display properly at times, gets progressively worse

### ISSUE THREAD

**Issue by DrippingYellow** [higan-emu/ares#1264]
Several bosses in the "Bosses Introduction" section of the ending have trouble being displayed. Bugmax is partially cut off by a set of glitched tiles that stick around even into the next boss, Joker, and Flying-Neo incorrectly uses Madam Barbar's graphics (not pictured). From there, it only gets worse: starting with Sunset Sting, the entire screen is completely covered in glitch tiles, and only Xi-Tiger actually uses his intended sprites. Even the Treasure and SEGA logos are garbled.

I have not experienced graphical issues like this anywhere else in the game, nor in any other game I've played. I'm on the latest release version of ares, v133.

![Screen Shot 2023-10-20 at 11 11 53 AM](https://github.com/ares-emulator/ares/assets/106562603/e20e2765-2acb-46ca-9145-e3fdf11646d9)
![Screen Shot 2023-10-20 at 11 12 03 AM](https://github.com/ares-emulator/ares/assets/106562603/11b4a714-49a9-40fd-92e4-8b10572d7fdd)
![Screen Shot 2023-10-20 at 11 13 05 AM](https://github.com/ares-emulator/ares/assets/106562603/9572208c-d5b8-4a6f-a9d0-1807b9911845)
![Screen Shot 2023-10-20 at 11 14 15 AM](https://github.com/ares-emulator/ares/assets/106562603/d3b364fd-ee51-4d36-b273-1d46c9104190)
![Screen Shot 2023-10-20 at 11 59 56 AM](https://github.com/ares-emulator/ares/assets/106562603/f537d644-6635-4eca-8161-9b862740d09f)

**Comment by FitzRoyX** [comment]
Can you post the checksum of your rom and a savestate?

**Comment by DrippingYellow** [comment]
I'm assuming the (rom name).bs# files are the save states? If so, here's a save state about midway through the credits, and a save state right as the boss introduction is starting.
[AlienSoldierSavesates.zip](https://github.com/ares-emulator/ares/files/13097135/AlienSoldierSavesates.zip)

According to the [Sega Genesis Checksum Utility](https://github.com/mrhappyasthma/Sega-Genesis-Checksum-Utility/tree/master) (idk if it's reliable or not), the "header checksum" is
`0x834F` and the "computed checksum" is `0xC0DC`

(Also, I'm aware that the save states are named "Alien Soldier (U)", that's just what the rom was named when i... obtained it, shall we say. It's definitely the Japanese release though, there's text at the bottom of the intro that's in Japanese.)

**Comment by FitzRoyX** [comment]
By checksum I mean, when the game is running, go to Tools>Manifest and copy paste the sha256 value here.

**Comment by DrippingYellow** [comment]
Well, this is awkward... I looked at the manifest page and apparently the rom I was using was, in fact, an NSTC-U rom. I found another rom that explicitly says "Alien Soldier (Japan)" and lo and behold, the manifest page listed it as being NSTC-J and PAL. The manifest itself is also completely different between the two roms.
For some reason my Mac won't let me copy-paste the manifests, so here's some screenshots of the manifest screen
![Screen Shot 2023-10-23 at 11 00 21 PM](https://github.com/ares-emulator/ares/assets/106562603/a0dda837-2e9e-47d4-af19-640d1e81c166)
![Screen Shot 2023-10-23 at 11 00 48 PM](https://github.com/ares-emulator/ares/assets/106562603/4ac1b475-a111-4dfc-8934-64d428c85701)
I checked the credits in the actual Japan version, and it seems to be working fine, so that settles that. The question burning in my mind now is, what did I even download at first??? Why is it NSTC-U, but the intro text matches the Japanese version? Maybe it was a bootleg this whole time...

**Comment by FitzRoyX** [comment]
Yeah I think your rom is a hack of the pal rom or something. The game was never released in America, so there was apparently an effort to combine the fixed english of pal with the 60hz speeds of japan, and they must've screwed something up. So not an emulator bug. Make sure to use verified no-intro romsets if you don't want fun surprises like this.

**Comment by LukeUsher** [comment]
likely broken romhack
