### ISSUE TITLE
Prefetch position in ASL and SR Instructions does not match

### ISSUE THREAD

**Issue by vmicka72** [higan-emu/ares#1275]
When i compare the timings of the instruction :

https://github.com/ares-emulator/ares/blob/d201d6a54770dc8286f1875c9b0547b67411e0f5/ares/component/processor/m68000/instructions.cpp#L198

With his equivalent in ASL i find the timing order strange.

ASL : 

```
template<u32 Size> auto M68000::instructionASL(DataRegister from, DataRegister with) -> void {
  auto count = read<Long>(from) & 63;
  **prefetch();**
  idle((Size != Long ? 2 : 4) + count * 2);
  auto result = ASL<Size>(read<Size>(with), count);
  write<Size>(with, result);
}
```

ASR : 
```
template<u32 Size> auto M68000::instructionASR(DataRegister from, DataRegister with) -> void {
  auto count = read<Long>(from) & 63;
  idle((Size != Long ? 2 : 4) + count * 2);
  auto result = ASR<Size>(read<Size>(with), count);
  **prefetch();**
  write<Size>(with, result);
}
```

In one case the prefetch is done just after the Long Reading, in other case no.
This is correct?

**Comment by TascoDLX** [comment]
I can confirm, it should be prefetch first for all register shifts, so ASR has the order incorrect. Good catch!
