### ISSUE TITLE
[Feature request] Adding support for dualsensX / dualsenseM

### ISSUE THREAD

**Issue by nan0tEch** [higan-emu/ares#1284]
Is it possible to add controler support via windows DualsenseX and mac DualsenseM. It seems that these driver send data over the midi OSC protocol, its even possible to setup the adaptive triggers which would be fun to setup for games in the emulator. Maybe i possible way to send rumble info from N64 to the controler.

for more dev info visit https://dualsensex.com

**Comment by PeterSamuels** [comment]
I think rumble for Dualsense is already supported in nightly builds without DualsenseX or M by using the SDL input driver. I don't know about the trigger stuff though.

**Comment by LukeUsher** [comment]
It is not planned to add custom controller drivers to ares at this time; consider trying the SDL2 driver on nightly; I'd expect that to support rumble quite well on the DualSense.
