### ISSUE TITLE
Driver options not being saved on quit

### ISSUE THREAD

**Issue by kathyrollo** [higan-emu/ares#1303]
**Describe the bug**
After changing the audio/video driver options in Settings, they revert to default values after exiting the emulator.

**To Reproduce**
Change Video to **Direct3D 9.0** and Audio to **XAudio 2.1**.

![Screenshot 2023-11-28 113658](https://github.com/ares-emulator/ares/assets/28589393/0a2669ef-a005-4613-8488-d00fe93ed963)

Quit the emulator and go to Drivers settings again.

Video is back to **OpenGL 3.2** and Audio is back to **WASAPI**.

![Screenshot 2023-11-28 113724](https://github.com/ares-emulator/ares/assets/28589393/aa2e33e1-6c7f-4636-9558-e6e3999a02fd)

**Expected behavior**
Selected driver options should persist after exit.

**Comment by remutro** [comment]
Make sure you have the application in a directory that doesn't require administrative permissions (like Program Files) or the app won't be able to write to the settings.bml file. You could try starting ares with the "Run as Administrator" option, make changes, and close the app and then see if settings were saved to see if it is an administrative permissions issue.

**Comment by kathyrollo** [comment]
![Screenshot 2023-11-28 124555](https://github.com/ares-emulator/ares/assets/28589393/7050194f-7be7-4a49-97a1-129964d5cdc2)

Hi @remutro, my emulators are on a separate partition with read/write permissions. I am also admin on my machine and did "Run as administrator" as suggested to be sure but arrived at the same outcome. Other options save fine and the `settings.bml` also maintain my button mappings, so I'm certain that file is being written to.

Can you check if you can replicate the issue on your end?

Edit: Added screenshot of Security permissions on SSD partition.

**Comment by remutro** [comment]
I was reminded that in order for driver settings to take effect, and save, you need to click on the reload button next to the dropdown list to apply the driver changes, and which [potentially] changes what options are available depending on driver selected. Driver settings should then be written out/saved properly after the reload button is used. We were discussing some options to possibly change button text and/or add hints as a usability improvement here, so you can leave this issue open even if you confirm driver options save when the reload button is used. 

Note the second issue you opened is different and seems to be a separate issue that needs more investigation.

**Comment by kathyrollo** [comment]
Hi @remutro, I confirm clicking the Reload button persists the selected driver options after exit. I also agree a hint to click the button is a useful UX improvement as the additional action is not very obvious. Changing the button from "Reload" to "Save" should be the path of least effort. 👍 

Thought it was best to raise separate tickets. Thanks for looking into both issues. Cheers!

**Comment by Kawa-oneechan** [comment]
Perhaps "Save and Reload"?

**Comment by LukeUsher** [comment]
Fixed as of 0dd3edebe0fa07b7c0d16cacd2a83ea6adbf8060

Renamed "Reload" to "Apply" in  f9d38f5dafed00e61d7886cc1508da6397ac642c
