### ISSUE TITLE
Deep Black Boost option not saving on quit

### ISSUE THREAD

**Issue by kathyrollo** [higan-emu/ares#1304]
**Describe the bug**
Related to #1303, but on Video settings this time. Other options persist on exit. 

**To Reproduce**
Enable `Deep Black Boost` option.

![Screenshot 2023-11-28 125500](https://github.com/ares-emulator/ares/assets/28589393/e561ddfe-81fb-4771-8fdd-1ea3893916bd)

Quit and reopen emulator. Option is unticked again.

![Screenshot 2023-11-28 125855](https://github.com/ares-emulator/ares/assets/28589393/bf99d589-40c2-436c-b3c7-74fc7276c417)

**Expected behavior**
Changes should persist after exit.

**Additional context**
Unlikely due to read/write permissions of the Ares directory as other options save ok to the `settings.bml` file.

**Comment by LukeUsher** [comment]
Fixed in 0dd3edebe0fa07b7c0d16cacd2a83ea6adbf8060
