### ISSUE TITLE
[N64] [macOS] [arm64] Crash on CPU allocator flush when using recompiler

### ISSUE THREAD

**Issue by jcm93** [higan-emu/ares#1305]
**Describe the bug**
Ares crashes when flushing the N64 CPU code cache on Apple Silicon. Not sure if unique to macOS or arm64, this is just my test environment. At least one report that it is not reproducible on x64. I narrowed down the offending commit by performing a bisect and found that the behavior is present since 8ed4af8b57bb5a67a9976e9dbd58db1b75152a2f.

**To Reproduce**
Any N64 game seems to trigger the crash. Tested with Snowboard Kids, Majora's Mask, Star Wars Episode I: Racer. It can be reproduced quickly by reducing the size of the cache in [`ares/n64/cpu/recompiler.cpp:27`](https://github.com/ares-emulator/ares/blob/2a819403db36a585fa5b1a268196f46e47d2be1f/ares/n64/cpu/recompiler.cpp#L27). I replaced `1_MiB` with `63_MiB` for testing. With that small a cache, most games will crash on startup or soon afterward.

**Expected behavior**
Ares should not crash when flushing the cpu code cache :(

Edit: I should probably attach a crash trace. [ares-2023-11-29-135053.ips.zip](https://github.com/ares-emulator/ares/files/13505787/ares-2023-11-29-135053.ips.zip)

**Comment by LukeUsher** [comment]
Fixed as of #1306
