### ISSUE TITLE
[MD/32X] Ares can not fully play a VGM track

### ISSUE THREAD

**Issue by viciious** [higan-emu/ares#1323]
**Describe the bug**
Music playback stops and leaves a hanging note.

**To Reproduce**
Load the test ROM and let it play.

https://drive.google.com/file/d/10ctMcsU1MU0bhYU2G92B04wZKn2SFjS4/view?usp=drive_link

**Expected behavior**
The music should continue as normal.

**Additional context**
Works fine in Gens and Fusion.

**Comment by viciious** [comment]
OK, after some further investigation, we now believe it's actually a software issue that always manifests on real hardware and in ares in 90% of runs. Will post here once I have more info

**Comment by viciious** [comment]
OK, so it's a software issue indeed. One observed difference between ares and real hardware is that it does play through the whole thing in 10% of cases, real hardware always stops at around the 1:04 mark.

**Comment by LukeUsher** [comment]
I would be interested to discover what the difference is that causes it to always fail on hardware but only sometimes fail on ares? Is there a chance it’s something hardware revision specific?

**Comment by viciious** [comment]
It's really hard to tell.. The problem had something to do with buggy z80 <-> m68k interaction code.

**Comment by LukeUsher** [comment]
Thanks, will close
