### ISSUE TITLE
[MD] Trouble Shooter/Battle Mania: Controls aren't working properly

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#1329]
**Describe the issue**
Controls are completely messy in this game.

You can't change options.
In equipment selection, it's pressing right all the time.
In the game itself you can't control horizontal positioning.

The issue happens regardless the use of default control pad or fighting pad.

**Rom Information**

```
  sha256: cc4e6374eb458776a1d184901851d71ecfa26eaa89853fec65cd9a7a533a00a9
  name:   Trouble Shooter (USA)
```

```
  sha256: 246e0a8da5d00e054af3fdeca8d54ca713163f9d29bb935336199182a6fe3b51
  name:   Battle Mania (Japan)
```

```
  sha256: 6cd79af88e497dab213a116969ab0c7720fafe4007ee3a18c3fc9441100779bd
  name:   Trouble Shooter (USA) (Beta) (1991-09-12)
```

**Comment by LukeUsher** [comment]
This sounds very similar to #1177

**Comment by FitzRoyX** [comment]
If you unplug controller 1, the autoscroll that happens at weapon selection stops, so that kind of tells us it's related to controller polling? Would have to be a very obscure edge case to only affect two games.

Oh, I see, it's already been documented by Eke
