### ISSUE TITLE
What BIOS does Neo Geo AES and Neo Geo MVS use?

### ISSUE THREAD

**Issue by milnak** [higan-emu/ares#1352]
**Describe the bug**
Scan in latest ares no longer detects the Neo Geo AES or Neo Geo MVS bios.  All other BIOS files are detected fine.

**Expected behavior**
BIOS detected.

**Additional context**
It seems like it should be "sp-45.sp1" in a zip file for MVS, and "neo-epo.bin" for a zip file for AES? But these aren't working for me, e.g.:

```
> unzip -v '.\Neo Geo AES - BIOS (World).zip'
Archive:  ./Neo Geo AES - BIOS (World).zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
  131072  Defl:X    23096  82% 12/24/1996 23:32 d27a71f1  neo-epo.bin
--------          -------  ---                            -------
  131072            23096  82%                            1 file
```

**Comment by remutro** [comment]
Quick comment, I'll try to test it out more thoroughly when I get a chance.

First, MVS doesn't work at all right now so don't waste your time. However you are correct that ultimately it looks for "sp-45.sp1" and being zipped (with a .zip extension) is also fine. 

You also have the correct AES file (which does work) - neo-epo.bin and again being in a zip should be fine. 

You should also be able to use the unibios, if you rename to the expected neo-epo.bin name.

Edit: Oh, the auto-scan. Then ya exactly what Luke said. You'll have to manually set the AES firmware path using the neo-epo.bin file (which can be the original or the unibios renamed).

**Comment by LukeUsher** [comment]
The scan feature just looks for file hashes and cannot read the contents of zip files, it's just a simple "lookup all files in your bios directory and match with known hashes", and nothing more.

This is a new feature for the current version, so it is not "no longer detects" but a case of it never has; at least, not within zip files.

Autodetect is always a best effort anyway, use a non-standard bios revision and it will fall part for any system.

**Comment by FitzRoyX** [comment]
This is just MAME legacy jank not keeping firmwares separate and then naming things in the most cryptic fashion possible.

**Comment by LukeUsher** [comment]
To clarify: you can use *any* neo geo compatible bios; either neogeo.zip/aes.zip for AES and MVS respectively, or any one of the bios .bin files from within if you want to emulate a specific region/revision (or unibios)
