### ISSUE TITLE
Super Nintendo Entertainment System / Super Famicom - Super Nintendo Campus Challenge 1992

### ISSUE THREAD

**Issue by piscsfy** [higan-emu/ares#1361]
Super Nintendo Campus Challenge 1992 (Japan) (En) (Competition Cart).sfc 
sha256: 67c1a4917f4cd0fd704b83330a7e91763736c2d2a10a7e12318fdac54cd9c6c6

Game displays nothing

**Comment by hackgrid** [comment]
Fixed by #1656

**Comment by hackgrid** [comment]
Works with ares 141
