### ISSUE TITLE
Is there a vision for an online mode in ngpc?

### ISSUE THREAD

**Issue by ameliandev** [higan-emu/ares#1379]
**Additional context**
Hi! Thanks for this awesome emulator. I use it to play many systems, specially for ngpc, for me, the best emulator for this system.

We (the ngpc community neogeopocket.es) are waiting to play online some day, so, I ask you, Is there a possibility to play online in the ngpc in the future? Is there any progress on this?

Many many thanks

**Comment by LukeUsher** [comment]
Netplay isn't planned at this time, that being said there already is an open issue for this, see https://github.com/ares-emulator/ares/issues/881
