### ISSUE TITLE
Add bilinear filtering please?

### ISSUE THREAD

**Issue by ghost** [higan-emu/ares#1382]
Add bilinear filtering please?

the slight blurriness added by this blends pixels close to what they were intended to look like on old displays.

**Comment by LukeUsher** [comment]
We have had this since day 1, select “Blur” in the shaders menu.

**Comment by ghost** [comment]
Blur in the menu doesnt seem to work for me. Across multiple computers. Shaders work. Blur doesn’t. It does on bsnes but not on this. Is it working on your system? Tried this on my htpc and two laptops.
