### ISSUE TITLE
[GB] MBC4 mapper support

### ISSUE THREAD

**Issue by ReNardier** [higan-emu/ares#1386]
https://twitter.com/LuigiBlood/status/1444084152815468545

**Comment by LuigiBlood** [comment]
Why? Nothing works with it. You can just use MBC3 and it'll be the same thing.

**Comment by LukeUsher** [comment]
Any released GameBoy software has never used this mapper, and as there is no software available, there is no way to determine how it works so it can be implemented.

Marking as wontfix for now.
