### ISSUE TITLE
Knuckles' Chaotix (Japan, USA) (En) (Beta) (1994-12-07) and Knuckles' Chaotix (Japan, USA) (En) (Beta) (1994-12-27) no longer boot as of ares v134

### ISSUE THREAD

**Issue by ehw** [higan-emu/ares#1396]
**Describe the bug**
Knuckles' Chaotix (Japan, USA) (En) (Beta) (1994-12-07) and Knuckles' Chaotix (Japan, USA) (En) (Beta) (1994-12-27) no longer boot as of ares v134. Both games were bootable prior to v134.

**To Reproduce**
1. Make sure you have the latest version of ares (v135 milestone or the latest nightly as of writing)
2. Open ares.exe
3. Click "Load"
4. Go to "Sega -> Mega 32X ..."
5. Navigate and load Knuckles' Chaotix (Japan, USA) (En) (Beta) (1994-12-07) or Knuckles' Chaotix (Japan, USA) (En) (Beta) (1994-12-27).32x

**Expected behavior**
The game should've boot to the Sega logo. Instead, it boots to a black screen.

**Screenshots**
ares v133:
![image](https://github.com/ares-emulator/ares/assets/885618/dbd0282e-e0cd-4888-9db3-17b81219910d)

ares 2024-02-16 19:26:37 UTC
![image](https://github.com/ares-emulator/ares/assets/885618/60d54281-6fe0-4899-bf1a-891b81a9669c)

**Additional context**
These two builds in particular are infamous that they require certain timings in order to boot. Real hardware, earlier versions of ares, and certain builds of Kega Fusion are the only things that can boot these. I tried to bisect to find a specific commit that broke this but I can't.

**Comment by LukeUsher** [comment]
Should be fixed as of [9ae2e43](https://github.com/ares-emulator/ares/commit/9ae2e43c68cc02c89fd41012422703567f56ad57)

**Comment by ehw** [comment]
This seems to be broken again. I wasn't able to test [9ae2e43](https://github.com/ares-emulator/ares/commit/9ae2e43c68cc02c89fd41012422703567f56ad57) at the time but it looks like there were some more changes since.

**Comment by LukeUsher** [comment]
Fixed (again) as of [8ff1043](https://github.com/ares-emulator/ares/commit/8ff104393eed00e48bee6911e50bddbd5d827dd7)
