### ISSUE TITLE
[SEGA CD] CD+G does not display even with subchannel file.

### ISSUE THREAD

**Issue by HeroponRikiBestest** [higan-emu/ares#1398]
**Describe the bug**
If you attempt to play a music CD on the Sega CD, even with a subchannel file containing the +G data, no graphics are displayed. 

**To Reproduce**
Obtain a music CD with +g data.
Start the Sega CD emulator using the image with the subchannel file alongside it.
Choose play, and set "CD+G" on in the Sega CD-player UI.

**Expected behavior**
I expected the +G data to display

**Screenshots**
![image](https://github.com/ares-emulator/ares/assets/50224630/3490c23f-5797-4a51-afd6-4c5165850078)

**Additional context**
At the moment, there is no way to test if ripped CD+G images had their subchannel data dumped properly, and anyone who dumps +G discs has to put them on a Sega Saturn/CD via an ODE (or burned disc). This would be extremely helpful for both checking and viewing +G data on dumped CDs.

**Comment by LukeUsher** [comment]
When a .sub  channel is present, subchannels are parsed and loaded by the ares cd-rom loader, so it is *just* a case of implementing the Sega CD hardware interface for fetching this data so that the bios can see it.

**Comment by LukeUsher** [comment]
Fixed as of 1e83da0241adba9653717754fce845a4ea757be2
