### ISSUE TITLE
On Apple Silicon (Mac M1). gdb cannot be built. What are my debugging options?

### ISSUE THREAD

**Issue by bkimmett** [higan-emu/ares#1408]
I am running Ares on my Apple Silicon MacBook Pro. While Ares can connect to GDB, I cannot build GDB on Apple Silicon as it does not support the architecture.

What are my options? Can Ares connect to lldb? Are there any internal debugging features I can access? Or am I just out of luck?

**Comment by bates64** [comment]
I have the same issue. We just need to find something that implements the other side of the GDB Remote Serial Protocol. A possible path to success is the VS Code debugger?

**Comment by merryhime** [comment]
lldb supports the GDB remote protocol fine.

`gdb-remote localhost:8000`

where 8000 is your selected port number.

**Comment by LukeUsher** [comment]
Closing as an alternate solution was provided
