### ISSUE TITLE
[Mega CD] CD+G graphical glitches

### ISSUE THREAD

**Issue by bikerspade** [higan-emu/ares#1411]
**Describe the bug**
With a high quality CD+G dump of [Fleetwood Mac - Beyond the Mask](https://archive.org/details/fleetwood-mac-behind-the-mask-cdg) in ccd/img/sub/cue format, there are some graphical gliches that are not present when playing the same image on a Sega Saturn (via Terraonion MODE).

**To Reproduce**
1. Load cue/img/sub for this disc in ares (MegaCD)
2. Enable CD+G in CD player menu
3. Play the beginning of track 1 or track 4.
4. See glitches.

**Expected behavior**
To render without glitches like it does on original hardware.

**Screenshots**

https://github.com/ares-emulator/ares/assets/161802532/4bacdbae-5306-4aa0-9411-dee7e202cff4

https://github.com/ares-emulator/ares/assets/161802532/fabfbe1d-c687-49c1-8137-2cbbd8c0ed39

https://github.com/ares-emulator/ares/assets/161802532/188fb7a0-5e19-4a82-8140-5b565553d42d

**Additional context**
I tested multiple different rips of this disc that I produced, and all of them experienced this issue.

**Comment by LukeUsher** [comment]
Should be fixed as of [d53fdb0](https://github.com/ares-emulator/ares/commit/d53fdb0087655b653e61a66d53027224513860b8)
