### ISSUE TITLE
PCEngine does not support multiple Controller pads

### ISSUE THREAD

**Issue by d4nielfr4nco** [higan-emu/ares#1415]
**Describe the bug**
The configurations done in "Controller Pad" are replicated to "Controller Pad 1" (and vice versa). The other "Controller Pads" are ignored. Only the inputs from "Controller Pad" is actually read.

**To Reproduce**
Try some multiplayer game like Bomberman 93/94. An example of scenario: you set up the Controller pad 1 with keyboard and 2 with a Xbox controller. The "Controller Pad" or "Controller Pad 1" will control both players 1 and 2.

**Expected behavior**
The expected behavior would be to have only Controller Pad 1 through 5 to configure, and the Controller Pads are independent of each other.

This was tested on v136, but I believe this bug exist in other versions as well.

**Comment by Tartifless** [comment]
Hello, Did you try enabling multitap ?

**Comment by d4nielfr4nco** [comment]
Thanks for your reply. I didn't find any option for that. Could you please tell me how to enable it?

**Comment by LukeUsher** [comment]
> Thanks for your reply. I didn't find any option for that. Could you please tell me how to enable it?

![image](https://github.com/ares-emulator/ares/assets/740003/71c34b10-d99d-4b53-8cb7-ca8752572eec)

**Comment by d4nielfr4nco** [comment]
Oh, It worked, thanks. I wonder if it would make sense to make multi-tap the default option for PCEngine from the emulator/UI perspective. In any case, I believe we can close this issue since it is not an issue at all.

**Comment by LukeUsher** [comment]
> Oh, It worked, thanks. I wonder if it would make sense to make multi-tap the default option for PCEngine from the emulator/UI perspective. In any case, I believe we can close this issue since it is not an issue at all.

It used to be but we disabled it because having the multitap present by default prevents many games from working at all. The most compatible solution was picked as a default.

**Comment by Tartifless** [comment]
@LukeUsher : do you think there's a chance to see one day these options set in the config.bml file or through command line argument ?
