### ISSUE TITLE
.desktop file is not detected by default (when building from source)

### ISSUE THREAD

**Issue by mayhair** [higan-emu/ares#1421]
When installing ares from source on Linux, a .desktop file is placed in ~/.local/share/applications. However, it isn't detected by GNOME.

By default, the Exec field just points to "ares" (`Exec=ares`). At least on GNOME, it doesn't show up this way. I have to put an absolute path (so, `Exec=/home/[my username]/.local/bin/ares`), and then it works just fine.

Any problems with implementing this? I believe it could be done by just fetching $HOME.

**Comment by XerTheSquirrel** [comment]
In your `~/.profile` do you have something like the following?

```sh
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
```

When the executable is not an absolute path, it will look in `$PATH` for the executable.

**Comment by mayhair** [comment]
D'oh! Silly me. I forgot that simply setting a variable in an interactive shell (as in, `export PATH="$HOME/bin:$HOME/.local/bin:$PATH"`) does not preserve between logouts. So, I added it to my `~/.profile`, and now it's just fine.
