### ISSUE TITLE
game no launch with 7z file

### ISSUE THREAD

**Issue by ViRuSmAn62700** [higan-emu/ares#1436]
Before submitting an issue, please use the search to make sure an issue doesn't already exist, you should also make sure your rom is not a bad dump, by comparing against the hashes in the No-Intro (Cartridges) or Redump (CD-ROM) databases.

**Describe the issue**
the gameboy , gmaeboy color , atari 2600 , supergrapfx , nintendo 64 no start with 7z file

**Rom Information**
atari2600:
  name:   pacman
  title:  pacman
  region: NTSC
  board:  Linear
    memory
      type: ROM
      size: 0x3ec6
      content: Program

gmaeboy:
  sha256: 1c604c6296d118b8183bd15bd80cfa524cf6e3a7f35ab7d9790a8c39f20f11ce
  name:   bombjack
  title:  bombjack
  label:  c  _    ,1  H'.
  board
    memory
      type: ROM
      size: 0xced4
      content: Program

supergrapfx:
  sha256: 4580abf5d1dc0393778d4adaecf1cbb5602948f725008413f5df9dd196f9d098
  name:   1941
  title:  1941
  region: NTSC-U
  board:  Linear
    memory
      type: ROM
      size: 0x91789
      content: Program

maybe it s normal and you work for this but i only want to say to you , i just try you emulator today , and for me it s very hard for found the bios  , only miss 3 bios for have all but for try the game i have the bios

**Comment by remutro** [comment]
7z (7-zip) isn't a supported format at this time. We only support .zip

There is already an existing enhancement request for this where it is discussed, so this is a duplicate: https://github.com/ares-emulator/ares/issues/388
