### ISSUE TITLE
Set gamepad buttons via command line programmatically

### ISSUE THREAD

**Issue by bmsuseluda** [higan-emu/ares#1443]
Hello together,

thank you for this great emulator.
I can set gamepad buttons via command line with `--setting VirtualPad1/Pad.Up=0x3/1/1/Lo;;`.
I would like to do it programmatically but i do not understand the format of `0x3/1/1/Lo`.

I tried with SDL2 but the format is much different.

I hope you can help me and explain how i can create this format.

Thanks in advance
bmsuseluda

**Comment by LukeUsher** [comment]
The format here depends entirely on what hardware and driver you are using, but the format is as follows:

deviceId/groupId/inputId/qualifier.

device_id is the id of your controller as reported by the input driver you are using in ares

Group ID is a device-specific type field, the current format is as follows:

Keyboard:

0 = Button

Mouse:

0 = Axis
1 = Button

Joypad:
0 = Axis
1 = HAT
2 = Trigger
3 = Button

The qualifier is only valid when mapping digital buttons:

Lo = The input is active Low (Pressed if a button, lower than the midpoint value if an AXIS/trigger)
Hi = The input is active High (Higher than the midpoint value if mapping an AXIS/trigger)
Rumble = Not really an input, just mapping which device rumble is mapped to

So for your example mapping
`0x3/1/1/Lo` = `Controller:0x3, Group:HAT, Input:1, Qualifier:Lo`

**Comment by bmsuseluda** [comment]
thank you for this detailed explanation :)
