### ISSUE TITLE
Shaders not working with flatpak version

### ISSUE THREAD

**Issue by Assgoblin83** [higan-emu/ares#1488]
**Describe the bug**
The shaders are not working with the flatpak version of Ares.

**To Reproduce**
1. Download the flatpak version of Ares
2. Apply a shader
3. See that there is no difference

**Expected behavior**
Shader should be applied.

**Additional context**
# System Details Report
---

## Report details
- **Date generated:**                              2024-05-09 13:51:23

## Hardware Information:
- **Hardware Model:**                              ASUS TUF GAMING B650-PLUS WIFI
- **Memory:**                                      32,0 GiB
- **Processor:**                                   AMD Ryzen™ 9 7900 × 24
- **Graphics:**                                    AMD Radeon™ RX 7900 XT
- **Disk Capacity:**                               4,1 TB

## Software Information:
- **Firmware Version:**                            2413
- **OS Name:**                                     Fedora Linux 40.20240505.0 (Bazzite GNOME)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.9-301.fsync.fc40.x86_64

Please let me know if you need any additional information.

**Comment by LukeUsher** [comment]
The flatpack is not created or managed by anybody from the ares team; we just link to it for convenience. 

The person (or persons) who created the flatpak need to integrate librashader into the package. 

There is already an issue for this over at the flatpak repo: 
https://github.com/flathub/dev.ares.ares/issues/36
