### ISSUE TITLE
One Bug, One Request

### ISSUE THREAD

**Issue by RaijinXBlade** [higan-emu/ares#1514]
Bug: Whenever I switch audio sources, Ares doesn't default to it. For example, under Windows, switching from headphones to speakers, the emulator will still manually need to be switched to speakers in the Drivers menu.

Request: A Simple "Game" directory in the Paths menu, that you can navigate from a default location when going to load a game.

**Comment by Screwtapello** [comment]
What audio driver are you using? I recall some of them have a "default" device that automatically switches between target devices as they're plugged and unplugged, and some of them do not (because the underlying API does not provide that feature).

**Comment by RaijinXBlade** [comment]
It's set to WASAPI by default so that. 99% of the time, I'll leave the audio driver alone since tools tend to default to the most stable/reliable/whatever ones.
