### ISSUE TITLE
[NES] Polygondwanaland - 2nd Edition (World) (Aftermarket) (Unl) - Green screen at the start

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#1524]
nightly release on 2024-06-12 16:38:44 UTC

![image](https://github.com/ares-emulator/ares/assets/12481242/dca6149f-ada4-43f0-9311-c21758947607)

**Comment by invertego** [comment]
Bad header? MAME has this listed as UXROM, not UNROM-512: https://github.com/mamedev/mame/pull/9504

You could try changing the mapper to 2 using Mesen (Debug -> NES Header Editor).

EDIT: More comments in this thread: https://forums.nesdev.org/viewtopic.php?t=19940&start=90

> Correction: Polygondwanaland looks like it has the wrong mapper, as it's too large for UNROM512. Oversized mapper 2? Does anyone know the actual INL board type?

> In response to my own question, Polygondwanaland is on an INL-XO-ROM board, based on pics on NoIntro.

**Comment by BenjaminSiskoo** [comment]
I try to change with mesen 2 but it doesn't work. I can't save the rom.

**Comment by invertego** [comment]
Is the rom in a .zip file? You may need to extract it first.

**Comment by BenjaminSiskoo** [comment]
nice catch :) So here the results with Mesen 2 last release : 

the original rom : 

![image](https://github.com/ares-emulator/ares/assets/12481242/ad25547a-59c1-4d58-9914-d9f0a5354862)

modified rom to mapper 2 : 

![image](https://github.com/ares-emulator/ares/assets/12481242/03c3ecc6-4bc7-48cc-a0f5-6061795ab592)

It works

**Comment by invertego** [comment]
Thanks for confirming. Based on these results, I believe this bug should be resolved as an external issue. ares requires accurate headers for unlicensed Famicom titles.

**Comment by BenjaminSiskoo** [comment]
thanks for your help :)

**Comment by LukeUsher** [comment]
Closing as not a bug, upstream rom needs fixing
