### ISSUE TITLE
N64 glitch since v133

### ISSUE THREAD

**Issue by Valmontechno** [higan-emu/ares#1525]
**Describe the bug**
When I run a n64 game with the 133 version or ulterior the video is glitched.

**Screenshots**
![image](https://github.com/ares-emulator/ares/assets/108832011/b910a512-4ca5-45bd-bdbf-bfb0bebc8cf1)
version 133

**Expected behavior**
![image](https://github.com/ares-emulator/ares/assets/108832011/aefa449b-097f-4ce7-be7c-0e8af25e985f)
version 132

**Additional context**
OS: Windows 10 22H2
RAM: 8 Go

**Comment by hackgrid** [comment]
You know that version 138 is current, yes?
Just update your graphic drivers, they must support Vulkan for N64.
This your local problem, not a issue of ares.

**Comment by remutro** [comment]
Newer versions of parallel-rdp require support for the Vulkan 1.1 spec. So as hackgrid already mentioned, you need to update your video drivers and they must support Vulkan 1.1.

**Comment by LukeUsher** [comment]
Perhaps we can do more to detect vulkan availability (and version) and show a warning dialog;

**Comment by kev4cards** [comment]
Glitches similar to this have been seen in ares prior to v133. The likely issue here is that the graphics card manufacturer's driver contains a shader compilation bug and would need to be worked around or fixed upstream from ares. Fortunately, if this is a shader compilation bug, an environment variable can be set to circumvent the problem at the cost of introducing compilation stutter. For Windows, that can be done by accessing the Control Panel and navigation to User Accounts under the User Accounts category. There you will find "Change my environment variables" on the left-hand side. Click that, create a new user variable with a variable name of `PARALLEL_RDP_FORCE_SYNC_SHADER` and set the variable value to `1`.
With that out of the way, this bug needs you to provide details on what CPU and GPU you have along with your graphics driver version if there is any chance of it getting fixed. This is one of those situations where only a few people have the skillset to squash that bug, and they need to be able to reproduce with similar hardware on top of that. So, please be patient if this does not resolve quickly.
