### ISSUE TITLE
[Mega Drive] Shadowrun - Graphics Glitch (Gamebreaking)

### ISSUE THREAD

**Issue by TwentySixHundred2600** [higan-emu/ares#1539]
**Describe the issue**
Vid-phone call via an in-game terminal displays corrupted options. Then when selecting one of the calls it will display a mess of coloured horizontal lines. 

**Rom Information**
ame
  sha256: 92a614491fc3ea12a6df32459cce08b48574b7b814e244c07eb860dc5c6edb7e
  name:   Shadow Run (U) [!]
  title:  Shadow Run (U) [!]
  label:  SHADOWRUN
  label:  SHADOWRUN
  serial: GM MK-1352 -00
  region: NTSC-U
  board
    memory
      type: ROM
      size: 0x200000
      content: Program
    memory
      type: RAM
      address: 0x200000
      size: 0x2000
      content: Save
      mode: lower
      enable: false

**Comment by TwentySixHundred2600** [comment]
So just for clarification the bug is present with an verified nointro ROM

game
  sha256: 92a614491fc3ea12a6df32459cce08b48574b7b814e244c07eb860dc5c6edb7e
  name:   Shadowrun (USA)
  title:  Shadowrun (USA)
  label:  SHADOWRUN
  label:  SHADOWRUN
  serial: GM MK-1352 -00
  region: NTSC-U
  board
    memory
      type: ROM
      size: 0x200000
      content: Program
    memory
      type: RAM
      address: 0x200000
      size: 0x2000
      content: Save
      mode: lower
      enable: false

**Comment by TwentySixHundred2600** [comment]
![Screenshot 2024-07-15 153951](https://github.com/user-attachments/assets/8cd76319-8a90-458f-af95-d956460bd71c)
![Screenshot 2024-07-15 154034dd](https://github.com/user-attachments/assets/0fc99548-8383-4673-be5d-9a670bcb8dd7)

**Comment by TascoDLX** [comment]
Known game bug, not an emulation issue. Refer to [https://gamefaqs.gamespot.com/boards/366854-shadowrun/59014988](https://gamefaqs.gamespot.com/boards/366854-shadowrun/59014988).

If you buy protection from a gang and don't have any contacts, the menu will be broken. You can easily reproduce this by using the ABBACAB cheat to get nuyen, go to the Halloweeners in Redmond and pay for protection, then go to a terminal and enter the Vid-Phone submenu.

**Comment by TwentySixHundred2600** [comment]
Oh wow, after all these years i had no idea about the bug and never triggered it. You are correct i paid for protection before having contacts (which is out of my norm of events). Thanks for the clarification and sorry for the false bug report. Im a happy man again, cheers
