### ISSUE TITLE
MegaDrive - NBA Jam TE

### ISSUE THREAD

**Issue by TwentySixHundred2600** [higan-emu/ares#1540]
**Describe the issue**
Fails to boot and displays vertical blue lines.

**Rom Information**
 sha256: 85ea84710a05b756d904706b2cee66fe778fafb6373f3760ed7959dd3e00865d
  name:   NBA Jam Tournament Edition (JUE) (REV 01) [!]
  title:  NBA Jam Tournament Edition (JUE) (REV 01) [!]
  label:  NBA JAM TOURNAMENT EDITION
  label:  NBA JAM TOURNAMENT EDITION
  serial: GM T-81406 -01
  region: NTSC-J, NTSC-U, PAL
  board
    memory
      type: ROM
      size: 0x300000
      content: Program

**Comment by LukeUsher** [comment]
This rom is known to be a bad dump; please verify your roms against no-intro or a similar modern rom database rather than what seems to be the massively outdated GoodTools.

**Comment by TwentySixHundred2600** [comment]
Thankyou for the heads up, been awhile since hunting roms so was unaware. I will make sure to get correct sets
