### ISSUE TITLE
Mega-CD RAM Initialization

### ISSUE THREAD

**Issue by TwentySixHundred2600** [higan-emu/ares#1544]
**Describe the bug**
When the game (Road Rash (verified no-intro)) is loading an option menu appears about low backup RAM. Please see attached screenshot below/

**To Reproduce**
ares_139 stable
game
  name:   Road Rash (USA)
  title:  Road Rash (USA)
  serial: GM T-50085
  region: NTSC-U

**Screenshots**
![Screenshot 2024-06-21 233904](https://github.com/ares-emulator/ares/assets/173236906/12aa960c-61c6-46c1-a4dd-0dda93530399)

**Comment by LukeUsher** [comment]
This is not a bug, but how real hardware functions if the memory is not formatted yet (first run or if the battery has died). You need to press A at the bios screen, enter the memory menu and format the backup memory so that the game can use it.

**Comment by TwentySixHundred2600** [comment]
Thankyou, sorry about the mistake
