### ISSUE TITLE
Macosx keyboard can't map??

### ISSUE THREAD

**Issue by Ulyssesm90** [higan-emu/ares#1548]
**Describe the bug**
For some strange reason, my MacBook Pro (m1, 2020) can't map any inputs using its own native keyboard. I run 13.5. Tried with my old 2017 MacBook Air just to make sure it wasn't me, and nope it's not. I CAN map the trackpad, like if I click assign, and then click with my mouse. Keyboard completely doesn't work, really strange. Using the current ares, but also tried with older versions and no luck.

**To Reproduce**
1. Go to settings
2. Click on input
3. As described above, can't set any inputs for any gamepad at all

**Expected behavior**
A keystroke should create an input and does on other computers/systems.

**Screenshots**
<img width="710" alt="Screenshot 2024-06-26 at 10 04 15 PM" src="https://github.com/ares-emulator/ares/assets/173973996/836458a9-d882-476c-b3e0-2205624bb0ca">
Just stays like this while mashing my keyboard

**Additional context**
I love ares!!!

**Comment by jcm93** [comment]
What is your input driver set to on the Drivers pane in settings?

**Comment by Ulyssesm90** [comment]
It's set to SDL, but call this a freaky occurrence but it's working now. Maybe I'm the one bugging out....

**Comment by remutro** [comment]
If it is working for you, maybe close out the issue? Did you have something else running that was interfering? Or was there anything else you did/closed/changed that would be helpful to others who may read this?
