### ISSUE TITLE
[NES] Ganbare Goemon 2 (Japan) - truncated window....

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#1571]
Ares : nightly release on 2024-06-21 10:58:52 UTC

![image](https://github.com/user-attachments/assets/fc5f4f51-7351-4909-94fa-efd93e28e605)

**Comment by PeterSamuels** [comment]
Check the overscan box in settings

**Comment by BenjaminSiskoo** [comment]
Thanks is it a normlal behaviour to check this option ?

**Comment by LukeUsher** [comment]
Not an issue' the game renders too close to the edge of the screen; it would likely be cut off on some CRTs too.
