### ISSUE TITLE
[PS1] Alundra 2 - A New Legend Begins (USA)

### ISSUE THREAD

**Issue by LilyBergonzat** [higan-emu/ares#1599]
(Just wanted to specify that I checked the md5 hash of my ROM and compared it to the one on Redump, and they match, so I assume I have a good one)

**Describe the issue**
- I open Ares
- I launch Alundra 2 on the Playstation emulator
- I skip the cinematics to go straight to the main menu
- I go to the options
- I move my cursor all the way down to the last option (I think it's SFX volume)
- I press X
The emulator closes there. I can see the animation of that part of the menu closing, but then the emulator closes, instead of going back to the main menu.

**Rom Information**
- **Filename:** Alundra 2 - A New Legend Begins (USA).bin
- **SHA256:** `4ea8c195deb77d223bd4f3faf41b077b183652ed7d768844af09d45a67a99a76`
- **MD5:** `250eba52e8878b2bb51bbce2af56742a`

**Manifest entry**
```
game
  name:   Alundra 2 - A New Legend Begins (USA)
  title:  Alundra 2 - A New Legend Begins (USA)
  region: NTSC-U
```

I was able to get an interesting-looking screenshot of my terminal with some debug traces enabled:
![image](https://github.com/user-attachments/assets/ec885523-3c8d-4ecf-86e6-4fb8484f80f6)

This is the part of the debug that was printed when I pressed X, the last step to reproduce the bug.

It kept printing roughly the same thing over and over again, and right before it closed:

![image](https://github.com/user-attachments/assets/40312f3f-9fcb-4976-95f9-f69c84a84eab)

**Comment by LukeUsher** [comment]
Appears to be fixed after [00a67f1](https://github.com/ares-emulator/ares/commit/00a67f167136a9027d13a244cf49cf2f3cdd7dd5)
