### ISSUE TITLE
[AUR] SNES games load, but don't actually run (black screen)

### ISSUE THREAD

**Issue by freq-mod** [higan-emu/ares#1615]
**Describe the bug**
Attempting to load any game (SMW, Kirby Dream Land 3, PAL DKC) results in a black screen. No audio, no video, running at 50/60 VPS. Pressing keys doesn't do anything. It likely happens only with SNES games, as PCE CD and N64 runs fine.

**To Reproduce**
1. Open ares
2. Try to load any SNES game. It can be .zip, .sfc. smc, doesn't matter. I tested only three of them.
3. Black screen

**Expected behavior**
SNES games should work, as they did on bsnes, higan and prior versions of ares.

**Screenshots**
![obraz](https://github.com/user-attachments/assets/71aa2e87-4972-4826-99d9-3838feefc021)

**Additional context**
Arch Linux x86_64, Intel UHD 620, ares bult from AUR.

**Comment by freq-mod** [comment]
More additional information, manifest:
game
  sha256:   b50bf9d95485e8aeb7a6730e9f9f9c9c4ec23a85b336a4fb2e3b63034531e36f
  name:     Kirby's Dream Land 3 (USA)
  title:    Kirby's Dream Land 3 (USA)
  label:    KIRBY'S DREAM LAND 3
  region:   NTSC
  revision: SNS-AFJE-0
  board:    SA1-RAM
    memory
      type: ROM
      size: 0x400000
      content: Program
    memory
      type: RAM
      size: 0x8000
      content: Save
    memory
      type: RAM
      size: 0x800
      content: Internal
      volatile

CPU WRAM:
![obraz](https://github.com/user-attachments/assets/0edfdda3-c4cd-4dab-824b-dd39864ac211)

**Comment by freq-mod** [comment]
Now I built it from the source myself, and it works as expected! It seems to be some weird problem with AUR build, up to maintainers if they are interesting in solving that problem.

**Comment by jcm93** [comment]
I suspect this is due to the package not finding the appropriate `Super Famicom.bml` database file. There are several `.bml` files required by ares to run certain cores, SFC among them. I would report that information to the AUR package maintainer so they can package those files appropriately.

ares should also probably error out when it doesn't find these files instead of the behavior here.

**Comment by Mastergatto** [comment]
That's odd. SNES games run without issues for me. 

Can you tell me how did you build the AUR build? Did you use some AUR helpers? After you have built the .zst package, can you locate `Super Famicom.bml` at `usr/share/ares/Database`?

**Comment by Mastergatto** [comment]
@freq-mod Pushed an update for AUR, it should be fixed now. Can you try it and tell me if it works for you?

**Comment by freq-mod** [comment]
I confirm it has been fixed. Thanks, sorry for taking so long to ping back

**Comment by erjoalgo** [comment]
I was having the same issue using the debian-trixe ares Version 126-3, installing from source resolved the black screen.
