### ISSUE TITLE
librashader: update to 0.5.0

### ISSUE THREAD

**Issue by bsdcode** [higan-emu/ares#1658]
librashader has released a release candidate for version 0.5.0:
https://github.com/SnowflakePowered/librashader/releases/tag/librashader-v0.5.0-rc.1

This bumps the ABI and is thus incompatible with applications targeting previous versions.

I have updated librashader and adopted the OpenGL runtime in my own branch:
https://github.com/bsdcode/ares/tree/librashader_0.5.0

Because I can only test the OpenGL runtime I haven't opened a PR directly. Feel free to take any of my commits from this branch as you see fit. Or if you create a feature branch for the update I can rebase my commits against this branch.

I'll probably update my commits when further release candidates or the final version 0.5.0 are released.

**Comment by jcm93** [comment]
I have a local branch for ABI2 with both Metal and OpenGL changes. Will take a look at it again later today and compare notes.

**Comment by jcm93** [comment]
I opened a PR on your branch with the Metal changes. As far as I can tell, the branch looks good to go after those are in (though we will probably want to wait for the actual 0.5.0 release to drop before merging anything into ares).

**Comment by bsdcode** [comment]
Thank you very much! I merged your Metal changes.
Yes agreed, we should wait for the final release before merging it into ares.

Do we know if the DirectX runtimes need an update to ABI 2 too?

**Comment by jcm93** [comment]
They do not; there's only d3d9 which doesn't implement librashader at the moment.

**Comment by LukeUsher** [comment]
Nice work guys, will work on upstreaming these changes soon!

**Comment by bsdcode** [comment]
Thanks!
