### ISSUE TITLE
Joystick doesn't work with 8BitDo Mod Kit for Original N64 Controller

### ISSUE THREAD

**Issue by gmariani** [higan-emu/ares#1683]
**Describe the bug**
I have an OEM N64 controller with the 8BitDo Mod Kit ( https://shop.8bitdo.com/products/8bitdo-mod-kit-for-original-n64-controller ). It connects via bluetooth fine, Ares is able to map the inputs fine, Windows sees the controller fine. But when I go to play, everything works except for the joystick. Even though I was able to map it as an input, it doesn't work once in-game. I tested with both the SDL and Windows drivers.

**To Reproduce**
1. Power on/connect an N64 controller with the 8BitDo Mod Kit
2. Map inputs to Ares, specifically the Nintendo 64 on Controller Port 1, set to Gamepad. Set the "Up", "Down", "Left", "Right" inputs to the different joystick positions.
3. Load an N64 game and test the inputs
4. Everything should work except the joystick.

**Expected behavior**
I expect the joystick to work as intended. It works in the Windows, see screenshot of Windows controller test. I was able to map inputs in Ares, just can't use it in-game.

**Screenshots**
![ares-mapped-inputs](https://github.com/user-attachments/assets/49cccef1-b7ae-4c90-a30e-aa267aa918d5)
![ares-driver-config-1](https://github.com/user-attachments/assets/e5e4bd54-28a4-4cd3-a90a-9b09168cf31f)
![ares-driver-config-2](https://github.com/user-attachments/assets/375110c7-f1fe-4108-9bcb-f11b790e5470)
![joystick-recognized-in-windows](https://github.com/user-attachments/assets/0c475555-b13e-4291-96b1-59b1ec33a0ad)

**Additional context**
Running Ares v140 on Windows 11 Pro 23H2 (22631.4317)
64GB of RAM
AMD Ryzen 9 5900X

**Comment by remutro** [comment]
You've mixed up the D-Pad (Up, Down, Left, Right) with your l-stick settings (L-Up, L-Down, L-Left, L-Right). You'll want to switch those around and it should work just fine (stick axis values should be associated with L-* entries).

**Comment by gmariani** [comment]
@remutro You're my hero, you were completely correct. I mapped the left D-Pad to the L-Up/Down/Left/Right because i thought "L" meant "Left". Thanks for clearing it up for me!
