### ISSUE TITLE
Impossible start playing some MSX games (input)

### ISSUE THREAD

**Issue by Erick-BR** [higan-emu/ares#1684]
**Describe the bug**
Some MSX games needs numbers to start (choose 1 or 2 players...) like Intellivision and ColecoVision, but there is no option to assign numbers to keyboard or controller.

**To Reproduce**
Game example: Beamrider

**Expected behavior**
MSX system should have the same key layout as the ColecoVision.

**Comment by LukeUsher** [comment]
The MSX has a full keyboard, whereas the ColecoVision does not, so this mapping does not apply there.

The MSX keyboard is fully supported, and is mapped to your computer keyboard, you just need to set a "Keyboard Capture" hotkey to toggle it on/off in the emulator settings under Settings -> Hotkeys.

**Comment by Erick-BR** [comment]
Thank you for reply. I'll try that.
