### ISSUE TITLE
Ares doesn't save controller bindings per system

### ISSUE THREAD

**Issue by VladimirVSC** [higan-emu/ares#1696]
When trying to bind some controller button in any system, it somehow binds to every similar button in other systems, In the result the control schemes are layering onto each other, becoming a mess.

**To Reproduce**
1. Open the "Settings/Input tab"
2. Bind some button in any system
3. Change system tab 
4. The similar button is bound here too.

**Expected behavior**
All the bindings done must be saved per system.

https://github.com/user-attachments/assets/a525c740-7682-4c77-8602-5c46f4eac837

**Screenshots**

**Additional context**

**Comment by LukeUsher** [comment]
This is how ares is supposed to work, as un-intuitive it may seem.

You configure your controller once in the Virtual Pad mapping, and then it maps each system automatically based on that virtual pad layout

The "system select" is *just* an alternative view for convenience, but not separate systems/mappings.

There is an open feature request for per-console controller profile #173 , but we're not there yet.
