### ISSUE TITLE
[GBA] The Legend of Zelda: The Minish Cap

### ISSUE THREAD

**Issue by jtrevor99** [higan-emu/ares#1705]
Copied over from the higan github.  This bug is confirmed in the latest builds of ares, higan, and byuu.

There's a room in the final dungeon ("Dark Hyrule Castle") that is notorious for causing softlocks. Google searches indicate multiple GBA emulators have trouble with this room. It does not appear to be due to corrupt ROM or any other such issue.

Savestate attached. To replicate the issue, move down one room then wait a second or so.  It appears newer versions of the original VBA do not crash here, but VBA-M and multiple other emulators do.

Additional info:
[https://retroachievements.org/viewtopic.php?t=1933](url)
[https://www.ngemu.com/threads/possible-spoilers-minish-cap-reset-bug-report-huge-bug.163977/](url)
[https://pyra-handheld.com/boards/threads/gpsp-zelda-minish-cap-freezing.46336/](url)
[https://gbatemp.net/threads/gbarunner2.451970/page-63#post-8472391](url)
[https://www.reddit.com/r/SBCGaming/comments/zx11cj/minish_cap_on_powkiddy_v90_freezes_at_this_point/](url)

[The.Legend.of.Zelda.-.The.Minish.Cap.zip](https://github.com/user-attachments/files/17929330/The.Legend.of.Zelda.-.The.Minish.Cap.zip)

**Comment by Screwtapello** [comment]
Just so there's a link back, the original issue was filed for higan as https://github.com/higan-emu/higan/issues/208

**Comment by remutro** [comment]
This is believed to be fixed as of commit: https://github.com/ares-emulator/ares/pull/1706

@jtrevor99 - could you confirm with the latest nightly build?   https://github.com/ares-emulator/ares/releases/tag/nightly

Please update with status and if fixed you can close after updating. If it still doesn't work then update with relevant info. Thanks!

**Comment by jtrevor99** [comment]
Thanks for the fast response! I am traveling for the holiday and won’t be able to test before Monday, but will let you know.

What was the root cause, out of curiosity? I know a little about system architecture and am curious.

**Comment by Kawa-oneechan** [comment]
> What was the root cause, out of curiosity? I know a little about system architecture and am curious.

From the linked commit I guess it hopefully was an inadequately-emulated open bus.

Which would mean _Minish Cap_ on GBA and _Speedy Gonzales_ on SNES have something in common, screwing the player over right in the last part of the game for such a reason. Fun!

**Comment by remutro** [comment]
The linked commit has to do with open bus and how some values are read in that condition. It's fairly well known now and was missing in ares but png183 was able to fix this and a number of other instances where open bus wasn't completely implemented. If you want to gory details, you can look at the changes in this commit: https://github.com/ares-emulator/ares/pull/1706

**Comment by jtrevor99** [comment]
I'm happy to report that that did it!  The issue is resolved as of the 2024-11-28 ares nightly commit.  Thank you.

**Comment by jtrevor99** [comment]
Marking closed due to successful resolution in latest commit.

**Comment by serbanosSs** [comment]
Now in 2026 with Ares 148 it is 100% playable and finishable ?

**Comment by jtrevor99** [comment]
Yep - after this update was made, I was able to 100% the game.
