### ISSUE TITLE
[N64] The Legend of Zelda: Majora's Mask

### ISSUE THREAD

**Issue by TheNotSoPro** [higan-emu/ares#1724]
There is a constant flickering of Link's tunic. The brown sword strap across his chest is constantly flickering partially on and off, causing green on/off flashes across brown strap. I have a 4070 so my computer is powerful enough to run it. Same issue on Simple 64, didn't have it on M64PN on RA but overall performance wasn't as smooth so I'd prefer to use Ares. 

```
file: Legend of Zelda, The - Majora's Mask (USA).z64
sha256:  efb1365b3ae362604514c0f9a1a2d11f5dc8688ba5be660a37debf5e3be43f2b

**Comment by omega-tuna** [comment]
The flickering happens on a real n64. ares is as close to the real hardware as you're going to get so it's also going to look a bit slower too. HLE emulators are always going to look cleaner and faster so if you prefer that just use that instead.

**Comment by TheNotSoPro** [comment]
Ok I wasn't sure if that happened on real hardware or not, thank you!

**Comment by omega-tuna** [comment]
you're welcome! My bad for all the edits, i couldn't think of how to say it lmao
