### ISSUE TITLE
[NES] can't get the zapper to work after mapping to mouse

### ISSUE THREAD

**Issue by cricri-pingouin** [higan-emu/ares#1728]
**Describe the bug**
I tried to play Duck Hunt, mapped the zapper to the mouse (see steps below) and the mouse doesn't do anything.

**To Reproduce**
- Load Duck hunt
- Famicom -> Controller port 1 -> Zapper
- Settings -> Input
- Controller port 1, Zapper
- Double click X/Y/Trigger to assign, then right click to select a mouse mapping; assigned X to mouse X, Y to mouse Y, and Trigger to left mouse button.

**Expected behavior**
I was expecting to see some sort of cursor moving with the mouse and be able to click "Game A" to start a game, but it does nothing. 

**Screenshots**

**Additional context**

**Comment by remutro** [comment]
You are missing one additional step. In Settings > Hotkeys, there is an option called "Toggle Mouse Capture" and you will need to assign a button to it. Once you've done the steps above and you have started the game, you will need to press this hotkey. It switches between the app (ares) capturing all mouse input, or your desktop environment from capturing mouse input. To return mouse input to the desktop, just hit the hotkey again.

**Comment by cricri-pingouin** [comment]
> You are missing one additional step. In Settings > Hotkeys, there is an option called "Toggle Mouse Capture" and you will need to assign a button to it. Once you've done the steps above and you have started the game, you will need to press this hotkey. It switches between the app (ares) capturing all mouse input, or your desktop environment from capturing mouse input. To return mouse input to the desktop, just hit the hotkey again.

Thanks, that works! For some reason I needed to have Controller 1 = gamepad and controller 2 = zapper for it to work though, not sure if that's how the game is programmed.

**Comment by cricri-pingouin** [comment]
Working!

**Comment by cricri-pingouin** [comment]
> You are missing one additional step. In Settings > Hotkeys, there is an option called "Toggle Mouse Capture" and you will need to assign a button to it. Once you've done the steps above and you have started the game, you will need to press this hotkey. It switches between the app (ares) capturing all mouse input, or your desktop environment from capturing mouse input. To return mouse input to the desktop, just hit the hotkey again.

Thanks, that works! For some reason I needed to have Controller 1 = gamepad and controller 2 = zapper for it to work though, not sure if that's how the game is programmed.

**Comment by remutro** [comment]
Yes, it may depend on the game where it expects the zapper as you still need to be able to navigate menus and such (the NES zapper didn't have standard controller buttons/dpad in it. 

If you feel this is resolved, please feel free to close it. Thank you.

**Comment by cricri-pingouin** [comment]
Thanks again! Yes, wanted to close it but only just figured it out.
