### ISSUE TITLE
[32X] No PWM in Sonic Robo Blast 32X

### ISSUE THREAD

**Issue by dgrove727** [higan-emu/ares#1730]
**Describe the issue**
SRB32X v0.1 doesn't have any PWM sound. PWM is used for both regular sound effects, as well as drums. Neither are played in Ares.

On real hardware, the situation is mixed -- NTSC has sound completely working, while PAL doesn't have any PWM. So Ares actually correctly mimics PAL hardware here in a sense. But it'd really be nice to have it working for NTSC. And maybe this would benefit the development team of SRB32X in learning about why it doesn't currently work for PAL *hint* *hint* ;)

**Rom Information**
There's only one ROM --> http://ssntails.srb2.org/srb32x

If you still need a hash for whatever reason, I can supply that, but it'll have to wait. I'm doing all of this from a phone.

```
file: SRB32X_v0.1.32x
sha256: <hash>
```

**Comment by LukeUsher** [comment]
BiZkViT on Discord has discovered that it works if you edit the ROM to remove "C" from the supported devices region of the header at 0x190 (the C being present tells emulators that the game supports CD32X and activates Sega CD emulation in ares)

Has this been tested on real hardware with a Sega CD attached to make sure the issue does not occur there?

**Comment by LukeUsher** [comment]
Update: not a bug in ares but a real hardware issue with sega cd attached; this has now been mentioned on the official release page for the hack. Closing as invalid.

**Comment by SSNTails** [comment]
This is invalid. We determined that we forgot to remove a line of code changing the sfx driver if a Sega CD was detected.
