### ISSUE TITLE
Logging SH2 commands to terminal using the tracer can result in a segfault

### ISSUE THREAD

**Issue by remutro** [higan-emu/ares#1733]
**Describe the bug**
Vic reported that logging SH2 commands to terminal using the tracer can result in a segfault. I was also able to reproduce this behavior. We were both on WinX64 using the latest available nightly. Vic mentioned he tried as far back as v137 and the problem was still present. 

**To Reproduce**
1. Open 32X ROM (I used latest Doom Resurrection, assuming Vic was working on his game)
2. Open Tools > Tracer from the menu bar
3. Click the log to terminal option for the two SH instruction options
4. Wait for crash

**Expected behavior**
Instructions log to terminal correctly

**Screenshots**

**Additional context**
This may be specific to the SH2 recompiler. It didn't crash for me using the interpreter but it is very slow and logs a ton of info so maybe I wasn't patient enough.

**Comment by invertego** [comment]
Thanks for writing this bug up, and to Vic for the initial report. For whatever it's worth, tracing never worked properly with the recompilers for any system before #1301. That PR should've made it work with all systems, but I must have overlooked 32x in my testing or neglected to retest after making additional changes before committing. In any case, it should be good after #1734 goes in.
