### ISSUE TITLE
[32X] Sega 32X Compatibility List

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#180]
As the Mega Drive received some updates these days, I take a time to test every 32X official release. The rules are the same from the N64 Compatibility List. If the region isn't defined, it means the North American NTSC version.
Also, note that I'm not evaluating speed or framerate (and by extension, audio speed) as we know this core it's still pretty new and as everybody knows, there are some optimizations that still need to be done. 
I expect this may serve as a reference as I plan to update this list as the core receives more updates.

Updated until **ares 123 dev 67db434**

**No issues found** (apart of speed/framerate issues)**:**
---
* Blackthorne
* Cosmic Carnage (E)
* Darkside (E)
* Knuckles' Chaotix
* Kolibri
* Pitfall - The Mayan Adventure
* RBI Baseball '95
* Sangokushi IV (J)
* Star Trek Starfleet Acadeny
* T-Mek
* World Series Baseball '95

**Partially:**
---
* Brutal Unleashed: It may hang due to using cached interpreter (seems to work with full interpreter mode)
* Doom: missing some audio effects
* FIFA '96: Some graphical bugs
* Golf Magazine - 36 Great Holes: Hangs in character select screen in Fred's favorite if you press "right" some times. The names of the characters in character select screen and the shirt of the character in-game have corrupted graphics.
* Mortal Kombat II: small graphical glitches in fights
* Motocross Championship: audio noises when the racing start
* NFL Quarterback Club: audio broken
* Parasquad/Zaxxon's Motherbase 2000: 3D objects aren't shown
* Primal Rage: Missing some sounds FX
* Shadow Squadron/Stellar Assault: audio corrupted when using waveOut in my end.
* Space Harrier: Graphical erros in Sega's logo
* Spider-Man - Web of Fire: audio corrupted when using waveOut in my end.
* Tempo: Some audio effects seem to be in different volume than the expected. Introduction seems to be running at wrong speed too.
* Toughman Contest: Some sprites are corrupted ingame. Some audio effects seems to be in different volume than the expected
* Virtua Fighter: Audio corrupted
* Virtua Racing Deluxe: Graphical corrupted in Sega and Sega Sports logo
* WWF Wrestlemania: Missing sprites

**Mega CD 32X games not recognizing the 32X accessory** https://github.com/higan-emu/ares/issues/179
---
* Corpse Killer
* Night Trap
* Slam City with Scottie Pippen (all 4 discs)
* Supreme Warrior (Both discs)
* Surgical Strike (Brazil)

**Don't work** (hangs in black screen unless another behavior is described)**:**
---
* After Burner Complete
* BC Racers: Black screen after licenses
* ECCO the Dolphin CinePak Demo (Developer Cart): Black Screen after SEGA logo
* Fahrenheit CD 1 Key Disc: The key disc aren't working in 32X CD mode, but it's working in Sega CD mode
* Fahrenheit CD 2 CD 32X Disc
* Metal Head: Black screen after Sega's logo
* NBA Jam Tournament Edition: Loud noise in the main menu. The game crashes before gameplay start probably due to using cached interpreter rather than fully interpreter.
* Star Wars Arcade
* WWF Raw

**General**
---
* Some audio effects may corrupt if you change them one after another. Thus, the most recommended is to restart the emulator whenever you change the game, until this issue is properly solved.

**Comment by remutro** [comment]
If you are going to go this route again, then you should probably close issue: https://github.com/higan-emu/ares/issues/52 

Any yes, Kolibri & Fifa Soccer '96 broke after some recent mega drive changes. They worked ok until those changes were merged.

**Comment by Shideravan** [comment]
With https://github.com/higan-emu/ares/pull/205 we have a lot of improvements. Now FIFA 96 and Kolibri are playable again. I'll change in the list as soon as the commit is merged. Thanks @TascoDLX 

![image](https://user-images.githubusercontent.com/12163923/134817329-dceeeaf0-e12e-433f-a67b-bf29a1ea8230.png)
![image](https://user-images.githubusercontent.com/12163923/134817410-b0ed12c6-580d-4bfc-9763-48d2ebc0d270.png)

**Comment by Shideravan** [comment]
But FIFA '96 still has some visual bugs
![image](https://user-images.githubusercontent.com/12163923/134903195-c62e6795-3ebe-44d7-8e1e-49db9365deaf.png)

**Comment by remutro** [comment]
@Shideravan 

Can you check the following games for audio again? If you don't have audio, shutdown ares (as in kill the process) and then load up the game again and see if you have audio. The following games should have their audio working without issue, but after sometime the 32X core seems to get into a state where audio goes away and you have to restart ares. Not sure what isn't getting cleaned up or re-initialized properly. I haven't found a reproducible case other then "play some 32X games and eventually audio disappears after loading some".

Blackthorne
Brutal: Paws of Fury
T-Mek

Also curious what "small graphical glitches in fights" in Mortal Kombat II means, I haven't noticed any. Also could you elaborate a little more on audio issues for Spiderman (I haven't noticed any in this game) and Stellar Assault? 

Tip: If you want to play "Golf Magazine - 36 Great Holes" on the character select screen where it normally hangs, for the one required player if you just hit right once and hit start, it should go in-game. Anything else and yes it will lock up. 

Finally, I would argue Toughman Contest has more graphical issues then just small ones in the HUD:

![Toughman](https://user-images.githubusercontent.com/84990500/134964858-0f226273-bc34-4bed-b520-3210613299df.png)

Thanks!

**Comment by Shideravan** [comment]
> @Shideravan
> 
> Can you check the following games for audio again? If you don't have audio, shutdown ares (as in kill the process) and then load up the game again and see if you have audio. The following games should have their audio working without issue, but after sometime the 32X core seems to get into a state where audio goes away and you have to restart ares. Not sure what isn't getting cleaned up or re-initialized properly. I haven't found a reproducible case other then "play some 32X games and eventually audio disappears after loading some".
> 
> Blackthorne
> Brutal: Paws of Fury
> T-Mek
>
>Toughman Contest has more graphical issues then just small ones in the HUD

You're right. I updated them.

> Also curious what "small graphical glitches in fights" in Mortal Kombat II means, I haven't noticed any. 

This:
![image](https://user-images.githubusercontent.com/12163923/135009747-3a48ff3f-ec1e-4dfd-8d8b-ef8245282017.png)
![image](https://user-images.githubusercontent.com/12163923/135009760-9bb37b0e-2585-4372-8252-4efb81366f34.png)
(but only happens in few frames during the fight, you have to pay attention to spot them)

**Comment by remutro** [comment]
@Shideravan - Thanks. Looks like we are in sync with experiences, which is good. If perhaps you recognize a pattern as to when some games lose audio then please update. Cause I haven't nailed it down yet. And it seems there are a few games that are especially susceptible to losing audio, which could potentially be a clue.

**Comment by Shideravan** [comment]
>  Also could you elaborate a little more on audio issues for Spiderman (I haven't noticed any in this game) and Stellar Assault?

I could reproduce these issues here when using waveOut, but as isn't reproducible in WASAPI and the games doesn't run at 60FPS in my end anyway, But WASAPI isn't viable for me to use in any driver, as it's causing distorsions in audio time. Also, I'm unsure about what is causing these errors, if is something related with my end (eg.: speed, my own audio driver, etc). I need to do futher testing - and if you don't experiment these problems using waveOut, I'll remove them from partially for now.

Also, I updated the Golf Magazine to partially, as it can go ingame under certain circunstances.

**Comment by ExperimentT** [comment]
In Ares 124 as well as the latest dev build I've noticed Tempo's introduction is running far faster than it's supposed to than on hardware despite being running at 60FPS and being VSync'd/ASync'd correctly. Ingame it seems to be running at the correct speed.

**Comment by viciious** [comment]
Doom 32X Resurrection has no sound effects whatsoever. The game uses DMA on the slave CPU to do them, so I guess that must be the bit that needs to be looked into.

**Comment by rcaridade145** [comment]
> Doom 32X Resurrection has no sound effects whatsoever. The game uses DMA on the slave CPU to do them, so I guess that must be the bit that needs to be looked into.

Looking at SH2::DMAC shouldn't SR register be saved before and restored after? Or can't i find it ?

**Comment by LukeUsher** [comment]
Would you mind creating separate issues for the issues that still exist? That way I can link it up to the compatibility tracker

**Comment by BiZkViT96** [comment]
I'm not sure it makes sense right now. Every game that I've tried has a graphic bug at the top of the image.

Space Harrier (Japan, USA)
SHA1 f32a52a7082761982024e40291dbd962a835b231

Again, it doesn't matter what game you run.

ares nightly 2022-03-04

**Comment by LukeUsher** [comment]
Superseded by the compatibility section on the ares website
