### ISSUE TITLE
[Feature Request] CHD (or full Zip) support

### ISSUE THREAD

**Issue by ghost-wolves** [higan-emu/ares#185]
Some of the consoles can boot from zipped files. The CD-based ones can't (and I wish there was some clarification somewhere on what can boot from Zip and what can't). Would like to see CHD support as that's the best way to store these massive sets or even zip support is something.

**Comment by Shideravan** [comment]
Regarding CHD support, you may like to take a look at: https://github.com/higan-emu/ares/issues/31
TLDR: Was decided to wait for CHDv6 final specifications to be released by the MAME team and work on improving other emulation aspects in the meantime.

**Comment by LukeUsher** [comment]
Zip files don't support random access, and as such, they are usually unsuitable for CD-ROM based systems.

CHD requires several large dependencies (flac, etc) and ares tries to be small and self-contained; it's too much bloat for such a small benefit at this moment in time.

**Comment by sards3** [comment]
Decompressing the entire zipped CD image into RAM up front seems easy and there would be no issues with random access.

**Comment by Shideravan** [comment]
> Decompressing the entire zipped CD image into RAM up front seems easy and there would be no issues with random access.

However, it is not immediate. A .7z in medium compression with 600MB takes approx. one full minute on an average modern computer for extraction. And it will depend on having this free space on the internal HDD for caching purposes. If there is no space available for the unzipped files in the cache, the emulator will simply not be able to run the file. It is a treatment that would require us to implement, otherwise, it could cause false positives issues.
Maybe it's a better idea to "force" the user to use pre-decompressed image files until the team is ready to work in CHDv6 files, which has better compression and can be ready to use.

**Comment by sards3** [comment]
> However, it is not immediate. A .7z in medium compression with 600MB takes approx. one full minute on an average modern computer for extraction

My CPU is almost 10 years old and it decompresses .7z at 20MB/second (about 30 seconds for 600MB).  ZIP files are faster than that.

> And it will depend on having this free space on the internal HDD for caching purposes. If there is no space available for the unzipped files in the cache, the emulator will simply not be able to run the file. It is a treatment that would require us to implement, otherwise, it could cause false positives issues.

None of this is an issue if you decompress directly to RAM. You don't have to worry about disk caching.

> Maybe it's a better idea to "force" the user to use pre-decompressed image files until the team is ready to work in CHDv6 files, which has better compression and can be ready to use.

Maybe. But Ares can already decompress zipped ROMs; it seems like it would take little effort to enable it for CD images for those who want it.

**Comment by rasky** [comment]
Maybe a more modern compression format should be investigated. Zstd is now the best overall general compressor and decompression is blazingly fast.

**Comment by LukeUsher** [comment]
CHD is supported for cd-rom systems as of 75c0a5f36e455aa0147e1ce747d2b28cf698f52e

**Comment by RinMaru** [comment]
> CHD is supported for cd-rom systems as of [75c0a5f](https://github.com/ares-emulator/ares/commit/75c0a5f36e455aa0147e1ce747d2b28cf698f52e)

soesnt work sonic cd chdv5 gets to the sega logo and freezes
