### ISSUE TITLE
[system request] neo Geo CD and cdz

### ISSUE THREAD

**Issue by AbreuEfechou** [higan-emu/ares#187]
The system architecture seems to be very similar to neo Geo aes. As the development of the neo Geo improves would be nice to see the Cd counterpart added in ares.

**Comment by meowthed** [comment]
It'll be a great addition sure, but currently the AES haven't gotten some notable developments in recent weeks.

**Comment by AbreuEfechou** [comment]
Removing to avoid duplicate of https://github.com/ares-emulator/ares/issues/797
