### ISSUE TITLE
[Documentation] Explain how to build ares in the README

### ISSUE THREAD

**Issue by sikthehedgehog** [higan-emu/ares#192]
Because I'm on Linux and forgot again how to build it. It isn't just running `make` from the root directory of the project.

**Comment by sikthehedgehog** [comment]
I think I figured it out for the emulator proper:
```
cd desktop-ui
make
```
The emulator binary is saved as `desktop-ui/out/ares`. Note that I don't remember what libraries need to be installed to make it work. You may need to add `cores=` and the list of cores to avoid building everything (in particular, I had to use `make cores=md` because it turns out that it crashed as soon as it tried to run otherwise… but that's a bug for another report).

I didn't try (`sudo`?) `make install` but it seems to be there in the makefile.

Still would be nice to have it in the README file.

**Comment by LukeUsher** [comment]
replaced by #521
