### ISSUE TITLE
[crash] Some core makes ares crash on Linux as soon as it runs

### ISSUE THREAD

**Issue by sikthehedgehog** [higan-emu/ares#193]
I initially built ares with just `make` and when I tried to run it it'd crash with `illegal instruction (core dumped)` as soon as it attempted to load. To make it clear, I mean the UI itself crashed, before even trying to load any game. I had to build ares using `make clean` then `make cores=md` (I only needed that core anyway) and now it runs properly.

In other words, support for some core (not Mega Drive) is causing it to crash on Linux. No idea which one.

PC specs:
* Ubuntu 18.04
* x86-64
* 4GB RAM

**Comment by bigbass1997** [comment]
Hmm my linux builds don't crash, even on the master branch. The build process changed semi-recently but my understanding is you first run `update-subtrees.sh` and then `make -C desktop-ui/` (or `cd` into the directory and run make as you did should be fine too). The script is there to grab a dependency for the n64 core, so not grabbing that might cause a crash? Not sure, haven't tested that.

Linux Mint 20.2 (Ubuntu Focal)

**Comment by Screwtapello** [comment]
`update-subtrees.sh` merges changes from upstream repositories into the current branch, which is not a thing you want to do on a regular basis, it's just there to remind people how to do it when needed.

**Comment by LukeUsher** [comment]
Any update on this?

**Comment by zoncabe** [comment]
hi there, i had the same issue here, running on lubuntu 20.04, now im building targeting for n64 to see what happpens

**Comment by rasky** [comment]
I debugged this with @zoncabe and it looks like the problem is that the n64 core forces `-msse4.2` in its `GNUMakefile`, and that's obviously wrong if the host CPU doesn't support it.
