### ISSUE TITLE
[Mega CD] Add back mode 1 support

### ISSUE THREAD

**Issue by sikthehedgehog** [higan-emu/ares#194]
Ares 119.4 actually had support for booting in mode 1. If the ROM header's device field ([ROM address $000190~$00019F](https://www.plutiedev.com/rom-header#devices)) included the letter "`C`" in it, it'd switch to Mega CD mode 1 emulation (and ask for a CD as well, but let's ignore that for a moment). It seems that the current version doesn't do this, nor have any other way to enable Mega CD mode 1 emulation.

It would be nice to have that back, or any other way to enable mode 1 boot.

Also while I was just checking I noticed that WORD-RAM didn't get mapped properly in mode 1, so that would need to be dealt with (oops), but first you'd need to restore the mode 1 functionality before being able to tackle that kind of problems.

**Comment by LukeUsher** [comment]
Mode-1 support was fixed in 741bfcd
