### ISSUE TITLE
[Audio] Sound is not working on Bluetooth headphones

### ISSUE THREAD

**Issue by essasetic** [higan-emu/ares#199]
I have the Sony WH1000XM3 and when I try to play audio through the emulator I'm only met with silence (even though it works fine in every other application).

I've tried it with the Mega Drive and the Famicom core (with Titan Overdrive 2 and HEOHdemo respectively). 

I've also tried setting the default audio device for the emulator to my headphones with no success (and I've also checked if I hadn't accidentally muted it).

**Comment by Screwtapello** [comment]
What audio driver are you using in ares? waveOut? XAudio2?

**Comment by essasetic** [comment]
WASAPI

**Comment by essasetic** [comment]
Switched to Linux, Pulseaudio works perfectly fine with my headphones. Not sure what was up with WASAPI though. 

Should I close it?
