### ISSUE TITLE
[MD] Titan Overdrive 1 graphical glitches

### ISSUE THREAD

**Issue by essasetic** [higan-emu/ares#212]
### Ares:
![Screenshot-20211001190409-1920x1160](https://user-images.githubusercontent.com/34970796/135667444-3edb0e12-8218-4af1-a95d-40933e936346.png)
![Screenshot-20211001190612-1920x1160](https://user-images.githubusercontent.com/34970796/135667443-8fb65921-d1d7-4005-9af7-e9af8dfdf745.png)
![Screenshot-20211001190645-1920x1160](https://user-images.githubusercontent.com/34970796/135667442-605da3fa-0786-4bab-91e0-16f58c727708.png)
![Screenshot-20211001190845-1920x1160](https://user-images.githubusercontent.com/34970796/135667439-c4dbac4c-f4b8-4d79-b0f2-c441ebf12e4b.png)

### Original hardware:

![Screenshot from 2021-10-01 19-12-26](https://user-images.githubusercontent.com/34970796/135667850-c2c6d46f-8b38-4cb6-8f49-6ec4437f108f.png)
![Screenshot from 2021-10-01 19-12-45](https://user-images.githubusercontent.com/34970796/135667852-79f048b3-57f9-4b22-ba49-6f65356f08eb.png)
![Screenshot from 2021-10-01 19-13-09](https://user-images.githubusercontent.com/34970796/135667856-cca0d34a-d343-463e-b09c-c4fc1f32ed8f.png)
![Screenshot from 2021-10-01 19-13-50](https://user-images.githubusercontent.com/34970796/135667858-6e4c4ae7-9081-425a-a4d1-82c29cbf29f9.png)

NOTE: I haven't tested the emulator specific versions on ares. Only the one meant for the original hardware as although the emulated versions will probably work perfectly. It isn't particularly useful for making the emulator more accurate.

**Comment by essasetic** [comment]
UPDATE:
Did a re-test on Ares v126. Unfortunately nothing got fixed however there are updates on two of the bugs I brought up.

![Titan Overdrive 1](https://user-images.githubusercontent.com/34970796/144718557-9f9d98b0-44a5-4884-b37c-c01f3f14e3c0.png)

The text on the left doesn't even render garbled mess anymore but at least more of the robot is render (I guess)?


![Titan Overdrive 2](https://user-images.githubusercontent.com/34970796/144718586-830eca1d-0c30-435c-8d55-ccd25ef0e1dc.png)

Instead of it being a blank blue background it does attempt to render the cityscape behind it now.


The re-testing was done on a completely different OS (Fedora 34 -> Windows 11) and a completely different setup (Intel laptop with iGPU -> PC with AMD GPU).

**Comment by BiZkViT96** [comment]
Update. These are all graphical bugs that I noticed.

The fancy backdrop is missing.
![2022-02-20 14_28_07-Titan - Overdrive (Rev1 1-106-Final) (Hardware)](https://user-images.githubusercontent.com/88586431/154833207-4ef99653-9b40-4b82-b4e3-a58b5fca819f.png)
A screen with a robot.
![2022-02-20 14_29_21-Titan - Overdrive (Rev1 1-106-Final) (Hardware)](https://user-images.githubusercontent.com/88586431/154833209-95dc3bc5-d48f-48e1-9f83-90a312e2266a.png)
The screen with the city.
![2022-02-20 14_29_39-Titan - Overdrive (Rev1 1-106-Final) (Hardware)](https://user-images.githubusercontent.com/88586431/154833210-0070c3b0-d461-46f4-bdb5-5f1c254ec27f.png)
When rotating "GFX" there is a graphical bug.
![2022-02-20 14_31_41-Titan - Overdrive (Rev1 1-106-Final) (Hardware)](https://user-images.githubusercontent.com/88586431/154833212-a44eb436-9b02-4e48-9b0b-368a53929cc9.png)
A well-known screen that rates your emulator.
![2022-02-20 14_32_22-Titan - Overdrive (Rev1 1-106-Final) (Hardware)](https://user-images.githubusercontent.com/88586431/154833213-47e37f1e-4143-4587-a9c5-36cd80462fcb.png)

I have no idea about the sound.

ares nightly 2022-02-18

**Comment by essasetic** [comment]
Update on the issue. This is on commit https://github.com/ares-emulator/ares/commit/c78d931e28972f2529dfe2961d3c9ff862f4abba

Fancy backdrop is completely fixed.
![Screenshot from 2022-03-01 14-15-16](https://user-images.githubusercontent.com/34970796/156186470-c9886500-58a7-4df6-afc7-c79242ad8e0a.png)

Robot scene is completely fixed.
![Screenshot from 2022-03-01 14-17-25](https://user-images.githubusercontent.com/34970796/156186616-84c17bd1-3c00-49a7-bac8-4b572cd6ace2.png)

City text scene is completely fixed.
![Screenshot from 2022-03-01 14-17-48](https://user-images.githubusercontent.com/34970796/156186717-a695fd24-d814-4037-8d91-a6c65a7eb3d1.png)

Screen that rates your emulator is still bugged.
![Screenshot from 2022-03-01 14-19-59](https://user-images.githubusercontent.com/34970796/156186809-bb1cd6ab-9d83-4514-8fa6-57bbaac90936.png)

Also the "GFX" text rotation is still slightly bugged (as seen on the above issue). But I wasn't able to get a screencap. Oddly doesn't apply to the other text in the scene?

**Comment by rasky** [comment]
I think everything has been fixed here after #421

**Comment by BiZkViT96** [comment]
Yeah, it looks like it. I didn't notice any graphical bugs.
