### ISSUE TITLE
[MD] B.O.B - Minor graphic flickering glitches in the game intro 

### ISSUE THREAD

**Issue by Yotamtamtam** [higan-emu/ares#214]
Minor graphic flickering glitche when the game shoes Electronic Arts logo.
See attatched video.

https://user-images.githubusercontent.com/87193210/135722442-7c9bc7d7-6c63-47ce-bddb-7d0ef1054159.mp4

Tested on Windows os. Ares v123 (Last nightly build - 10.20.2021).

**Comment by BiZkViT96** [comment]
The video doesn't help at all. Neither on the latest version nor on v123 do I see any artifacts on the EA screen. Can anyone confirm this?

**Comment by Shideravan** [comment]
I think that is about the small flash showing the full Electronics Art logo before the animation starts in the prototype version of B.O.B. (which seems to be the case of the video)
It's not an emulator error, it's a prototype bug fixed in the retail version. The issue can be closed.
