### ISSUE TITLE
[request] support for nintendo 64dd

### ISSUE THREAD

**Issue by AbreuEfechou** [higan-emu/ares#218]

**Comment by Shideravan** [comment]
There's already some 64DD implementation in the code, just don't know how much complete it is

**Comment by remutro** [comment]
> There's already some 64DD implementation in the code, just don't know how much complete it is

It's a skeleton structure meant as a placement holder as the intent was always to add support for 64DD. But so far there is no real implementation.

**Comment by LukeUsher** [comment]
64dd is now supported
