### ISSUE TITLE
[M-CD] A/X-101 (USA): The emulator crashes after select "start" in main menu

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#221]
The emulator crashes on choose the "start" option in main menu
![image](https://user-images.githubusercontent.com/12163923/135792576-926a79cb-a876-411f-b990-97c01c6342f1.png)

Using Windows 10 x64
ares 3ca1f9e
Sega CD BIOS: USA 2.0.0

**Comment by TascoDLX** [comment]
Try a different v2 BIOS (recommend the one from June '93). There a CD h/w revision that isn't emulated correctly due to the way seek ops work. The game seems to work fine otherwise.
