### ISSUE TITLE
[GBA] Rock'n Roll Racing: Completely corrupted graphics

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#223]
The graphics of this game is completely corrupted, making it unplayable

**Comment by LukeUsher** [comment]
Can you clarify which rom this is for? USA or Europe? Both?

**Comment by sczther** [comment]
Happens with both USA and Europe no-intro verified roms. The title screen looks like this screenshot, you can mash through to a completely red screen and lagging music.
![Rock 'N Roll Racing (USA) 2023-02-17 22-09-45](https://user-images.githubusercontent.com/17219314/219794152-0c22a028-11d8-49a6-a70c-963e1dfb9af1.png)

**Comment by LukeUsher** [comment]
![image](https://github.com/ares-emulator/ares/assets/740003/fdc826ad-2a20-4ac6-aaed-a162edd71bc2)
No longer an issue in currently nightly, unsure when solved.
