### ISSUE TITLE
[Feature Request] Rebindable Hotkey for "Capture Screenshot"

### ISSUE THREAD

**Issue by TheKins** [higan-emu/ares#233]
Self-explanatory. There doesn't seem to be a hotkey at all for screenshots at the moment, let alone a rebindable one. I love playing weird things and sharing what I find with friends, and part of the fun is taking quick snaps to shoot over to them on Discord or Twitter.

Any support would be greatly appreciated! Love the emulator so far, can't wait to see it grow further.

**Comment by Kawa-oneechan** [comment]
This was remarkably easy to figure out, even for me who can't compile this thing. I'm like... 90% certain what I have here right now should work.

**Comment by LukeUsher** [comment]
Fixed by #234
