### ISSUE TITLE
[MD] NBA Live 98: Graphical artifacts and crash

### ISSUE THREAD

**Issue by BiZkViT96** [higan-emu/ares#238]
Ares - The menus don't work properly and produce artifacts.
![2021-10-18 01_08_12-NBA Live 98 (U)  !](https://user-images.githubusercontent.com/88586431/137639886-c7b1c89a-d4f5-4f36-8a47-eb653b850bd1.png)
Ares - Artifacts.
![2021-10-18 01_30_35-NBA Live 98 (U)  !](https://user-images.githubusercontent.com/88586431/137640312-503e432f-ad55-411d-8900-8eb8d3bd7713.png)
Kega Fusion - All menus are highlighted correctly.
![2021-10-18 01_06_04-Fusion 3 64 - Genesis - NBA Live '98](https://user-images.githubusercontent.com/88586431/137639884-88a9b947-8c87-414a-9d43-bdaa82be8938.png)
Ares - Right before loading into, the game displays this for a split second
![ares_2021_10_18_01_12_40_117 mkv_snapshot_00 14_ 2021 10 18_01 14 41](https://user-images.githubusercontent.com/88586431/137639949-2a7f155b-90df-4122-ab4b-5b75e69cdaf3.png)
Kega Fusion - In the game
![2021-10-18 01_07_20-Fusion 3 64 - Genesis - NBA Live '98](https://user-images.githubusercontent.com/88586431/137639954-f6549c72-cc04-4c01-8b32-6bb51df18d5d.png)
BlastEm can't load into the game either, but there's another error. Maybe this will help.
![2021-10-18 01_04_50-NBA Live '98 - BlastEm - 59 8 fps](https://user-images.githubusercontent.com/88586431/137640166-906dd3dd-7a3a-48d4-a36a-6c8231947691.png)

NBA Live 98 (U) [!]
SHA1 89B98867C7393371A364DE58BA6955E0798FA10F

Tested on ares nightly 2021-10-17

**Comment by BiZkViT96** [comment]
With latest https://github.com/ares-emulator/ares/pull/257 before getting into the match, the game displays a black screen, the emulation speed drops and after a while the emulator freezes. But sometimes the game throws an error, and now it's different.
![2021-10-22 06_39_22-NBA Live 98 (U)  !](https://user-images.githubusercontent.com/88586431/138371768-9034338d-56c9-4e09-87a0-08058ea21cc0.png)

**Comment by rasky** [comment]
The menu artifacts were fixed by #362. Ingame was fixed by #357.

This issue can be closed.
