### ISSUE TITLE
[MD] NHL 98: Graphical artifacts

### ISSUE THREAD

**Issue by BiZkViT96** [higan-emu/ares#239]
Ares
![2021-10-18 01_35_50-NHL 98 (U)  c !](https://user-images.githubusercontent.com/88586431/137640695-e06b9848-9c2a-4f00-8fbc-ebeb07f415a5.png)
Kega Fusion
![2021-10-18 01_41_07-Fusion 3 64 - Genesis - NHL 98](https://user-images.githubusercontent.com/88586431/137640704-d7d8acb0-d8f0-472a-a391-8cccd379fab6.png)
Ares
![2021-10-18 01_36_21-NHL 98 (U)  c !](https://user-images.githubusercontent.com/88586431/137640709-cd4431f9-f17b-486a-aaa7-42f004c75684.png)
Kega Fusion
![2021-10-18 01_41_15-Fusion 3 64 - Genesis - NHL 98](https://user-images.githubusercontent.com/88586431/137640713-ec26acd8-cffa-425e-be44-b39d75bbd42e.png)

There's nothing to say, everything is on the screenshots.

NHL 98 (U) [c][!]
SHA1 6771E9B660BDE010CF28656CAFB70F69249A3591

Tested on ares nightly 2021-10-17

**Comment by rasky** [comment]
Fixed by #362. Can be closed.
