### ISSUE TITLE
[MD] Water Margin - Tales of Clouds & Winds (Unlicensed): Game freezes

### ISSUE THREAD

**Issue by BiZkViT96** [higan-emu/ares#241]
Ares - The game freezes after some time being in game, even in Demo mode without user input, music continues to play.
![2021-10-18 02_44_58-Water Margin - Tales of Clouds   Winds (U) (Unl)  c](https://user-images.githubusercontent.com/88586431/137642622-a239bf94-00d9-4e1c-bb24-0b385aed38ab.png)
BlastEm - run the game just fine
![2021-10-18 02_40_24-__#QNu -- -- - BlastEm - 59 9 fps](https://user-images.githubusercontent.com/88586431/137642649-8a3cc893-c800-4cc6-9cb0-c1a06e77ce6e.png)

Water Margin - Tales of Clouds & Winds (U) (Unl) [c]
SHA1 309E601697891FC90CFFE090E993330402B47457

Tested on ares nightly 2021-10-17

**Comment by Shideravan** [comment]
The game seems to be running fine in the most recent version 98aee19
![image](https://user-images.githubusercontent.com/12163923/138346662-d75ceb97-2dd4-42e5-9a10-d8b1ce6c1e23.png)

Probably was fixed with #257

**Comment by BiZkViT96** [comment]
@Shideravan Are you sure? My game still freezes. Judging by the score in your screenshot, you just started the game for 10 seconds. The game freezes not immediately but after some time.

It's my fault. I thought that "game freezes even in Demo mode" should indicate that the game does not freeze immediately when entering the game.

**Comment by Shideravan** [comment]
> @Shideravan Are you sure? My game still freezes. Judging by the score in your screenshot, you just started the game for 10 seconds. The game freezes not immediately but after some time.
> 
> It's my fault. I thought that "game freezes even in Demo mode" should indicate that the game does not freeze immediately when entering the game.

Alright, I can replicate. It's not fixed...

**Comment by BiZkViT96** [comment]
@Shideravan Updated the main post to reflect this.
