### ISSUE TITLE
[MD] Road Rash 3: Graphic flickering

### ISSUE THREAD

**Issue by BiZkViT96** [higan-emu/ares#243]
![2021-10-18 04_08_28-Road Rash 3 (UE)  !](https://user-images.githubusercontent.com/88586431/137645552-f138dbbf-e4a1-42f7-aee3-19e0421f93de.png)
In the race, the top line on the screen is constantly flickering.

Kega Fusion and BlastEm don't have such a problem.

Road Rash 3 (UE) [!]
SHA1 B2324833BF81223A9626A6060CAFC203DD203468

Tested on ares nightly 2021-10-17

**Comment by Shideravan** [comment]
The issues seems to be fixed as of version 98aee19
Probably fixed with #257

**Comment by BiZkViT96** [comment]
As far as I can tell, bug was really been fixed.
