### ISSUE TITLE
[MD] Toy Story: Graphic flickering

### ISSUE THREAD

**Issue by BiZkViT96** [higan-emu/ares#244]
The two lines at the top of the screen are constantly flickering on the racing stage.
![2021-10-18 04_51_51-Toy Story (U)  !](https://user-images.githubusercontent.com/88586431/137646568-90db193d-c86b-48b4-9f0a-cbf648896856.png)
The fastest way to get there is to use a save file in which I skipped two demo stages. Load the first slot.
Or use fast forward, the race stage will be the third in demo mode.
[Toy Story Save.zip](https://github.com/ares-emulator/ares/files/7360954/Toy.Story.Save.zip)

BlastEm and Kega Fusion are fine.

Toy Story (U) [!]
SHA1 49BE571CD943FD594949C318A0BDBE6263FDD512

Tested on ares nightly 2021-10-17

**Comment by Shideravan** [comment]
Replicable in the latest ares version
![image](https://user-images.githubusercontent.com/12163923/138348008-c74621e6-74d3-49fd-923b-8739f5fa5ff0.png)
Here a new version of the savestate just before the third demo start
[Toy Story (USA).zip](https://github.com/ares-emulator/ares/files/7392494/Toy.Story.USA.zip)

**Comment by BiZkViT96** [comment]
Update. The problem is still not solved, the flickering line now appears centered on the left.

![2022-02-20 14_18_17-Toy Story (USA)](https://user-images.githubusercontent.com/88586431/154832717-356e1acd-56c2-4615-b01b-bc15c9abecfd.png)

New save, first slot.
[Toy Story (USA).zip](https://github.com/ares-emulator/ares/files/8103570/Toy.Story.USA.zip)


ares nightly 2022-02-18

**Comment by BiZkViT96** [comment]
Bug is still there

ares nightly 2022-09-13

**Comment by BiZkViT96** [comment]
Fixed.
