### ISSUE TITLE
[MD] Arkagis Revolution (Unlicensed): Doesn't launch

### ISSUE THREAD

**Issue by BiZkViT96** [higan-emu/ares#248]
Ares - Black screen
![2021-10-19 18_00_56-Arkagis Revolution - Trial Version (Rev 00)](https://user-images.githubusercontent.com/88586431/137897280-47c90068-79fb-4be9-a475-5fef7aaf6d6d.png)
Kega
![2021-10-19 17_58_36-Fusion 3 64 - Genesis - ARKAGIS REVOLUTION](https://user-images.githubusercontent.com/88586431/137897333-6b7bf20c-ae3c-4c58-aad5-efceaa5dcc58.png)
BlastEm
![2021-10-19 18_01_40-ARKAGIS REVOLUTION - BlastEm - 59 9 fps](https://user-images.githubusercontent.com/88586431/137897352-e7b7343d-adbf-4a7f-b870-4ac326000fc8.png)

Kega and BlastEm run game with no problem.

Get trial rom from there website https://arkagis.com/revolution/

Arkagis Revolution - Trial Version (Rev 00)
SHA1 AD2E9E1DFC82F687B9BDB5B972A340990EA577F6

Tested on ares nightly 2021-10-17

**Comment by FitzRoyX** [comment]
Make sure you include the (Unlicensed) or (Proto) tags when a game is of that type. Sometimes that has a lot to do with why a game isn't working.

**Comment by BiZkViT96** [comment]
@FitzRoyX Like that?

**Comment by BiZkViT96** [comment]
Fixed with https://github.com/ares-emulator/ares/pull/257
