### ISSUE TITLE
[MD] Danny Sullivan's Indy Heat (Proto): Doesn't launch

### ISSUE THREAD

**Issue by BiZkViT96** [higan-emu/ares#249]
Ares - Black screen
![2021-10-19 20_14_10-Danny Sullivan's Indy Heat](https://user-images.githubusercontent.com/88586431/137917108-41890c06-8c71-43d9-aa2a-d7f4b623b569.png)
BlastEm - in game
![2021-10-19 20_13_16-Game title here - BlastEm - 59 3 fps](https://user-images.githubusercontent.com/88586431/137917215-f66e26de-ae58-4161-ba7b-1fcd744d2b77.png)
Look for Danny Sullivan's Indy Heat on https://hiddenpalace.org/Main_Page

Danny Sullivan's Indy Heat (USA) (Beta)
SHA1 6E76FF6A74374CD9170A902C250A1674EF69FD56

Tested on ares nightly 2021-10-19

**Comment by FitzRoyX** [comment]
Make sure you include the (Unlicensed) or (Proto) tags when a game is of that type. Sometimes that has a lot to do with why a game isn't working.

**Comment by BiZkViT96** [comment]
Fixed with https://github.com/ares-emulator/ares/pull/257
