### ISSUE TITLE
[MD] FX-Unit Yuki - The Henshin Engine (Unlicensed): black screen

### ISSUE THREAD

**Issue by BiZkViT96** [higan-emu/ares#252]
The game cannot play a lot of music tracks. Check the "Audition" option in the menu. Here's a little bit about compatibility - it may help to understand what is wrong here [https://www.retrorgb.com/fx-unit-yuki-port-released-for-the-genesis-mega-drive.html](url)

BlastEm has no problems with the game.

FX-Unit Yuki - The Henshin Engine (USA) (Unl)
SHA1 3ADCA8C5A4758E2A670EEBE93B80B5B0019E91ED

Tested on ares nightly 2021-10-19

**Comment by BiZkViT96** [comment]
After https://github.com/ares-emulator/ares/pull/257 the game doesn't load anymore. For a split second, the emulator displays this.
![ares_2021_10_22_06_52_57_934 mkv_snapshot_00 00_ 2021 10 22_06 53 37](https://user-images.githubusercontent.com/88586431/138372395-a7b70568-67e3-49d1-b1ce-f2c70956601a.png)

**Comment by TascoDLX** [comment]
ares never properly supported MD roms over 4MB, but coincidentally another issue was allowing this to boot by skipping part of the init. Proper support for >4MB roms will be coming soon.

**Comment by BiZkViT96** [comment]
Still no support for such roms. Ping @TascoDLX 

ares nightly 2022-09-13

**Comment by remutro** [comment]
This appears to be working as of latest nightly now (just prior to v130 release).
