### ISSUE TITLE
[MD] Lethal Wedding (Unlicensed): Sound bug

### ISSUE THREAD

**Issue by BiZkViT96** [higan-emu/ares#262]
Just white screen.

There is no voice on the Mega Cat logo screen on BlastEm. But everything works fine on Kega.

Demo rom https://megacatstudios.com/pages/lethal-wedding
Direct link https://cdn.shopify.com/s/files/1/1494/4102/files/LW_build_0446.zip?v=1592210201

LW_build_0446
SHA1 FE6533D013100DAA65D26E26BBAAE551422F57DF

Tested on ares nightly 2021-10-21

**Comment by BiZkViT96** [comment]
Update. The game itself loads and works fine. The only problem that I noticed is that there is no speech on the MegaCat screen, just like in BlastEm.

ares nightly 2022-02-18

**Comment by BiZkViT96** [comment]
Still no speech on MegaCat screen.

ares nightly 2022-09-13

**Comment by TascoDLX** [comment]
I'm not sure there's supposed to be speech here, at least not in this build. Is there any evidence of this working elsewhere? I know it's heard in the trailer, but that could have easily been dubbed in (or from a different build).

**Comment by BiZkViT96** [comment]
Game bug.
