### ISSUE TITLE
[Website] Issue tracker link leads to a 404 error.

### ISSUE THREAD

**Issue by ExperimentT** [higan-emu/ares#275]
The Ares website at ares.dev has an outdated link to the issue tracker (https://github.com/ares-emu/ares) which leads to a 404 error. It requires A slight edit to point in the right direction. https://github.com/ares-emulator/ares/issues

**Comment by cjalbert** [comment]
The ares team unfortunately does not have the information needed to access/update the ares.dev website (not from lack of trying either). That site will never be updated (or taken down for a while until it gets to the point of non-payment).

The new location for this site is located at: https://ares-emulator.github.io/  and the links there are correct and point to the right locations.

**Comment by ExperimentT** [comment]
Ah OK. Apologies, my mistake. I thought the dev site was still the official page.
