### ISSUE TITLE
[GBC] Donkey Kong Land 1, 2 and 3: Run the game in the GBC core makes the colors wrong (any pallette selection)

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#277]
The following example is using default pallete. But other palletes are wrong too. I'm unsure if this happens in other DMG games when using the GBC core, but probably yes

Ares:
![image](https://user-images.githubusercontent.com/12163923/140247919-3dfeade8-6c40-441f-b5a6-655eff1326a5.png)

Expected (using mGBA)
![image](https://user-images.githubusercontent.com/12163923/140248536-5f879c79-75b9-42a4-bf17-ba626878ba62.png)

**Comment by Shideravan** [comment]
The other DK Land titles has the same issues too
![image](https://user-images.githubusercontent.com/12163923/140254112-7e5e5e34-a46a-4acb-8f8c-fe9a94bacd50.png)
![image](https://user-images.githubusercontent.com/12163923/140254432-cf9b663c-c473-4e7b-a270-a73e929e2567.png)

**Comment by meowthed** [comment]
I assume it's because of the games being SGB enhanced that it does this?

**Comment by LukeUsher** [comment]
This seems to be caused by the fact that ares does not currently implement CGB running in DMG mode.

**Comment by LukeUsher** [comment]
Resolved by [b1d216b](https://github.com/ares-emulator/ares/commit/b1d216b8affbfb811a681dca1bd603d3369624fc)
