### ISSUE TITLE
[NES] Akira (iNES mapper 033): Hangs after main menu

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#281]
Even though we have proper mapper 033 support, this game doesn't get ingame, hanging after the following screen
![image](https://user-images.githubusercontent.com/12163923/141033988-01f231ba-796c-44af-9e67-9d073721cc95.png)

The same dump runs fine using Mesen
![image](https://user-images.githubusercontent.com/12163923/141034139-235a027f-9717-47a4-b8c3-4c98e6505df7.png)

**Comment by encoded-byte** [comment]
This was fixed in #336
