### ISSUE TITLE
(NES) Graphics in Honey Peach (Asia) (Ja) (Unl) are completely broken

### ISSUE THREAD

**Issue by ghost** [higan-emu/ares#282]
![honey peach](https://user-images.githubusercontent.com/92196998/141035658-068c76c1-b762-4cdb-a403-420b22d9b974.PNG)

![Capture2](https://user-images.githubusercontent.com/92196998/141035666-4ba89a21-d7b6-41db-b690-4832c67d110b.PNG)

**Comment by Shideravan** [comment]
The mapper 243 isn't supported yet
