### ISSUE TITLE
Nintendo 64 emulation on macOS

### ISSUE THREAD

**Issue by LukeUsher** [higan-emu/ares#284]
The Nintendo 64 emulation core relies on Parallel-RDP for rendering.

Parallel-RDP is a software implementation of the Nintendo 64 RDP rasterizer that is written with Vulkan and runs on the host GPU.

Vulkan is not available on macOS, and the current version of Parallel-RDP still doesn't run with MoldenVK.

In order to work on macOS, the Nintendo 64 core needs an RDP implementation that does not depend on Vulkan. 

All existing RDP cores (other than Parallel-RDP) are either GPL or MAME licensed: this makes them *incompatible* with ares' ISC license and unable to be used.

In the long-term, we may need to build our own RDP core from scratch in order to support macOS...

**Comment by remutro** [comment]
Can we use AngryLion-Plus then for the time being? Yes it is CPU intensive, but how much different would this actually be if someone were to write their own LLE RDP software implementation?

**Comment by LukeUsher** [comment]
> All existing RDP cores (other than Parallel-RDP) are either GPL or MAME licensed: this makes them incompatible with ares' ISC license and unable to be used.

AngryLion-Plus is licensed with the old MAME license, which adds some conditions that are incompatible with ISC:

> 
    * Redistributions may not be sold, nor may they be used in a commercial product or activity.
    * Redistributions that are modified from the original source must include the complete source code, including the source code for all components used by a binary built from the modified sources. However, as a special exception, the source code distributed need not include anything that is normally distributed (in either source or binary form) with the major components (compiler, kernel, and so on) of the operating system on which the executable runs, unless that component itself accompanies the executable.
    
If we were to include AngryLion, the ares releases would have to also be MAME licensed.

**Comment by LukeUsher** [comment]
It does seem that MAME's RDP implementation is BSD licensed, see: https://github.com/mamedev/mame/blob/94664102484edb96ac81f8613b096cb11cdeb6ab/src/mame/video/n64.cpp

This means that although we can't use angrylion or its derivatives, we could potentially port mame's RDP renderer to ares as a fallback when vulkan isn't available.

**Comment by remutro** [comment]
I know that's the default MAME license, but only because they haven't been able to get approval/feedback from some developers (AFAIK). According to their license page, over 90% is now licensed under the BSD-3 clause. So if the RDP renderer specifically calls out that license, then perhaps that would be one way forward.

Reference: https://docs.mamedev.org/license.html

**Comment by LukeUsher** [comment]
Closing this issue, as of #324 we can fallback to mame-RDP when Vulkan isn;t available
