### ISSUE TITLE
[N64] Goldeneye 007 has small graphical issues

### ISSUE THREAD

**Issue by RockyGateway** [higan-emu/ares#291]
I'm using Ares v125 and the only options I've changed are making N64 render in HD rather than SD. The same issue occurs on SD, though.
![Untitled](https://user-images.githubusercontent.com/7503745/141469852-b131842b-e9be-4b1a-a8f7-5bbdd73cf6d0.jpg)
So far this is the only part of the game I've encountered that has this issue, though I haven't played a huge amount.

**Comment by Screwtapello** [comment]
What OS are you using, what GPU, what video drivers?

**Comment by RockyGateway** [comment]
This is on Windows 10, 3070 Founder's Edition on driver 496.13

**Comment by sp1187** [comment]
I have the same issue on my system, which is an entirely different setup (Linux, AMD graphics card), so I suspect this may be an emulation bug.

**Comment by remutro** [comment]
This is only reproducible in the USA & Japanese versions of the ROM. This renders correctly using the European version of the ROM and does not have any visible artifacts. So perhaps this is an NTSC vs. PAL issue?

**Comment by loganmc10** [comment]
FWIW, m64p never had this issue, but I recently made a change to run the CPU/RSP somewhat in parallel (before it just ran the entire RSP task in one shot when it was submitted), and now this happens in m64p as well (though it's not as visible as this screenshot).

So I assume it's something to do with CPU/RSP/RDP synchronization, maybe interrupt timing? Perhaps an improvement that could be made to Parallel-RDP?

**Comment by osaeed18** [comment]
I also have this issue using Ares v129

Microsoft Windows 10 Pro
OS Version:  10.0.19044 Build 19044
Intel UHD Graphics 770
Driver version 30.0.101.1371 DCH

**Comment by LukeUsher** [comment]
Resolved in v133
