### ISSUE TITLE
[MSX] Some games needs keyboard support to start

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#293]
Even when using controllers to play, some games need a keyboard to choose options and while we don't support keyboard in ares yet, these games will hang in the main menu being unplayable.
Some examples of games that suffer from the lack of keyboard support (even don't use keyboard in the gameplay itself) include:
* H.E.R.O.
* Athletic Land
* Cosmo
* some others

**Comment by LukeUsher** [comment]
Keyboard is emulated now so this should no longer be an issue
