### ISSUE TITLE
[NGP] SNK Vs. Capcom - The Match of The Millennium: Doesn't properly trip the console warning screen

### ISSUE THREAD

**Issue by waspennator** [higan-emu/ares#296]
For whatever reason when playing this game with the regular Neo Geo Pocket core, it doesn't trip the "You can only play this on the Neo Geo Pocket Color" screen, which results in unplayable visuals, could be happening with other games as well.

Tested with the latest Nightly version 
![NGPC bug](https://user-images.githubusercontent.com/78768499/141659867-200fd5c2-d0f0-4077-b06a-09f219c9651c.png)

**Comment by invertego** [comment]
I am unable to reproduce this on the 2021-11-12 nightly build. I am seeing the expected error message from the game.

ROM SHA-256: 70d77cefb8a99350a53790d04c23ad874e2ef2bc92d2bd4211ea4407c08c0bdc

**Comment by waspennator** [comment]
Weird, guess I must have messed up setting it up somehow.

**Comment by LukeUsher** [comment]
Is there a chance it could be related to the fast boot setting?

**Comment by waspennator** [comment]
Tried turning on fast boot and all it really changed was making the menu and stuff more readable.
