### ISSUE TITLE
Can't assign buttons to mappings

### ISSUE THREAD

**Issue by viciious** [higan-emu/ares#298]
![image](https://user-images.githubusercontent.com/1173058/141674776-ee78920d-e3d4-420b-90de-6833be81f64c.png)

Pressing a key on the keyboard does nothing, unless I first minimize the main window and then restore it, or it goes out of focus.

For that matter, it also applies to loading ROMs: after loading the ROM, the emulator won't start executing it and just chill forever, until it does out of focus or minimized and then restored.

OS: Windows 10.
Ver: 125.1

**Comment by LukeUsher** [comment]
This is the same issue as #292 and has been resolved as of 12ac1b55341aac3e8eeb684b63aabbafe0a12db7
