### ISSUE TITLE
[Input] No keyboard or controller support ?

### ISSUE THREAD

**Issue by cocopickle** [higan-emu/ares#299]
Ok so i'm stuck on this screen => [https://a.tmp.ninja/geJPDtm.jpg](https://a.tmp.ninja/geJPDtm.jpg)
No input from the keyboard work, no input from my controller work. My controller is a Xbox 360 imitation, it works on other games !

Any idea ?

**Comment by LukeUsher** [comment]
Duplicate of #298, this issue has been solved in the latest development builds. 

Please search issues before creating a new one.
