### ISSUE TITLE
Make the paths in the configuration menu editable

### ISSUE THREAD

**Issue by meowthed** [higan-emu/ares#305]
Currently, the only thing you can edit with the paths is to assign them to a folder, or to reset it.

**Comment by jeffythedragonslayer** [comment]
You mean you want to be able to type a path into these four text boxes?

![image](https://user-images.githubusercontent.com/13253146/221442321-74f00d21-a5e2-493e-9d0f-7921d19b7e0f.png)

I agree, but what I like about the way it works now is that you can't accidentally type a nonexistent directory.  Perhaps we give some sort of immediate visual feedback if a nonexistent directory is typed in?

**Comment by remutro** [comment]
I would suggest we close this out as "won't fix". This is very clearly a minimalistic design that keeps users out of trouble. While it is straightforward to allow making the paths directly editable, my concern is that it is just going to create problems. There are literally two event handlers available currently - onActivate & onChange. Neither allow you to do things like format the path properly, or make sure there is a trailing directory separator (which is needed cause we append the system name/filename.ext). Of course other handlers could be defined (that's two implementations - one will handle all native but Qt is separate). I'm not even sure what event handler would work here to do final formatting. LostFocus? That would still require a user to know they need to click out of the path. We could add a specific save button, but it isn't needed for the other operations/buttons. It would just make this dialog more confusing. And ultimately, if someone REALLY wants to manually edit paths, feel free to edit the settings.bml file as much as you want. It just seems like way too much effort to enable when it isn't really needed in the first place, and it will likely result in users making mistakes and causing issues. This entire dialog window would need to be altered and I'm not sure I see any benefit here.

**Comment by Kawa-oneechan** [comment]
Very good point I'd say.
