### ISSUE TITLE
[NGPC] Unable to get correct colours.

### ISSUE THREAD

**Issue by TheKins** [higan-emu/ares#312]
The BIOS intro looks correct, but the actual game does not. I have tried multiple variants on the BIOS (No Intro, MAME...), to no success. Fast Boot makes no difference. Any ideas on where I've messed up?

BIOS:
![Bust-A-Move Pocket (USA) 2021-12-01 05-44-15](https://user-images.githubusercontent.com/2977232/144108603-338fe502-0b3c-4eb3-9ade-3fdd66d1eee1.png)

Bust A Move Pocket
![Bust-A-Move Pocket (USA) 2021-12-01 05-44-20](https://user-images.githubusercontent.com/2977232/144108634-c2c7c829-1dd1-4d81-b67d-66adcc38c3e9.png)

Neo Turf Masters
![Neo Turf Masters (World) (En,Ja) 2021-12-01 05-40-13](https://user-images.githubusercontent.com/2977232/144108653-c5a395a0-bd8b-4067-8a55-af737d5b0fdd.png)

**Comment by remutro** [comment]
I can't reproduce this issue. Using BIOS & Roms that match No-Intro and ares v126

![image](https://user-images.githubusercontent.com/84990500/144481610-e505dd21-d34b-40c6-b27a-29d1166613aa.png)

![image](https://user-images.githubusercontent.com/84990500/144481710-3240f171-c68e-4edf-b399-90ad8023caea.png)

**Comment by FitzRoyX** [comment]
Operating system? Version of ares you're using?

**Comment by TheKins** [comment]
Windows 10 Home 21H1
Ares v126
No-Intro BIOS and ROM set

**Comment by LukeUsher** [comment]
None of us can reproduce this I'm afraid; so I don't know where to go from here

**Comment by BiZkViT96** [comment]
I also can't reproduce it.
![2021-12-08 03_24_02-Bust-A-Move Pocket (USA)](https://user-images.githubusercontent.com/88586431/145101537-3d52a1d8-0d08-4635-92e3-218fefa2085c.png)
![2021-12-08 03_24_46-Neo Turf Masters (World) (En,Ja)](https://user-images.githubusercontent.com/88586431/145101542-b8203605-17d4-4134-b3bf-6733c1e78858.png)

Bust-A-Move Pocket (USA)
SHA1 5e8c84b9a4b10aa1c3abbfdea60aef90a8b7db7d

Neo Turf Masters (World) (En,Ja)
SHA1 d425bb812290b93a800032925d7be14f75820159

SNK Neo-Geo Pocket Color BIOS (1999)(SNK)(en-ja)
SHA1 edc13192054a59be49c6d55f83b70e2510968e86

Are all the settings in Ares for video and shaders set by default? Could it be a video driver?

Perhaps it makes sense to try another video driver in the settings, and change OpenGL to Direct3D.

**Comment by TheKins** [comment]
Shader is set to "None".
Colour Adjustment is set to what I think are the defaults: Luminance 100%, Saturation 100%, Gamma 100%.
Emulator Settings in the Video tab of options are all set to off.
Changing video driver from OpenGL to Direct3D or even GDI does not change the results.

It's kind of baffling and I'm not sure how I've wrangled this into happening. Non-Color emulation looks fine, too...

**Comment by BiZkViT96** [comment]
Does the SHA1 of the games themselves match with what I wrote in the post above? Perhaps it's worth trying to extract the game from the archive first, before launching? It might be worth trying another emulator, like [vdmgr](http://vdmgr.g2.xrea.com/download.html). Use the same BIOS and the same ROMs with games. If everything works fine in vdsmgr, I have no idea what the problem is.

**Comment by TheKins** [comment]
SHAs match, unzipping changes nothing, colors look fine in VDMGR and Bizhawk's implementation of NeoPop.

🤷‍♂️

**Comment by FitzRoyX** [comment]
Try wiping both the config file in your hidden user/appdata directory, as well as the "emulation" folder in your user directory. I'm wondering if the bios ram is corrupted somehow from being written with some super old version of ares and the new version is trying to inherit it.

**Comment by TheKins** [comment]
Emulation folder was largely empty, as far as I could tell. Wiping the BML file seems to have fixed it, thankfully. What a weird bug...

**Comment by LukeUsher** [comment]
Closing as the issue appears to be solved; if we ever see this again, we can re-open and investigate
