### ISSUE TITLE
Audio Output device "Default" missing in newer Windows releases (126, etc)

### ISSUE THREAD

**Issue by boktai1000** [higan-emu/ares#313]
I recently upgraded from release 120 which I had setup and working nearly flawlessly with workflow and setup to version 126.

I noticed in my release 120 setup, the option for the Output device is set to Default and is listed as an option in the dropdown menu (and is the default option)
![image](https://user-images.githubusercontent.com/9054563/144139781-9821e624-8580-4bfc-8f77-8b1e8c87a6bf.png)

With my setup for release 126, I only have the actual audio outputs listed and no option to set Default and let Windows handle this like with version 120
![image](https://user-images.githubusercontent.com/9054563/144139958-13e9e4d0-b9b0-4d60-a8ab-0de4855afe8e.png)

This is a pain as I'm frequently swapping between speakers and USB headset, and having a program with my Windows setup not change audio behavior when I flip that toggle in Windows is enough to keep me from wanting to update my release to this version. I don't exactly know if this is a regression or intentional, but having the Default option for audio not only took me a while to find (as it was under Drivers, not Audio) and figure out what was going on, but as far as my workflow goes for streaming and swapping between the two works against it.

Anyways, just wanted to relay this information - again not sure if a bug, regression, or intentional - but making sure parties here know, and throwing my hat in the ring if it is intentional to bring back the option for Default :)

Thanks! This was all tested in Windows 10 (21H1 x64 build - if it matters)

**Comment by Screwtapello** [comment]
In your screenshots, I notice the audio driver has also changed, from "waveOut" to "WASAPI". If you switch the driver back to "waveOut" and click the "Reload" button, does "Default" appear in the device list?

**Comment by boktai1000** [comment]
It looks like it does!

![image](https://user-images.githubusercontent.com/9054563/144264657-58b5a0aa-3b63-4245-876a-3d56db1e4ad5.png)

I will say though, I'm unsure why or how this got changed - I'm assuming this is a new default, and there's definitely no way I probably would have figured this out without asking about it

Do we know why this was behavior was changed, and why this new default driver doesn't have a Default option? Seems like a few things here that could probably be improved.

Glad that it's working with new version, still scratching my head on this though

**Comment by LukeUsher** [comment]
> I will say though, I'm unsure why or how this got changed - I'm assuming this is a new default, and there's definitely no way I probably would have figured this out without asking about it

The default driver was changed to WASAPI because testing showed that it had higher performance than the other drivers, for example in a performance test on my machine, it was the difference between maxing out at 109 fps (WASAPI) or maxing out at 76 FPS (waveout). This difference is significant enough that it may have caused some users to not get a solid 60fps where their hardware was otherwise capable.

> Do we know why this was behavior was changed, and why this new default driver doesn't have a Default option? Seems like a few things here that could probably be improved.

The lack of a default option with WASAPI is because WASAPI does not have a concept of a default device; the driver requires that the application specify an endpoint to use.

**Comment by LukeUsher** [comment]
On the basis that this is a configuration issue, rather than an emulator issue, I'm closing this issue.

This does highlight the need for a proper user guide, however.
