### ISSUE TITLE
[Feature Request] Portable Mode or CommandLine Integration

### ISSUE THREAD

**Issue by Nolar-Hack** [higan-emu/ares#322]
Hello,
i love your project thank you very much :)

My first request :
Is it possible for the windows version to make a portable mode ?
When i use Ares, a configuration file is created on my "appdata", that i would like is to get this configuration file on the folder where ares is put.
Behind this request i want to put a parameters by console and not by games.

My second request :
I don't know if the quetion has been made but is it possible to integrate a console mode on ares ?
If the first request is not possible i want to put the shader model or size directly by command

Like this for shader
.\ares.exe --shader crt-geom --file "rompath"

Like this for shader + size
.\ares.exe --shader crt-geom --size 3x --file "rompath"

Currently i use pegasus-fe for my frontend but i can't choose the good shader for each console i have to change it manually.

Or there are something i missing...

It would be perfect !!

Have a great day
Thanks.

**Comment by MartyShepard** [comment]
Hi. I'm currently working with Ares and looking at the emulator and have also created various bezels in combination with shaders for the integrated systems. I also missed such a command line. I compiled the current version with Msys2/MingW64 on Windows 10 and these are my "quick and dirty" changes.

This my changes to desktop-ui.cpp at line ~38

```
mia::setSaveLocation([]() -> string {
    return settings.paths.saves;
  });

  string gShader = "";

  for(auto argument : arguments) {
    if(argument == "--fullscreen") {
      program.startFullScreen = true;
    } else if(file::exists(argument)) {
      program.startGameLoad = argument;
    }

    // Lade shader via Commandline -------------- BEGIN
    if (arguments.take("--shader", gShader)) {}
    // Lade shader via Commandline -------------- END
  }


  inputManager.create();
  Emulator::construct();
  settings.load();

  // Lade shader via Commandline -------------- BEGIN
  if (gShader == "") {
  } else {
      string HoldOldShader      = settings.video.shader;

      settings.video.shader = { "Shaders/", gShader, ".shader/" };
      if (inode::exists(settings.video.shader)) {
      } else {
          MessageDialog()
              .setTitle("Error")
              .setAlignment(Alignment::Center)
              .setText({ "Shader not found: ", settings.video.shader , " - Using old: ", HoldOldShader })
              .error();
          settings.video.shader = HoldOldShader;
      }
  }
  // Lade shader via Commandline -------------- END

  Instances::presentation.construct();
  Instances::settingsWindow.construct();
  Instances::toolsWindow.construct();
```

Now it can load via ares.exe \<rom> --shader \<shader> (without .shader)

PS: I removed the "Home user" Reference and pointet to the programfolder to make my Version nativ "Portable". You have to change Path::userData() -> Path::program() and Modify to use a sub directory for Save Settings how .\savedata\.

**Comment by remutro** [comment]
FYI: appdata path has been updated so that Ares is truly portable as of version v131.

**Comment by remutro** [comment]
This issue can be closed. Shader options are available from the command line now and ares has been made truly portable.
