### ISSUE TITLE
The meaning of ares

### ISSUE THREAD

**Issue by CRTRevivalDreamer** [higan-emu/ares#323]
We all know this emulator was named after the main protagonist of **Lunar: The Silver Star**, one of Near's favorite JRPGs.

However...

I think ares stands for Advanced Retrogaming Emulation Suite.

**Comment by CRTRevivalDreamer** [comment]
Sorry for having opened this issue, but there are people that confuse ares (the Advanced Retrogaming Emulation Suite) with Ares Galaxy (a peer-to-peer file sharing program).

**Comment by Kawa-oneechan** [comment]
So?
