### ISSUE TITLE
[N64] Disabling Vulkan doesn't actually work if the GPU supports Vulkan

### ISSUE THREAD

**Issue by CasualPokePlayer** [higan-emu/ares#344]
If Vulkan is disabled via the option introduced in https://github.com/ares-emulator/ares/commit/980e9ed687093e94590ff4f0208525d13d3e3815, it won't actually disable Vulkan if the GPU does actually support Vulkan, due to the load attempt [here](https://github.com/ares-emulator/ares/blob/980e9ed687093e94590ff4f0208525d13d3e3815/ares/n64/system/system.cpp#L90) succeeding.

**Comment by LukeUsher** [comment]
Even though Vulkan does still get initialised, it won't be used for rendering; see https://github.com/ares-emulator/ares/blob/980e9ed687093e94590ff4f0208525d13d3e3815/ares/n64/rdp/render.cpp#L49

But otherwise you're right, we could clean this up a little

**Comment by CasualPokePlayer** [comment]
I don't think actually prevents rendering completely, [This code](https://github.com/ares-emulator/ares/blob/980e9ed687093e94590ff4f0208525d13d3e3815/ares/n64/vi/vi.cpp#L83-L105) normally should never be ran if Vulkan is disabled (no implementation always returns false, although implementation will exist if the init works). But it can be ran and it does output what would be expected of it if it was just rendering as normal? I don't understand why it does that but it does.

**Comment by LukeUsher** [comment]
should be resolved as of b03da384d847f743d7a99020956ac2e52b4c1b70, if you can confirm

**Comment by CasualPokePlayer** [comment]
That fixed it, thanks!
