### ISSUE TITLE
Vulkan Init Failed

### ISSUE THREAD

**Issue by MartyShepard** [higan-emu/ares#346]
Hello,

It show the message  
"Vulkan init failed, falling back to MAME RDP"

if i changed the Message to  
platform->status({ "Vulkan init failed, falling back to MAME RDP:.. ", implementation });

It show the message  
"Vulkan init failed, falling back to MAME RDP:.. 0x2449b710"  
But a Context is created?????

With Vulkan Disabled - "Vulkan Disabled: using MAME RDP:.. (nullptr)". This is normal

Latest Build, Windows 10/ X64 (Vulkan successfully testet with https://github.com/skeeto/vulkan-test)

**Comment by LukeUsher** [comment]
Thanks, for debugging purposes I reversed an if statement to make sure the message shows. 

I forgot to restore the correct behaviour before committing. 

Fixed in 58690cd5fc7bb6566c22935c5b80504a158cca29
