### ISSUE TITLE
[N64] Puyo Puyo Sun 64 (Japan) Crashes Emulator On Boot With MAME RDP

### ISSUE THREAD

**Issue by CasualPokePlayer** [higan-emu/ares#348]
Noting this game does not crash on MAME itself.

**Comment by CasualPokePlayer** [comment]
Some investigation seems to point to a small logic issue with component loading.
https://github.com/ares-emulator/ares/blob/e5220e8fd0cac360bb437c8b453907061d87f5e6/ares/n64/system/system.cpp#L85-L86
RDP is loaded before RSP is loaded. However,
https://github.com/ares-emulator/ares/blob/e5220e8fd0cac360bb437c8b453907061d87f5e6/ares/n64/rdp/rdp.cpp#L32
A pointer to RSP DMEM is given here on load, and where is it allocated
https://github.com/ares-emulator/ares/blob/e5220e8fd0cac360bb437c8b453907061d87f5e6/ares/n64/rsp/rsp.cpp#L19
Right here, on RSP load... after the pointer is given to MAME RDP (so MAME RDP just got a NULL pointer).

Switching the rdp and rsp loads around seems to fix the issue.

**Comment by LukeUsher** [comment]
Nice find, would you like to submit a pull request to fix this? We could do it ourselves but then you won't end up in the contributors list :P
