### ISSUE TITLE
[MegaDrive] Certain music for Phantasy Star IV sounds off

### ISSUE THREAD

**Issue by PatrikStar24** [higan-emu/ares#354]
Version : Ares v126
Options : Default
Game : Phantasy Star IV (USA)
System : Megadrive / Genesis

I'll get to the point. I'm only partway through the game (on this emulator, anyways), and there are a couple tracks that don't sound like they should. The 2 tracks I've spotted with anomalies so far are [the theme for Rune](https://youtu.be/LcwSd379SxM?list=PLmBphinVLUzQ9txIKQ78nFzCLcW_MTWfx), and [the song for the town of Tonoe](https://youtu.be/GPmB56F1asY?list=PLmBphinVLUzQ9txIKQ78nFzCLcW_MTWfx). 

I've attached recorded audio from the emulator for comparison, and I apologize ahead of time for the low volume of the recordings Edit: And I recorded it with my microphone since I don't have a proper set up on my laptop.
[Phantasy Star IV (buggy audio).zip](https://github.com/ares-emulator/ares/files/8056590/Phantasy.Star.IV.buggy.audio.zip)
.

**Comment by FitzRoyX** [comment]
Please recheck with latest action build

**Comment by PatrikStar24** [comment]
I've checked again with v130 (released today as of this writing), and the music for Phantasy Star IV is still not fixed (no change, good or bad). That said, there are other games (possibly related to this report) that saw improvements. 

Those being:
- Sub-Terrania (went from sounding very off in v126, to no sound past the menus in v129, to only sounding slightly off in v130)
- Dragon's Fury/Devil Crash MD (sustained or reverberated notes were off, now fixed)
- Zombies Ate My Neighbors (Main Theme sounded bad before, now fixed)
- Atomic Runner (see Devil Crash MD)
- Castlevania Bloodlines (see Devil Crash MD)
