### ISSUE TITLE
[N64] Implement Better VI Emulation (for MAME RDP)

### ISSUE THREAD

**Issue by CasualPokePlayer** [higan-emu/ares#355]
A bit related to https://github.com/ares-emulator/ares/issues/345. When using Vulkan, paraLLEl-RDP handles VI emulation itself, and ares doesn't have to do much there. However, the MAME RDP port instead uses whatever ares' had for VI emulation. Which is very lacking and has issues such as the one linked here, resolution being wrong, etc etc.

This probably isn't super hard, as paraLLEl-RDP itself seems to have very good VI emulation in the first place, so it can be used as a reference implementation, along with Angrylion's perhaps.

**Comment by LukeUsher** [comment]
We no longer ship the MAME RDP so this can be closed
