### ISSUE TITLE
[MEGADRIVE] Black screen with Back to the Future Part III (Europe)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#358]
Emulator : Ares 1.26
Options : Default
Game :  Back to the Future Part III (Europe)
System : Megadrive / Genesis

Black screen at the start

**Comment by FitzRoyX** [comment]
This is one of those PAL titles that will not boot at NTSC speeds. So you need to set region to Europe in the menu.

**Comment by BenjaminSiskoo** [comment]
Thanks you're right.
