### ISSUE TITLE
[MEGADRIVE] Sega logo broken with Bass Masters Classic - Pro Edition (USA)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#359]
Emulator : Ares 1.26
Options : Default
Game : Bass Masters Classic - Pro Edition (USA)
System : Megadrive / Genesis

Sega logo is borken at the start

![image](https://user-images.githubusercontent.com/12481242/154293230-f6e8889c-5f70-4d47-b663-95e13f6d2b20.png)

**Comment by rasky** [comment]
Fixed by #362, can be closed.

**Comment by BenjaminSiskoo** [comment]
Nice :)
