### ISSUE TITLE
[MEGADRIVE] Kind so crackles with the sound in Chuck Rock (Europe)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#369]
Emulator : Ares 1.26 Nightly build 2022-02-17 19:24:29 UTC
Options : Default
Game : Chuck Rock (Europe)
System : Megadrive / Genesis

The sound is weird in game.

**Comment by FitzRoyX** [comment]
Fixed by #669 about a month ago
