### ISSUE TITLE
[MEGADRIVE] Characters in background with Clue (USA)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#370]
Emulator : Ares 1.26 Nightly build 2022-02-17 19:24:29 UTC
Options : Default
Game : Clue (USA)
System : Megadrive / Genesis

Characters in background.

![image](https://user-images.githubusercontent.com/12481242/154711188-fcd1c3e8-67ae-46e4-ad13-7d44972b2579.png)

**Comment by FitzRoyX** [comment]
I can't reproduce this on nightly or v125. How old is your romset? Maybe the rom is bad.

**Comment by remutro** [comment]
I can't reproduce this issue either. Clue looks fine and no issues with sound on latest build of ares.

Rom is based on No-Intro dat.

**Comment by BenjaminSiskoo** [comment]
here the pic with infos
![image](https://user-images.githubusercontent.com/12481242/154749217-1b5eee4d-1f7e-4e38-9bcc-71c33e000210.png)

**Comment by BenjaminSiskoo** [comment]
I undersood what is the problem : 

If you drag and drop the archive, you have the bug. If you launch the game Clue (usa).md no problem.

I have seen the problem with a nes game too.

**Comment by FitzRoyX** [comment]
I see it now. It appears to happen randomly on its own, not due to anything you did.

**Comment by BenjaminSiskoo** [comment]
I tried 4-5 times, it's always there :)

**Comment by BenjaminSiskoo** [comment]
Fixed this day
