### ISSUE TITLE
[MEGADRIVE] Sonic The Hedgehog 3 (USA) (Sonic Classic Collection) Won't Boot

### ISSUE THREAD

**Issue by Yotamtamtam** [higan-emu/ares#372]
Emulator : Ares 1.26 Nightly build (18.02.22)
System : Megadrive / Genesis
Game : Sonic The Hedgehog 3 (USA) (Sonic Classic Collection)
Database: No-Intro: Genesis (v. 20210226-213851)
File/ROM SHA-1: 7CEB83DE0871962FA3CD8FDC0BA8B5DEC9A32CA9
File/ROM CRC32: FC0429DD

The game won't boot and will show a black screen.

**Comment by LukeUsher** [comment]
Not an emulation bug: the roms from Sonic Classic Collection only work on the emulator used for that collection contains some emulation inaccuracies that the games have been patched to work-around: as a result, these roms do not function on a real megadrive, or on any other emulator except the one used in the classics collection.
