### ISSUE TITLE
[MEGADRIVE] Freeze at the start with College Slam (USA)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#375]
Emulator : Ares 1.26 Nightly build 2022-02-18 15:07 UTC
Options : Default
Game : Clue (USA)
System : Megadrive / Genesis

Sega logo screen is borken. FPS are low

![image](https://user-images.githubusercontent.com/12481242/154779022-069c9c7c-99cd-499e-8d06-4da401dda343.png)

**Comment by FitzRoyX** [comment]
This is a regression, it works in v126

**Comment by BenjaminSiskoo** [comment]
Frank Thomas Big Hurt Baseball (USA, Europe) : same problem

**Comment by LukeUsher** [comment]
Should be fixed as of f67373732cc56544b4f74b606b5045d2d23001cb

**Comment by BenjaminSiskoo** [comment]
Fixed

**Comment by BenjaminSiskoo** [comment]
Frank Thomas Big Hurt Baseball fixed too
