### ISSUE TITLE
[MEGADRIVE] Collision problem with Devil Crash MD (Japan)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#379]
Emulator : Ares 1.26 Nightly build 2022-02-18 15:07 UTC
Options : Default
Game : Devil Crash MD (Japan)
System : Megadrive / Genesis

Very often, the ball pass through the flipper. Kind of collision problem.

**Comment by FitzRoyX** [comment]
This appears to be true. It feels like some kind of CPU calculation bug, but you'd think that would have wider impacts (unless the m68k had some rarely used instructions?). I also wonder if this is related to the Mario Lemeux hockey bug I found.

**Comment by rasky** [comment]
VDP has a sprite collision detection feature that is also subject to timing madness.

**Comment by BenjaminSiskoo** [comment]
Seems ok thanks :)
