### ISSUE TITLE
[MEGADRIVE] Stuck on the Elite screen with Elite (Unknown)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#381]
Emulator : Ares 1.26 Nightly build 2022-02-18 15:07 UTC
Options : Default
Game : 
- Elite (Unknown) (Tech Demo, Game)
- Elite (Unknown) (Tech Demo, Soaker)
- Elite (Unknown) (Tech Demo, Viewer)
System : Megadrive / Genesis

![image](https://user-images.githubusercontent.com/12481242/154801918-3573ce64-0291-4e37-8022-c6b16e957192.png)

**Comment by BenjaminSiskoo** [comment]
we can go further now with Ares 1.29 Nightly build 2022-08-24 23:08:51 UTC


![image](https://user-images.githubusercontent.com/12481242/186545078-8dcd1662-36fb-4ce3-b6e0-d9ef9a501dd6.png)

**Comment by TascoDLX** [comment]
There doesn't appear to be anything wrong with this in Ares. Can I get further explanation? Mind you, this is prototype, so while it may look slightly off in presentation, it seems to be functioning as intended.

**Comment by BenjaminSiskoo** [comment]
Seems good now : 

![image](https://user-images.githubusercontent.com/12481242/192234843-30cb448f-d9e0-4746-a76b-f122710243aa.png)
