### ISSUE TITLE
[MEGADRIVE] Crackles music with European Club Soccer (Europe) (Beta) (1991-10-25)

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#382]
Emulator : Ares 1.26 Nightly build 2022-02-18 15:07 UTC
Options : Default
Game : European Club Soccer (Europe) (Beta) (1991-10-25)
System : Megadrive / Genesis

**Comment by BiZkViT96** [comment]
Game works fine. Sound also good.

**Comment by BenjaminSiskoo** [comment]
Yup it's good
