### ISSUE TITLE
[MEGADRIVE] Black screen with Evander Holyfield's 'Real Deal' Boxing (World)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#383]
Emulator : Ares 1.26 Nightly build 2022-02-18 15:07 UTC
Options : Default
Game : Evander Holyfield's 'Real Deal' Boxing (World)
System : Megadrive / Genesis

**Comment by BiZkViT96** [comment]
Sequel Greatest Heavyweights also black screen. Everything used to work fine, this is regression.

**Comment by BenjaminSiskoo** [comment]
Fixed this day : 

![image](https://user-images.githubusercontent.com/12481242/154939621-1ee4fc2c-5d0b-4ce5-a0c2-0cc4958dee45.png)
