### ISSUE TITLE
[MEGADRIVE] Text size is not right with Exo Squad (Europe)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#384]
Emulator : Ares 1.26 Nightly build 2022-02-18 15:07 UTC
Options : Default
Game : Exo Squad (Europe)
System : Megadrive / Genesis

![image](https://user-images.githubusercontent.com/12481242/154802415-2e3e341b-b088-461f-ad22-16cb7795e1eb.png)

**Comment by BiZkViT96** [comment]
I'm not sure I know what to look at. The size of the emulator windows themselves is different. Naturally, the image in them will be of different scales.

**Comment by BenjaminSiskoo** [comment]
USA version is ok with the size. The problem is only with European version

**Comment by BiZkViT96** [comment]
I just checked it myself. The screenshots show a static title screen. I thought it was a scrolling screen. Ares really seems to have cropped the top and bottom of the screen.

**Comment by LukeUsher** [comment]
> USA version is ok with the size. The problem is only with European version

Did you make sure to run the Europe version with the Europe megadrive region? There are some slight resolution differences between PAL and NTSC systems

**Comment by BiZkViT96** [comment]
@LukeUsher I just tried everything. The picture is still cropped, and it seems to be only on one screen.

**Comment by FitzRoyX** [comment]
Ares defaults to only showing 224px height, but 240p is sometimes possible (all nes games, some pal snes, some pal mega drive). There is a checkbox to expand to 240 in the deep video settings called "overscan".

**Comment by BiZkViT96** [comment]
@FitzRoyX If I activate the Overscan option, the game displays the SEGA logo and right before displaying that cropped screen that we are looking at here, Ares crashes. After starting Ares again, the Overscan option appears disabled.

**Comment by FitzRoyX** [comment]
Cfg changes will only save if the emulator exits normally. So the real issue here is that the ares vdp crashes when it encounters 320x240 mode.

**Comment by BenjaminSiskoo** [comment]
Hi, I tried with tis build :@[github-actions](https://github.com/apps/github-actions) github-actions released this 2 hours ago
· 348 commits to 89287dabf144c49a4b0754ff8ba41cdb2218a6cd since this release
nightly
cb4a79e

It seems the problem is not fixed. Do I  need summit special ?

**Comment by TascoDLX** [comment]
You need to enable the Overscan option in Settings->Video in order to display the extended PAL regions. The crash issue mentioned above should be fixed.

**Comment by BenjaminSiskoo** [comment]
Thanks
