### ISSUE TITLE
[MEGADRIVE] Black screen with FX Unit Yuki - The Henshin Engine (World) (Aftermarket) (Unl)..

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#387]
Emulator : Ares 1.26 Nightly build 2022-02-18 15:07 UTC
Options : Default
Game : FX Unit Yuki - The Henshin Engine (World) (Aftermarket) (Unl)
System : Megadrive / Genesis

**Comment by BiZkViT96** [comment]
Duplicate of #252 and @TascoDLX knows about the problem.

**Comment by BenjaminSiskoo** [comment]
I close
