### ISSUE TITLE
[MEGADRIVE] Artefacts to the left bottom of the screen with Gouketsuji Ichizoku (Japan)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#389]
Emulator : Ares 1.26 Nightly build 2022-02-18 15:07 UTC
Options : Default
Game : Gouketsuji Ichizoku (Japan)
System : Megadrive / Genesis

Small red line 

![image](https://user-images.githubusercontent.com/12481242/154838250-46174b07-7578-4287-a662-3741281fb6f6.png)

Here a video wit a real megadrive

https://youtu.be/Nt0J3BDgG_k

**Comment by FitzRoyX** [comment]
It looks much worse in blastem. Are we sure the guy in the video is running at NTSC speeds? He sounds French.

**Comment by BenjaminSiskoo** [comment]
Yup it's french.

**Comment by Shideravan** [comment]
Are you sure it's not caused by overscan?
There's some flickering in the screen before it in the same position on the video (in ares we can see that with one pixel more, the place where the flickering in the screen happen is the same where this red line appears in the following screen)

**Comment by Shideravan** [comment]
The red line appears flickering in BlastEm too
![image](https://user-images.githubusercontent.com/12163923/192730456-b36c55fe-aea0-475b-b1a8-ce89a23af911.png)

**Comment by LukeUsher** [comment]
likely not a bug
