### ISSUE TITLE
[MASTER SYSTEM] Flickering with Addams Family, The (Europe)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#400]
Emulator : Ares 1.26 Nightly build2022-02-21 08:41:40 UTC
Options : Default
Game : Addams Family, The (Europe)
System : Master Sytem

![familleaddams](https://user-images.githubusercontent.com/12481242/154969607-cdce6fa3-dfee-4966-8f88-f08e1d8d4563.gif)

**Comment by LukeUsher** [comment]
@BenjaminSiskoo a potential issue could be that you're running an EU game at 60hz, try again with PAL mode; PAL and NTSC Sega Master System's do have important timing differences.

**Comment by BenjaminSiskoo** [comment]
yup, with eu it works properly. Is it possible to add a region auto detection ? I close this br

**Comment by LukeUsher** [comment]
> yup, with eu it works properly. Is it possible to add a region auto detection ? I close this be

Sega Master System games don't have headers, so it is not possible to accurately detect which region should be used; we will need to build a game database for this.

**Comment by BenjaminSiskoo** [comment]
Ok I understand, thanks :)
