### ISSUE TITLE
[MD] Implement custom mapper for Triple Play Gold

### ISSUE THREAD

**Issue by LukeUsher** [higan-emu/ares#407]
This game uses a non-standard PCB with an unusual memory layout.

Quoting EkeEke:

> See:
> https://datomatic.no-intro.org/index.php?page=show_record&s=32&n=1457
> https://datomatic.no-intro.org/index.php?page=show_record&s=32&n=1458
> 
> for the PCB layout of these two games (Triple Play Gold and Triple Play 96) and available ROM dumps.
> 
> As explained in above post, the games only have a 3MB ROM chip but it is mapped discontinuously in the CPU address space:
> 
> lower 2MB is mapped to 0x000000-0×1FFFFF
> upper 1MB is mapped to 0x300000-0x3FFFFF
> The games also embedd backup RAM which is mapped in between, in the usual 0x200000-0x2FFFFF region.
> 
> The result is that ROM dumps done from the cartridge port (with devices like Retrode or similar MD cartridge dumpers) are 4MB > files with SRAM data included (usually 0xFF when coming out from factory but can be anything depending on backup memory state when dumped). These ROM dumps are playable in emulators without specific care but will only allow backup saves if you enable > SRAM in the middle region as specified in ROM header.
> 
> The 3MB ROM dumps are coming straight from the Mask ROM and will need to be properly mapped by the emulator to be playable.
> 
> Both dumps are available in no-intro.
> 
> EDIT: To be fully accurate, the Mask ROM chip is actually a 4MB ROM chip (ROM chip with size not a power of 2 do not exist afaik) but the upper MB is empty (reads as 0xFF) and is not mapped in CPU address space.

**Comment by rcaridade145** [comment]
From the work of Mike Pavone of Blastem

https://www.retrodev.com/repos/blastem/file/tip/rom.db

**Comment by Shideravan** [comment]
![image](https://user-images.githubusercontent.com/12163923/192724048-13afe773-1f56-45cc-a92f-e03036472be5.png)
Working in the most recent version of ares

**Comment by LukeUsher** [comment]
Actually not sure this should be closed: have all varients of this rom been tested? both the 4MB and 3MB version? does SRAM function correctly with both?

**Comment by Shideravan** [comment]
Not working with 3MB variation
![image](https://user-images.githubusercontent.com/12163923/192880632-c3fba029-19ec-4405-9f9b-7ef6800ecf5e.png)

Access SRAM in some variations may freeze the game
![image](https://user-images.githubusercontent.com/12163923/192880868-a57c7624-e802-45c8-8532-439696947285.png)
