### ISSUE TITLE
md: Depends on 128-bit integers in ares/md/vdp/vdp.hpp

### ISSUE THREAD

**Issue by tobihan** [higan-emu/ares#409]
I packaged ares for Debian to replace the higan package: https://tracker.debian.org/pkg/ares
I had to disable the Sega Mega Drive core on 32 bit architectures because it uses 128 bit integers (u128) for two variables in ares/md/vdp/vdp.hpp. These are only available on 64 bit architectures. Would it be possible to modify this to make the core available on 32-bit architectures?

**Comment by jeffythedragonslayer** [comment]
Would https://github.com/calccrypto/uint128_t work?

**Comment by invertego** [comment]
This should be fully resolved by fc50ad03ae01072edf6fae45952243b9cf732d71 and b178d3d51a8b177cb10097b79ddda67905c2ebaa.
