### ISSUE TITLE
ppc64el: undefined reference to `swap_context' in libco/ppc64v2.c

### ISSUE THREAD

**Issue by tobihan** [higan-emu/ares#410]
Building ares on Debian ppc64el I get undefined references to swap_context:
        
        /usr/bin/ld: /tmp/cczPehVO.ltrans23.ltrans.o: in function `ares::Famicom::CPU::read(nall::Natural<16u>)':
        /<<PKGBUILDDIR>>/desktop-ui/../libco/ppc64v2.c:270: undefined reference to `swap_context'
        /usr/bin/ld: /<<PKGBUILDDIR>>/desktop-ui/../libco/ppc64v2.c:270: undefined reference to `swap_context'
        /usr/bin/ld: /tmp/cczPehVO.ltrans23.ltrans.o: in function `ares::Famicom::PPU::step(unsigned int)':
        /<<PKGBUILDDIR>>/desktop-ui/../libco/ppc64v2.c:270: undefined reference to `swap_context'
        /usr/bin/ld: /tmp/cczPehVO.ltrans23.ltrans.o: in function `ares::Famicom::CPU::write(nall::Natural<16u>, nall::Natural<8u>)':
        /<<PKGBUILDDIR>>/desktop-ui/../libco/ppc64v2.c:270: undefined reference to `swap_context'
        /usr/bin/ld: /tmp/cczPehVO.ltrans23.ltrans.o: in function `ares::Famicom::APU::main()':
        /<<PKGBUILDDIR>>/desktop-ui/../libco/ppc64v2.c:270: undefined reference to `swap_context'
        /usr/bin/ld: /tmp/cczPehVO.ltrans27.ltrans.o:/<<PKGBUILDDIR>>/desktop-ui/../libco/ppc64v2.c:270: more undefined references to `swap_context' follow
        collect2: error: ld returned 1 exit status

Full build log:
https://buildd.debian.org/status/fetch.php?pkg=ares&arch=ppc64el&ver=126-3&stamp=1645308306&raw=0

**Comment by LukeUsher** [comment]
Unfortunately, I don't have access to a powerpc64 machine to test this; is there a qemu configuration that would work for testing the build?

**Comment by LukeUsher** [comment]
This appears to be a result of the use of inline assembly in libco for the ppc64v2 backend.

If you check the other backends, you'll notice that rather than inline assembly, they use pre-assembled bytecode (with the original assembly as code comments)

We would need to do the same thing here.

**Comment by tobihan** [comment]
Not sure about qemu. Note that higan 106 with the same ppc64v2.c built successful on ppc64el 6 months ago:

https://buildd.debian.org/status/fetch.php?pkg=higan&arch=ppc64el&ver=106-2%2Bb1&stamp=1629099547&raw=0

**Comment by tobihan** [comment]
I can try later if higan still builds on todays Debian unstable ppc64el.

**Comment by tobihan** [comment]
The higan 106 Debian package still builds successfully on ppc64el Debian unstable (with gcc 11.2). Not sure what's different from ares there.

**Comment by LukeUsher** [comment]
I believe this may be due to the use of lto at compile-time, the compiler is incorrectly marking the swap function as unused and removing it from the binary.

removing the occurrences of `lto = true` from nall/GNUmakefile could fix it in the short term for v126.

**Comment by frediz** [comment]
Hi,
 I was looking into that failing build too and I confirmed disabling lto helps.
Thanks,
F.

**Comment by invertego** [comment]
ares should now compile cleanly for PPC64 even with lto enabled.
