### ISSUE TITLE
[N64] Diddy Kong Racing (NTSC-U region) V1.1 Regression- Corrupted Controller Pak

### ISSUE THREAD

**Issue by kev4cards** [higan-emu/ares#415]
Diddy Kong Racing v1.1 of the NTSC-U region can no longer reach the start screen. A caution screen (as shown below) states that the controller pak has been corrupted. This started happening with commit e98a313. That said, the dumped ROM for this particular region and version is listed on the No-Intro database but not verified. It is, however, considered good by the GoodTools/GoodSet designation. Therefore, there is a chance that the dump may be the cause of the problem and not the changes from the commit. Finally, v1.0 of the NTSC-U region works without any issue. Other regions were not tested.
![Diddy Kong Racing (U) (M2) (V1 1)  !  2022-02-26 18-43-08](https://user-images.githubusercontent.com/21962903/155862893-e5cfc89a-a714-42a6-9c99-609326e991e3.png)

**Comment by remutro** [comment]
Can confirm this is an issue and it only seems to do this with Rev 1 of Diddy Kong Racing - U

But in my experience, trying again allows it to continue into the game. Tracks cleared/times are stored in EEPROM, the controller pak is used to save ghost data from time trials. I had no issues saving ghost data, or racing against my ghost after saving. 

Also, this only occurs the very first time you play this game. If there is already a pak file it doesn't report corrupt data either.

**Comment by kev4cards** [comment]
Good to know other versions and regions appear unaffected.

I did not have any luck with trying again on fresh EEPROM and controller pak saves (i.e. no "progress data" actually written to these files) by unloading and reloading the game. The caution screen still persists. However, I can always continue past the screen by pressing start in both scenarios (on brand-new saves or saves without "progress data").

So, there are definite workarounds to the caution screen and should not affect anyone's play-through.

Lastly, the caution screen is most likely the result of an SI timing issue (Rasky's thought on Discord). The fix to the MULT/DIV timings probably changed the SI timing somewhat.

**Comment by kev4cards** [comment]
Fixed by commit fa017c2.
