### ISSUE TITLE
nall: path::desktop() does not obey XDG standards

### ISSUE THREAD

**Issue by LukeUsher** [higan-emu/ares#418]
Currently `path::desktop()` returns the output of `path::user() + '/Desktop'`.

This will work on Windows, Linux and macOS provided the default 'Desktop' path name is kept.

The XDG standard allows the Desktop path to be changed, so long as XDG_DESKTOP_DIR is set, so we should read this environment variable instead on POSIX systems.

Windows and macOS are safe to keep using the current implementation.

See: https://github.com/ares-emulator/ares/blob/3ca1f9ebb4ae3f472f7fba661746058f84126536/nall/path.hpp#L75

**Comment by Screwtapello** [comment]
Isn't there some fancy `SHGetKnownFolderPath` dance you're supposed to do on Windows to get the path to the Desktop folder (or other special folders)?

**Comment by Kawa-oneechan** [comment]
> Isn't there some fancy `SHGetKnownFolderPath` dance you're supposed to do on Windows to get the path to the Desktop folder (or other special folders)?

This is true: `SHGetKnownFolderPath(FOLDERID_Desktop, 0, NULL, &desktopPath);`

**Comment by LukeUsher** [comment]
ares already uses SHGetFolderPathW() for appdata, etc, so yes we could expand that to desktop also

**Comment by LukeUsher** [comment]
Fixed as of 35f6a937135e43bd13a9cbb2d6fa823daefe9b31
