### ISSUE TITLE
Request: Build Instructions

### ISSUE THREAD

**Issue by shinra-electric** [higan-emu/ares#422]
It took me quite a while to figure out how to build Ares. I think the project should post some build instructions somewhere. 

FWIW, here are the steps I took to build on Mac / macOS / M1 / Apple Silicon: 

Homebrew dependencies: `llvm` (There may be others, comment below if you came across some).

`git clone https://github.com/ares-emulator/ares`

`cd ares`

`make -C desktop-ui` 

After compiling, the app should be located in ares/desktop-ui/out/ and it needs to be signed. 

You can self-sign with `codesign --force --deep --sign - ` and then drop the app into terminal to get the path. (Note there is a space after the last `-`).

**Comment by Screwtapello** [comment]
According to the comment in the source, `macos-fix-jit` is a workaround for people building ares with versions of XCode before 11.4.1:

https://github.com/ares-emulator/ares/blob/d5dcc645e42156cd753084f5c1fa16f1d45d8e7d/desktop-ui/macos-fix-jit.cpp#L3-L15

If you build on macOS, the fixer tool is automatically built and applied to the ares binary, you don't need to apply it manually:

https://github.com/ares-emulator/ares/blob/d5dcc645e42156cd753084f5c1fa16f1d45d8e7d/desktop-ui/GNUmakefile#L77-L80

Also, ares should be buildable just by having XCode installed, you shouldn't need Homebrew or any Homebrew packages.

**Comment by shinra-electric** [comment]
Thanks for the info, I'll update the issue accordingly. 

Regarding homebrew, I had llvm removed as I was having issues with another project. I have Xcode 13.2.1 installed, but I was not able to compile ares. After re-installing llvm it worked, which is why I have it listed as a dependency. Maybe if you have llvm installed via homebrew you could try uninstalling and checking?

**Comment by rasky** [comment]
@shinra-electric 

We added a top level Makefile, so now `make` is enough to build Ares. Also we added a codesigning step for app bundle which should fix the issue running the bundle on Apple Silicon. As explained by Screwtapello, macos-fix-jit is used internally by the build system and should not be manually run by users trying to compile Ares.

So now, as long as you have a reasonable C++ compiler installed on your system, running `make` after checkout should be enough to build Ares. I would say the concern of this issue should now be solved.

**Comment by LukeUsher** [comment]
Closing this issue due to new top-level makefile;

**Comment by shinra-electric** [comment]
I can confirm the fix worked for me, and also that it compiled without llvm installed. 

Since the macOS-fix-jit shouldn't be applied manually, I've removed mention from my initial post. 

(I still think that there should be build instructions for all supported platforms somewhere, like on the readme.md of the project...)
