### ISSUE TITLE
[N64] Super Mario 64 - Weird shadow on Mario's shoe [ares-v127]

### ISSUE THREAD

**Issue by Max833** [higan-emu/ares#423]
Mario has a shadow on his shoe. That's not the case on original hardware.

The problem appears with MAME RDP **and** Vulkan.

![image](https://user-images.githubusercontent.com/53529402/156886126-ce3330ee-4965-44bf-9977-d5011d36f361.png)

**Comment by invertego** [comment]
This does occur on real hardware, though if the N64 is connected to your display with a standard composite cable you'll be less likely to notice. It's also less obvious in ares if you change the N64 render setting to SD Quality (which matches the original N64 resolution). Here is a video of the game being played on real hardware with an RGB mod (for improved signal quality) which shows the same issue: https://youtu.be/m_BlKt5-MMY?t=1368

**Comment by Max833** [comment]
You are right. Thank you!
