### ISSUE TITLE
[SNES] Yuuyu no Quiz de Go! Go! (Japan) - doesn't boot [ares-v127]

### ISSUE THREAD

**Issue by Max833** [higan-emu/ares#429]
Yuuyu no Quiz de Go! Go! (Japan) doesn't boot. 

Probably because of that: 

> This game stores an extra title byte, "YUYU NO QUIZ DE GO!GO!", the last ! is 0x21 in hex, which states HiROM mapping, even though it's a LoROM game. I special cased this game's title string so it detects as LoROM.

Source: https://archive.ph/ayiNL

**Comment by LukeUsher** [comment]
Fixed as of [93e8944](https://github.com/ares-emulator/ares/commit/93e89446e2d83f2084a20924f3cf4ac26fe78a03)

**Comment by Max833** [comment]
Thank you, @LukeUsher! :)
