### ISSUE TITLE
[SNES] From TV Animation Slam Dunk - Shuueisha Limited (Japan) - doesn't boot [ares-v127]

### ISSUE THREAD

**Issue by Max833** [higan-emu/ares#430]
From TV Animation Slam Dunk - Shuueisha Limited (Japan) doesn't boot.

Probably because of a board entry issue: https://archive.ph/RNsYF

**Comment by LukeUsher** [comment]
Fixed as of [93e8944](https://github.com/ares-emulator/ares/commit/93e89446e2d83f2084a20924f3cf4ac26fe78a03)
