### ISSUE TITLE
[N64] Mischief Makers Freezes After Pressing Start on Title Screen

### ISSUE THREAD

**Issue by CasualPokePlayer** [higan-emu/ares#432]
Reproduced on aresv127

**Comment by LukeUsher** [comment]
There are three versions of this game; can you please clarify which version this applies to?

Mischief Makers (USA)
Mischief Makers (USA) (Rev 1)
Mischief Makers (Europe)

**Comment by CasualPokePlayer** [comment]
Oh, didn't realize there were that many, I tested against Mischief Makers (USA), didn't test others.

**Comment by kev4cards** [comment]
This problem occurs with all regions and revisions, including Yuke Yuke!! Trouble Makers (Japan). The issue pops up sometime between the release of ares v123 and ares v124. I don't have any nightly builds from GitHub Actions for that window of time, so I can't point to one particular commit.

**Comment by kev4cards** [comment]
Additional information. This bug presents itself in CEN64. It does not in m64p (probably holds true for other variants of mupen64plus, as well). Therefore, the duration of 2304 cycles for the SI_DMA that was incorporated after v123 and used in m64p probably has no direct bearing on this issue.

**Comment by kev4cards** [comment]
I compiled some old versions today using MSYS2 with gcc. Turns out the SI_DMA duration (commit 0084865) is the offender after all.

**Comment by kev4cards** [comment]
Fixed by commit cb01795 . @CasualPokePlayer Please confirm.
