### ISSUE TITLE
[SNES] VOXEL database entry

### ISSUE THREAD

**Issue by Max833** [higan-emu/ares#436]
Source: https://github.com/bsnes-emu/bsnes/issues/123

> The leaked VOXEL rendering game demo doesn't work anymore on the latest version of BSNES (nor on the 2014 libretro core).
> There's only a single video of it apparently running correctly on BSNES v0.55

![image](https://user-images.githubusercontent.com/53529402/157318716-20055b88-0e94-40a6-a697-b85364fa937d.png)

jbo-85:

> What's happening here: (it's the same in ares and higan)
> 
> the game is 384KB, in commit https://github.com/bsnes-emu/bsnes/commit/a937f9b79b7756176842e7ac2489450a3d6408fc some refactoring took place, that basically masks every address in bus_read/write() by rom_mask/ram_mask, you can handle non power-of-2 sizes with "addr = Bus::mirror(addr, rom.size());"
> 
> after 106, icarus was basically rewritten, and some heuristics got changed, Voxel needs at least 64k expansion ram (previously 128k was used), that's hardcoded to 32k in SuperFamicom::expansionRamSize() for roms that don't set the extended header flags (i.e. Star Fox)
> 
> It's not really suprising that the heuristics don't really work for a prototype, adding an entry to the database would be sensible here

ROM: [VOXEL.zip](https://github.com/ares-emulator/ares/files/8209337/VOXEL.zip)

**Comment by jbo-85** [comment]
Should be fixed with https://github.com/ares-emulator/ares/pull/457

**Comment by Max833** [comment]
It's working great now. Thank you, jbo-85!
