### ISSUE TITLE
[SNES] Real hardware issues

### ISSUE THREAD

**Issue by Max833** [higan-emu/ares#437]
Every single game ever officially sold has been tested with bsnes (with firmware roms), and **zero bugs are currently known**. But there were some "hardware issues". These looked like bugs but were confirmed to occur on a real SNES. 

We should keep track with real hardware issues. 

Entries: **97**
Last update: **24.01.2022**

| Game | Description | Source | 
|     :---     |     :---     |     :---      |  
|      7th Saga      |      Bad graphic tiles at the bottom (right corner) when walking south      |      ZSNES forum      |
|      Aqutallion (J)      |      No visable battle damage, same on hardware.      |      ZSNES forum      |
|      Ace o Nerae!      |      Buggy game track: "Change Court", Bass guitar pops excessively      |      Blargg     |
|      Actraiser      |      Buggy game track: "North Wall", Click in echo at beginning      |      Blargg     |
|      Aero the Acro-Bat 2      |      Buggy game track: "Fort Redstar: Act 2, Title", Main instrument is slightly scratchy      |      Blargg     |
|      A Ressha de Ikou 3 Super Version      |      Buggy game track: "Bankrupcy", Glitch sound at beginning      |      Blargg     |
|      Albert Odyssey 2      |      Buggy game track: "Sorceress of Glacier", Bass sample has slight click (especially on left channel)      |      Blargg     |
|      Arcana (Cardmaster)      |      Buggy game track: "Journey, others", Clicks at beginning      |      Blargg     |
|      Barbarossa      |      Buggy game track: "Ending", Click at beginning      |      Blargg     |
|      Battletoads in Battlemaniacs      |      Level 4, part 2: The snake doesn't go through the hole. **Screenshot:** https://user-images.githubusercontent.com/53529402/131921348-d5abda88-5cda-4532-98c9-0f54be4119cd.png      |      ZSNES forum      |
|      Battle Blaze (beta only)      |      Black line flickering on "The Battle" after "Battle Start" just before beginning the fight      |      Github: http://archive.is/H41kY     |
|      Beavis and Butthead      |      Graphics are partially visible for one frame      |      Github: http://archive.is/xdcl3     |
|      Bishoujo Senshi Sailor Moon (Japan)      |      Intro: They were trying to recreate an effect seen in the anime, but did a very bad job of it. They are on a platform. The spotlight is being broken up by it that's because it is not round. The France release of Sailormoon is a port of this. **Screenshot:** https://user-images.githubusercontent.com/53529402/131502899-06f855e3-a3c1-4ad2-95da-57e6390f8a6a.jpg     |      ZSNES forum      |
|      Bishoujo Senshi Sailor Moon S - Kondo wa Puzzle de Oshioki yo! (Japan)     |      A single tile of garbage one 8x8 tile right from lower left corner      |      Github: http://archive.is/SOmwg     |
|      Bugs Bunny - Rabbit Rampage / Hachamecha Daibouken      |      Last line sometimes flickers when you jump      |      Github: http://archive.is/NEVWQ     |
|      Captain Novolin (USA)      |      Single white line while transitioning between doctor's advise and blood glucose screen      |      Github: http://archive.is/fjHTx     |
|      Captain Tsubasa J (J)      |      Parts of goal disappear when stuff comes in front       |      ZSNES forum      |
|      Captain Tsubasa IV (J)      |      "leftmost vertical line appears black/transparent" issue: ingame when bottom map shows up      |      ZSNES forum      |
|      Caravan Shooting Collection      |      Bad row of tiles on top of screen (probably emulating a NES-era limitation)      |      Github: http://archive.is/Ndnw0     |
|      Contra III: The Alien Wars      |      Blue line on left hand side of screen      |      Github: http://archive.is/owllF     |
|      Dirt Racer (Europe)      |      Sometimes crashes on startup due to a bad read from uninitialized WRAM      |      Github: https://archive.is/SFSID     |
|     Donkey Kong Country      |      Buggy game track: "Fear Factory", Click at 0:41 on right side and same place when song repeats      |      Blargg     |
|     Donkey Kong Country      |      Buggy game track: "Cave Dweller Concert", Click at 1:11 on right side     |      Blargg     |
|      Donkey Kong Country - Diddy Kong's Quest      |      Faces missing/loading late on barrels in Klobber Karnage      |      Github: http://archive.is/QoxXq     |
|      Donkey Kong Country 3 - Dixie Kong's Double Trouble      |      At the very beginning when kiddie and dixie are spinning the xylophone. Look at Kiddie's eye on the left, every few frames, part of it flashes an aqua color.      |      ZSNES forum      |
|      Doraemon 3 - Nobita to Toki no Hougyoku (J)      |      "leftmost vertical line appears black/transparent" issue: Intro      |      ZSNES forum      |
|     Earthworm Jim      |      Buggy game track: "What the Heck?", After a minute or so some bass notes seem to cut off early      |      Blargg     |
|      Exertainment Mountain Bike Rally      |      Blue dots on left hand side when selecting a track      |      Github: http://archive.is/f4kVA     |
|      Equinox/Solstice II      |      (4th dungeon) Character sprite is clipping into some layers.      |      Github: https://github.com/bsnes-emu/bsnes/issues/11      |
|      F-Zero      |      Buggy game track: "Mute City", Chorus comes into song about 2 seconds after beginning      |      Blargg     |
|      Gambling Hourouki (J)      |      Character portraits blink black during effect       |      ZSNES forum      |
|     Ganbare Goemon 2      |      Buggy game track: "Stage Clear", Weird sound at beginning, like bad sample data     |      Blargg     |
|      Gegege no Kitarou (J)      |      Possible mosaic issue on left side of the screen      |      ZSNES forum      |
|      Great Battle IV, The (J)      |      In gameplay, flickering garbage for a split second at top of screen      |      ZSNES forum      |
|      Heisei Inu Monogatari: Bow Pop'n Smash!!      |      Scanline flicker on top of screen when choosing Taisen mode      |      Github: https://archive.is/0rt8z     |
|      Heracles no Eikou III - Kamigami no Chinmoku      |      Black line on left hand side of title screen      |      Github: http://archive.is/gFM4i     |
|      Holy Umbrella - Dondera no Mubou!! (Holy Umbrella: Dondera´s Wild!!)      |      In short time, the village's people are all petrified by a villain. When you try talking to them, it tells you they're petrified. But then the bug occurs. The petrified npcs will start walking in place while still petrified. Their sprites will also often change to a random different npc sprite.      |      Github: https://github.com/devinacker/bsnes-plus/issues/316     |
|      Hurricanes      |      Attract sequence during level 12 renders an incorrect line of tiles due to uninitialized WRAM      |      Github: https://archive.is/85vit     |
|      Jissen Bass Fishing Hisshouhou in USA (J)      |      Line of water shows through boat       |      ZSNES forum      |
|      Kaizou Tyoujin Shubibinman Zero      |      Buggy game track: "Aquarium", Samples have slight clicks      |      Blargg     |
|      Kamen Rider SD (J)      |      Bikes flicker heavily when ontop of eachother      |      ZSNES forum      |
|      King of Rally (Japan)      |      Flickering in-game due to sending a table in WRAM to OAM in the middle of updating      |      Github: http://archive.is/GkbQ2     |
|      Las Vegas Dream in Golden Paradise (Japan)      |      Garbage line on top during Title Screen sequence      |      Github: http://archive.is/uSGcv     |
|      Lufia & the Fortress of Doom (USA)      |      Blue dots around text during the opening      |      Github: http://archive.is/keYYm     |
|      Magical Drop (Japan)      |      Soft-lock due to the SPC700 not initializing the DSP registers on startup (specifically, PITCH and ENVX)      |      byuu.net     |
|      Mega Man X3      |      Every time the enemy shoots the second spike thing, a black horizontal line appers which covers Mega Man partially. This glitch is always reproduciable. I also tested this with another enemy of the same type, and it worked too. It's easiest to see in Crush Crawfish's stage (the picture). I confirmed yesterday that this bug occurs on hardware. I used the European cart, but that doesn't probably matter. Screenshot: https://user-images.githubusercontent.com/53529402/131505438-4e806090-6ef9-42bf-8f2d-f2d8e809c524.jpg     |      ZSNES forum      |
|      Metal Marines      |      Buggy game track: "Engine Sound", Engine sound that changes pitch then ends      |      Blargg     |
|      Mickey Mania (Europe)      |       In the loading screen (Mickey keeps looking at the watch) there is a graphical bug in the left corner of the screen (it looks like a duplicate of his ear      |      ZSNES forum     |
|      Nakajima Satoru Kanshuu - Super F-1 Hero (Japan)      |      Has a flickering line during gameplay (pixel-based renderer) which actually happens on the real system.      |      ZSNES forum      |
|      Nichibutsu Arcade Classics (Japan)      |      Attract mode in Frisky Tom causes a hang due to reading uninitialized memory.      |      Github: http://archive.is/ji2ic     |
|      Pop'n Twinbee (Sample) (J)      |      Fails to load      |      ZSNES forum      |
|      Popeye - Ijiwaru Majo Seahug no Maki (J)      |      "leftmost vertical line appears black/transparent" issue: title screen      |      ZSNES forum      |
|      Pro Yakyuu Star (Japan)      |      Glitched tiles in center during attract mode.      |      Github: http://archive.is/x2qHG     |
|      Rendering Ranger R2      |      Sometimes crashes due to a deadlock between SNES and SPC700 **+** there is possiblity that when you enter the first level you have no sound     |      Github: http://archive.is/z7KI4     |
|      Romancing SaGa 3      |      Buggy game track: "Trade For Defeat", Echoing sound at beginning      |      Blargg     |
|      Sakurai Shouichi no Jankiryuu Mahjong Hisshouhou      |      Black lines for one frame before text box appears in "Point Nitsuite"      |      Github: http://archive.is/v4ayG     |
|      SD Gundam Gaiden - Knight Gundam Monogatari - Ooinaru Isan      |      Bad graphic tiles when walking left or right      |      Github: http://archive.is/GNvJY     |
|      Secret of Evermore      |       Broken dialog      |      Github: https://github.com/bsnes-emu/bsnes/issues/206#issuecomment-1020465371|
|      Secret of Evermore      |       Unable to finish the game       |      Github: https://github.com/bsnes-emu/bsnes/issues/206#issuecomment-1020473068|
|      Shin Ikkakusenkin      |      Sine wave playing during horse race      |      Github: http://archive.is/3iQ7f     |
|      Shin Megami Tensei      |      Audio popping      |      Github: https://archive.is/bPOoL     |
|      Shin Megami Tensei      |      Buggy game track: "Demo", Cuts off abruptly at 0:15      |      Blargg     |
|      Shin Megami Tensei      |      Buggy game track: "Dream, Ending, others", Lots of clicks when notes start      |      Blargg     |
|      Shin Nihon Pro Wrestling - Chou Senshi in Tokyo Dome - Fantastic Story      |      Slight rendering glitch of a few pixels in upper right corner during attract mode.      |      Github: http://archive.is/CVALy     |
|      Shodai Nekketsu Kouha Kunio      |      Buggy game track: "_most tracks_", Echoing click one second in      |      Blargg     |
|      Shounen Ninja Sasuke      |      Flickering line on left side of the screen when you press start      |      Github: http://archive.is/DYfMf     |
|      Super Bomberman 5 - Gold Cartridge      |      Screen glitch when you rename a custom bomber. Screenshot: https://user-images.githubusercontent.com/53529402/131500270-b4b2ec1a-074e-4382-866c-7bf3dc0a89f1.jpg      |      ZSNES forum      |
|      Super Bonk      |      Demo sometimes desyncs in front of the Jet-Roller Pipeline. Cause is CPU/APU-oscillator-specific.      |      byuu.net     |
|      SimCity      |      Bad tiles while scrolling      |      Github: http://archive.is/9U5bX     |
|      SimCity      |      Buggy game track: "Menu", First bass note sounds interrupted  |      Blargg     |
|      Super Chinese World 2 & 3      |      Black line on right when speaking to someone      |      Github: http://archive.is/R8i3Y     |
|      Super Double Dragon / Return of Double Dragon      |      Line of garbage at the beginning of the game in the elevator (or a few out-of-place blue pixels)      |      Github: http://archive.is/h9EWY     |
|      Super Famista      |      Flickering in upper left corner when pausing game while playing baseball      |      Github: http://archive.is/me0As     |
|      Super Famista 5      |      Flickering at top of screen during a baseball game      |      Github: http://archive.is/jBLmy     |
|      Super Fire Pro Wrestling X      |      Some parts of the body of your character can become invisible during Hyper Battle Royal mode.      |      Github: http://archive.is/Rom7D     |
|      Super Hockey '94 (Japan)      |      Black scanline at top of screen.      |      Github: http://archive.is/EsZAq     |
|      Super Inindou - Datou Nobunaga (Japan)      |      Black line on top of screen for about a second when you speak to someone      |      Github: http://archive.is/CnFy2     |
|      Super Mario World (Europe) (Rev 1)      |      Yoshi's House: Fire animation doesn't work      |      https://github.com/bsnes-emu/bsnes/issues/206#issuecomment-934627610
|      Super Professional Baseball      |      Bad tiles on left and right sides of the screen.      |      Github: http://archive.is/9Cl7B     |
|      Super Star Wars - Jedi no Fukushuu      |      Character's tiles (a sprite just below the Return of the Jedi logo, which is the only other set of sprites used) get corrupted after seventh attract mode demo      |      Github: http://archive.is/klHiT     |
|      Super Turrican      |      Buggy game track: "Level 4-2", Click-like sound on voice 5 mixed with bass line      |      Blargg     |
|      Super Turrican      |      Buggy game track: "_most tracks_", Some samples have slight clicks  |      Blargg     |
|      Takeda Nobuhiro no Super League Soccer (J)      |      Top horizontal line during gameplay looks odd      |      ZSNES forum      |
|      Tengai Makyo Zero      |      Buggy game track: "Let's Play!", Glitch tone at beginning      |      Blargg     |
|      The Lost Vikings 2      |      Crash during level 22 when using Baleog's cheat move with Y+down      |      Github: http://archive.is/TUT00     |
|      The King of Rally (J)      |      Missing/flickering textures at race beginning.      |      ZSNES forum      |
|      Thunderbirds - Kokusai Kyuujotai Juudou Seyo! (J)      |      Smoke effect as 1 launches looks wrong, looks the same on hardware.      |      ZSNES forum      |
|      Tiny Toon Adventures - Wild & Wacky Sports (E)      |      Feet missing 1 pixel line on character select screen, looks the same on hardware.      |      ZSNES forum      |
|      Tom and Jerry (J)      |      Far right of first level has messed up vertical line.      |      ZSNES forum      |
|      Top Gear                        |      There’s a weird tiny line of corrupted pixels near the speedometer for both player 1 and 2 (fast mode disabled)      |      Github: https://github.com/MiSTer-devel/SNES_MiSTer/issues/309
|      Top Gear 2 (Europe)      |      A black line appears in the bridge on level 1, happens on hardware too.      |      ZSNES forum      |
|      Top Management II (J)      |      When car comes in, it is under line.      |      ZSNES forum     |
|      Ultra Baseball Jitsumei Ban 3      |      Bottom of the screen sometimes turns blue when you hit the ball.      |      Github: http://archive.is/40vcQ     |
|      Ultimate Fighter      |      Flickering scanlines on bottom after pressing start to open the menu      |      Github: http://archive.is/rc7vL     |
|      Wild Snake/Super Snakey      |      Junk sprites in upper left corner via zeroing out coordinates.      |      Github: http://archive.is/rxB3d     |
|      Yuujin - Janjuu Gakuen 2 (J)      |      Sometimes the Characters will disappear or flash heavily, happens on hardware in the same places.      |      ZSNES forum      |
|      Zombies Ate My Neighbors (USA)      |      Line error on titlescreen, when the title is waving, 1 line wraps around to the other side of the screen      |      ZSNES forum      |

### _**Sources:**_
**Github (old bsnes github site):** https://archive.is/jd5qL
**ZSNES forum (bsnes_thread.zip)**: https://gitlab.com/higan/bsnes-history-kit/-/tree/master/sources/tukuyomi/misc
**Blargg's site**: https://www.slack.net/~ant/info/buggy-music.html
More infos about Blargg's issues: 
>Listed are music tracks that have been tested on hardware and verified to sound wrong or odd, either due to a bad rip or because they just sound that way. Refer to this if you're developing an emulator and find a music track that sounds wrong, before you look for a problem in your emulator. SPC tracks have been verified by loading them into the SPC-700 unit on a SNES using a custom development cartridge.

**Comment by LukeUsher** [comment]
Good idea; I have moved the content to the GitHub wiki here; https://github.com/ares-emulator/ares/wiki/Game-Bugs

We can keep this page up-to-date and link it with the Website in future.

**Comment by Max833** [comment]
Sounds good! :)

**Comment by Max833** [comment]
Updated list: https://github.com/bsnes-emu/bsnes/issues/206
