### ISSUE TITLE
[MEGA CD] 1.10 USA bios music issue

### ISSUE THREAD

**Issue by HeroponRikiBestest** [higan-emu/ares#445]
Emulator : Ares v127 Built 2022-03-09
Options : Default
BIOS : [BIOS] Sega CD (USA) (Rev B)
System : Mega CD / Sega CD

At the moment, the 1.10 usa bios has a delay before any music is played, and when music finally does start playing, it sounds extremely broken.

https://user-images.githubusercontent.com/50224630/157424220-c4db226f-af3a-42be-af33-70bb7ad43289.mp4

I apologize for the audio clipping due to me running below fullspeed, but even with that in mind, this is very audibly wrong when compared with the video below.

https://www.youtube.com/watch?v=tfsWDre2tIE

**Comment by ghost** [comment]
This seems to only happen when resetting the console, when loading a disc through through the "Load" menu it doesn't happen.

**Comment by HeroponRikiBestest** [comment]
In my experience, it does happen. The only difference is that you only get to experience a few seconds of the audio in the above video before the disc auto loads. I will retest with latest tomorrow in case this has changed since I made this issue.

**Comment by HeroponRikiBestest** [comment]
@Fluvian I confirmed that this still happens when booting the disc through the load menu, you just don't experience it as long since the game auto-boots. Here is a comparison between ares and kega fusion (which handles it correctly), using the same game (AX-101, USA version, although this has happened on all games I've tested) and the same bios file, with no input on my part.

https://user-images.githubusercontent.com/50224630/159146392-96ad01bd-b1fc-4fa8-bcc9-73ee996a653e.mp4

Please let me know if you experience different behavior.

**Comment by ghost** [comment]
@HeroponRikiBestest Might have happened because I tried an empty disc as that doesn't boot into anything.

**Comment by HeroponRikiBestest** [comment]
@Fluvian  I'm not quite sure what you mean by an empty disc, but if I try and load a cue file with no corresponding bin file, or a non-sega cd disc, or anything else I can think of, the same issue is present. Can you please record a video demonstration?
