### ISSUE TITLE
[32X] Golf Magazine 36 Great Holes Starring Fred Couples (JP - US): Visual issue resulting in crash

### ISSUE THREAD

**Issue by HeroponRikiBestest** [higan-emu/ares#446]
Emulator : Ares v127 Built 2022-03-09
Options : Default
Game : Golf Magazine 36 Great Holes Starring Fred Couples (JP - US)
System : Sega 32X

![image](https://user-images.githubusercontent.com/50224630/157425087-cfd18613-bcc7-41d2-9da0-0e7cb70c6c34.png)
Upon selecting your golfer before a hole, the text will be garbled, and the game will freeze if you don't select your character and hit start fast enough. This is a regression, although I don't remember which version this game worked with properly.

**Comment by remutro** [comment]
I'm fairly certain this isn't a regression. This issue has been on the list for almost a year. 

If you hit the right directional once and then start, you can go in game. I've never seen an ares release where the text wasn't mangled, or you wouldn't get in a hang situation if you hit right more then once.

**Comment by HeroponRikiBestest** [comment]
I swear I remember a release where it was fixed. Unfortunately, since the old github was removed and the discord logs were removed as well, I don't really have any proof of this.

**Comment by invertego** [comment]
This can be closed now.
