### ISSUE TITLE
[NES] Glitches with Jikuu Yuuden - Debias (J) and the translation

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#463]
Emulator : Ares 1.27 Nightly build2022-03-14 23:07:52 UTC
Options : Default
Game : Jikuu Yuuden - Debias (J)
System : NES

The link to the translation : https://www.romhacking.net/translations/1645/

Tested with Nestopia 1.51.1 and Nintendulator, no glitches.

When you talk with the NPC, you have some gltiches.

![image](https://user-images.githubusercontent.com/12481242/158619245-d2ee3c89-d58d-47c6-928b-b3e95a04fea9.png)

**Comment by FitzRoyX** [comment]
I can't reproduce this with either the original or modified rom.
![Jikuu Yuuden - Debias (Japan)fff 2022-03-17 11-50-19](https://user-images.githubusercontent.com/57089001/158852510-bd16b916-fd91-404a-9c49-78a5c1ee83f6.png)
![Jikuu Yuuden - Debias (Japan) 2022-03-17 11-51-18](https://user-images.githubusercontent.com/57089001/158852512-c9b3ca38-528d-4d69-8588-14843b7abed8.png)

Go to tools > manifest and post that info.

**Comment by BenjaminSiskoo** [comment]
I reload the direct3d 9 driver close the emulator, and it works after restarting, weird... Thanks for your answer
