### ISSUE TITLE
[PC ENGINE CD] Burai - Yatsudama no Yuushi Densetsu (Japan) - Hangs on the title screen

### ISSUE THREAD

**Issue by Yotamtamtam** [higan-emu/ares#475]
Emulator : Ares v126 Nightly Built 26-02-2022
Options : Default
Game : Burai - Yatsudama no Yuushi Densetsu (Japan)
Core : PC Engine CD
Bios: Version 3.00

Hangs on the title screen
(see attatched image)

![Burai_01](https://user-images.githubusercontent.com/87193210/159114829-1733e079-1571-4569-a336-181522237bc2.png)

**Comment by HeroponRikiBestest** [comment]
The game does not hang, that screen only displays if your ram is uninitialized. This issue should be closed.
![image](https://user-images.githubusercontent.com/50224630/160042093-92cd7207-221b-478e-b649-2f83856ab975.png)
