### ISSUE TITLE
[PC ENGINE CD] Burai II - Yami Koutei no Gyakushuu (Japan) - Only the first option will boot the game

### ISSUE THREAD

**Issue by Yotamtamtam** [higan-emu/ares#476]
Emulator : Ares v126 Nightly Built 26-02-2022
Options : Default
Game : Burai II - Yami Koutei no Gyakushuu (Japan)
Core : PC Engine CD
Bios: Version 3.00

Only the first option will boot the game

![Burai_02](https://user-images.githubusercontent.com/87193210/159115087-7b0c830e-f6f6-4bc4-856a-fd636658b177.png)

**Comment by LukeUsher** [comment]
the first option is “start the game”, the second option is “don’t start the game”

**Comment by LukeUsher** [comment]
For future reference, both Google translate and Apple translate can translate Japanese text from screenshots. 
![C28C918E-D419-4B77-BB6D-01D990E64DF4](https://user-images.githubusercontent.com/740003/159117043-9d2c6b98-88e7-4e7c-b51f-55d2c96c2a7c.jpeg)

**Comment by HeroponRikiBestest** [comment]
Shouldn't this issue be closed?

**Comment by Yotamtamtam** [comment]
Closed
