### ISSUE TITLE
[PC ENGINE CD] Dragon Slayer - The Legend of Heroes (USA) - The game hangs at the beginning of the first level

### ISSUE THREAD

**Issue by Yotamtamtam** [higan-emu/ares#493]
Emulator : Ares v126 Nightly Built 26-02-2022
Options : Default
Game : Dragon Slayer - The Legend of Heroes (USA)
Core : PC Engine CD
Bios: Version 3.00

The game hangs at the beginning of the first level
(see attatched image)

![Dragon_01](https://user-images.githubusercontent.com/87193210/159117283-ce201f35-a286-4a6a-9a34-c41f1e5487a3.png)

**Comment by HeroponRikiBestest** [comment]
The game is not frozen, ares just cuts off the voice clip almost immediately. If you continue waiting, the game will let you progress. This issue should be closed.
![image](https://user-images.githubusercontent.com/50224630/159831270-651659b1-d04b-4747-89a0-70eebbbe549b.png)
