### ISSUE TITLE
[Mega Drive(?)] Random full emulator crashes in early builds of Cave Story MD

### ISSUE THREAD

**Issue by LivelyZephyrs** [higan-emu/ares#520]
As the title says. While messing around in early ROMs of the Cave Story MD homebrew port
(Check out at https://github.com/andwn/cave-story-md ), there is a low(?) chance of Ares completely crashing.
![unknown](https://user-images.githubusercontent.com/14850864/162677526-71ac17a1-1143-4111-b94c-e307795ccbce.png)

This MAY be an issue specifically with these homebrew ROMs, or perhaps it's something more significant, I don't know.
I had Bluestacks running with 6GB of RAM allocated, as well as 10+ Chrome tabs, so it might also be an issue with insufficent RAM, leading to a crash.

**Comment by BiZkViT96** [comment]
I played v0.8.0 for about 15 minutes, no problems were found.

ares nightly 2022-09-13

**Comment by remutro** [comment]
This should have a homebrew/prototype label. 

If this problem is no longer occurring on the latest version of Ares then it should be closed.

**Comment by BiZkViT96** [comment]
I couldn't reproduce a crash, the game is working fine
![2023-03-26 16_41_40-cave-story-md 0 8 0](https://user-images.githubusercontent.com/88586431/227797328-0a342c28-0c1d-4484-96ba-83d11cdd795d.png)
