### ISSUE TITLE
[GENESIS/MD] first boss does not appear in cave story md 

### ISSUE THREAD

**Issue by FelipePlayzYT** [higan-emu/ares#523]
![Captura de tela de 2022-04-12 11-18-37](https://user-images.githubusercontent.com/54115676/162983648-f7eef934-cf18-431a-b150-8f1a7bfd0b10.png)
as the title says, balrog was supposted to appear, but in ares, he does not appear! hopefully this will get fixed on the next version (maybe) of ares

**Comment by remutro** [comment]
This should be re-tested. There have been multiple improvements to the Mega Drive core since this was originally filed. v131 is the current latest release.

**Comment by BiZkViT96** [comment]
Defeated the boss without any problems.
![2023-03-26_16_33_36-cave-story-md_0 8 0](https://user-images.githubusercontent.com/88586431/227797264-a11ac4b8-a2c9-432d-9fac-f9f979f96414.png)

Victory
![2023-03-26_16_35_00-cave-story-md_0 8 0](https://user-images.githubusercontent.com/88586431/227797275-517a9660-ae7a-42f0-854e-06239b5e0816.png)
