### ISSUE TITLE
[NES] Black screen with Nagagutsu wo Haita Neko - Sekai Isshuu 80 Nichi Daibouken (J)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#532]
Emulator : Ares 1.27
Nightly build 2022-04-23 15:12:57 UTC
Options : Default
Game : Nagagutsu wo Haita Neko - Sekai Isshuu 80 Nichi Daibouken (J)
System : NES

Black screen.

**Comment by FitzRoyX** [comment]
Can't reproduce. Can you post what it says in tools>manifest when the game is loaded?

**Comment by BenjaminSiskoo** [comment]
Tested with ares 2022-04-27 15:50:17 UTC

game
  sha256: d352fc622dd6e9bb4c5e514e2db46adf5d409787dee72a8f3901c06be6bb5843
  name:   Nagagutsu wo Haita Neko - Sekai Isshuu 80 Nichi Daibouken (J)
  title:  Nagagutsu wo Haita Neko - Sekai Isshuu 80 Nichi Daibouken (J)
  region: NTSC-J, NTSC-U, PAL
  board:  HVC-CNROM
    mirror mode=vertical
    memory
      type: ROM
      size: 0x10
      content: iNES
    memory
      type: ROM
      size: 0x8000
      content: Program
    memory
      type: ROM
      size: 0x8000
      content: Character

**Comment by FitzRoyX** [comment]
Appears to be a bad dump from a really old romset. Current dump that matches nescartdb is 68943c9e55fc9df846ae0a20decbe142fe516c9e8ba7b4d2c4f7b6aee0fc0fd7

**Comment by BenjaminSiskoo** [comment]
Niuce catch thanks
