### ISSUE TITLE
[MASTER SYSTEM] Bug with Golvellius ?

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#546]
Emulator : Ares 1.27
Nightly build 2022-05-03 17:32:17 UTC
Options : Default
Game : Golvellius (USA, Europe, Brazil)
System : Master System

GFX bug with a hole. I don't know if the bug exists on the real hardware or not.

Savestate : 

[Golvellius - Valley of Doom (USA, Europe, Brazil).zip](https://github.com/ares-emulator/ares/files/8630296/Golvellius.-.Valley.of.Doom.USA.Europe.Brazil.zip)

![image](https://user-images.githubusercontent.com/12481242/166902884-6823e686-8587-4f35-b3b2-0bf00e3cf1a3.png)

**Comment by BenjaminSiskoo** [comment]
I just finished this game and except the hole problem, the game is playable.

**Comment by invertego** [comment]
It looks like this occurs on real hardware:
https://www.twitch.tv/videos/252096258?t=101m50s

**Comment by Shideravan** [comment]
Isn't a bug. It's a feature lol

**Comment by BenjaminSiskoo** [comment]
> It looks like this occurs on real hardware: https://www.twitch.tv/videos/252096258?t=101m50s

Thanks :)
