### ISSUE TITLE
[NES] Flickering with Digger T. Rock - The Legend of the Lost City (E)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#553]
Emulator : Ares 1.27
Nightly build 2022-04-23 15:12:57 UTC
Options : Default
Game : Digger T. Rock - The Legend of the Lost City (E)
System : Nes

With FCE Ultra : 

![digger fceu](https://user-images.githubusercontent.com/12481242/168294091-0fa0f374-22d1-478d-87f2-2d346c7b53b0.gif)

With Ares : 

![digger ares](https://user-images.githubusercontent.com/12481242/168294132-20022c3e-7666-45f1-85c2-b68443f87306.gif)

**Comment by FitzRoyX** [comment]
Looks similar to Wizards and Warriors (E), just less severe

**Comment by remutro** [comment]
Looks to me like FCEUltra is at fault. For a frame or two you can see the purple flying thing in FCE but it disappears and then never seems to hit digger or cause damage. In Ares, Digger is clearly taking damage here. Does he usually flicker when taking hits (I'm not familiar with this title)? It certainly doesn't look like FCEUltra is doing the right thing here as the enemy shows up briefly and disappears.
