### ISSUE TITLE
[SFC] Major regression with majority of SuperFX ROMs

### ISSUE THREAD

**Issue by ChromiusMixin** [higan-emu/ares#556]
New issue that cropped up with the release of Ares v128. SuperFX ROMs utilizing FastROM no longer launch properly, displaying massively glitched graphics or showing nothing at all. 
This affects Star Fox with SuperFX 2 + FastROM and an experimental Star Fox 2 FastROM hack, both by Star Fox hacker Kandowontu.

Star Fox SuperFX 2 + FastROM:

![image](https://user-images.githubusercontent.com/105760326/168938270-985b6948-21a5-4806-853d-2f031e5a36a0.png)

Star Fox 2 FastROM (Intro only):

![image](https://user-images.githubusercontent.com/105760326/168938485-34095043-097d-4f93-afe6-7c574bf91cf9.png)

**Comment by ChromiusMixin** [comment]
Okay, so, scratch this being just a SuperFX FastROM issue. This breaks nearly **every** SuperFX ROM. Including but not limited to ROM hacks and prototypes.

Games broken are: Star Fox, Star Fox 2, Stunt Race FX, Vortex, DOOM. Dirt Trax FX and Winter Gold are also very likely broken.
Only confirmed working SuperFX game is Super Mario World 2 - Yoshi's Island (Including its prototype builds).

**Comment by LukeUsher** [comment]
[This commit](https://github.com/ares-emulator/ares/commit/d08a9bdcc2ce3ed85dc3f9d7f631bca1ec765fb5) is most likely the cause; not the database entry but the handling of non-power-of-two roms.

Perhaps an alternate solution would be to have mia pad the rom to power-of-two automatically (non-power-of-two rom chips do not physically exist here), and restore the original code.

**Comment by LukeUsher** [comment]
Should be fixes as of [0cafaad](https://github.com/ares-emulator/ares/commit/0cafaad19be8bbc52bd55b1f1a69a2b23d777bb9)
