### ISSUE TITLE
hiro: the hiro gui framework is not 'portable'

### ISSUE THREAD

**Issue by 7zxkv** [higan-emu/ares#562]
Hi,

there remains the following directory / file which was recreated each time the game is launched, which means that ares is not yet fully portable.

_C:\Users\xxxxx\AppData\Local\hiro_  

best regards

**Comment by LukeUsher** [comment]
Good spot; the emulator itself is portable now but this is from the GUI framework, hiro

**Comment by remutro** [comment]
the GUI framework technically creates the hiro directory, but it is really determining appdata path (and path for all 3 OS's) from within nall, specifically by calling userSettings() and userData() found in nall/path.hpp. So any underlying parts of code that rely on these functions is going to cause portability issues.

**Comment by remutro** [comment]
hiro is portable now along with the rest of ares. This issue can be closed.
