### ISSUE TITLE
[PS1] Full emulator crash when switching games

### ISSUE THREAD

**Issue by HeroponRikiBestest** [higan-emu/ares#567]
As far as I can tell, this may not happen with all games, but I can at least confirm it happens when switching between Crash 2 and Crash 1, and between Pingu and Logic Pro Adventure. Additionally, this seems to be capable of happening even after manually unloading your ps1 game (but not closing the emulator) and choosing another. 

Logs:
[error.txt](https://github.com/ares-emulator/ares/files/8776174/error.txt)

Ares v128 compiled 5/25/2022
Linux Mint 20.2

**Comment by invertego** [comment]
Confirmed to no longer be occurring, so this can be closed.
