### ISSUE TITLE
[PS1] Crash Bandicoot 2 - Cortex Strikes Back (USA): Major SPS on lobby holograms, minor polygon flickering throughout game

### ISSUE THREAD

**Issue by HeroponRikiBestest** [higan-emu/ares#576]
Self explanatory, polygon flickering most easily viewable on the title screen logo. At one point during testing the intro level froze right as the music was loading in, but I wasn't able to recreate it.

Ares v128 compiled on 5/26/2022
Linux Mint 20.2

**Comment by LukeUsher** [comment]
Fixed in [7233efb](https://github.com/ares-emulator/ares/commit/7233efbc39bbc9ea40a3182f07d63220987860f5)
