### ISSUE TITLE
[PS1] [Meta Issue] Games with no input

### ISSUE THREAD

**Issue by HeroponRikiBestest** [higan-emu/ares#588]
Affects the following games:
Spyro
Spyro 3
Crash 3
Metal Gear Solid
Silent Hill
Star Ocean - The Second Story
G Darius
Both Pac-Attack games in Namco Anthology 2

**Comment by HeroponRikiBestest** [comment]
https://github.com/ares-emulator/ares/commit/5283135a49e4017e99b93cae5f94ed8639653d88 Fixed all titles except for Crash 3.

**Comment by LukeUsher** [comment]
should all be fixed in latest master;
