### ISSUE TITLE
[PS1] [Meta Issue] High pitched voices

### ISSUE THREAD

**Issue by HeroponRikiBestest** [higan-emu/ares#603]
Currently affects: 

Ace Combat 3 - Electrosphere (Japan, Asia) https://github.com/ares-emulator/ares/issues/569
Langrisser IV & V - Final Edition (Japan) (Langrisser IV Disc) https://github.com/ares-emulator/ares/issues/602
Amerzone - The Explorer's Legacy (Europe) - Also suffers from choppy audio during FMVs
Disney's Atlantis - The Lost Empire (USA)
Spyro 2 - Ripto's Rage! (USA)

**Comment by jeffythedragonslayer** [comment]
How far off is the pitch?

**Comment by HeroponRikiBestest** [comment]
Extremely far. I didn't provide a video at the time because it's incredibly noticeable. If you really need one, here.

https://user-images.githubusercontent.com/50224630/221581686-98955ebe-f701-4efd-8ae2-c52f7c3e654b.mp4

Versus

https://youtu.be/YO7PxXD496Q?t=196

**Comment by mnadareski** [comment]
This also affects the US version of Spyro 2: Ripto's Rage, to somewhat hilarious effect.

**Comment by LukeUsher** [comment]
Fixed as of [7dea816](https://github.com/ares-emulator/ares/commit/7dea8162dba0c15c44011f4e7b6df1ba62944edd) tested with Spyro 2 and Atlantis.
