### ISSUE TITLE
[N64] Nightmare Creatures boots and runs extremely slowly

### ISSUE THREAD

**Issue by kev4cards** [higan-emu/ares#614]
As first noted by remutro, Nightmare Creatures no longer boots. Bisected to commit 0084865 (decreased SI DMA delay).

**Comment by remutro** [comment]
And as found by kev4cards afterwards, the game does eventually boot, but it takes a while for the first screen to appear and the games runs extremely slow.

**Comment by kev4cards** [comment]
Updated the title to reflect the actual status.

**Comment by kev4cards** [comment]
Fixed by commit cb01795 .
