### ISSUE TITLE
[NES] GFX bug with Tiny Toons Adventure (U)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#615]
Emulator : Ares 1.28
Nightly build 2022-06-03 23:46:42 UTC
Options : Default
Game : Tiny Toons Adventure (U)
System : Nes

Look at the bottom of the screen, when the character move from the left to the right.

Savestate : 
[Tiny Toon Adventures (U).zip](https://github.com/ares-emulator/ares/files/8839765/Tiny.Toon.Adventures.U.zip)

![tinytoons](https://user-images.githubusercontent.com/12481242/172045816-d2e6ce8f-3da8-4037-81f2-e7f552b360e6.gif)

**Comment by Kawa-oneechan** [comment]
Looks like regular ol' overscan garbage to me.

**Comment by BenjaminSiskoo** [comment]
Dunno, it seems I can read 101010101, I'm not sure.

**Comment by Shideravan** [comment]
> Dunno, it seems I can read 101010101, I'm not sure.

It's common with NES overscan garbage. It's just displaying some content from CHR ROM of the cartridge.It's normal and happens with various games when the overscan area is shown.
Look at this print of Tiny Toon Adventures in Mesen
![image](https://user-images.githubusercontent.com/12163923/172970103-7565c155-f969-4135-9fff-1bdc5eb2ae86.png)

**Comment by BenjaminSiskoo** [comment]
Ok So I CLose the br ?
