### ISSUE TITLE
[PC Engine] Devil Crash - Naxat Pinball (Japan) has a row of garbage pixels at the bottom of the screen

### ISSUE THREAD

**Issue by foryourinformation6** [higan-emu/ares#617]
![crasj](https://user-images.githubusercontent.com/105691567/173234101-058e87bb-46e4-4138-8e4d-4586bcc787a9.PNG)

**Comment by invertego** [comment]
Observed on real hardware: https://youtu.be/AYrLORZYi-0?t=144
