### ISSUE TITLE
Where is the configuration file stored?

### ISSUE THREAD

**Issue by braiam** [higan-emu/ares#623]
I'm trying to move my old higan configuration to ares, but I can't find the configuration file on .config/ares. I found something in .local, but that is not where configuration files should reside according to the [userSettings](https://github.com/ares-emulator/ares/blob/a7ce0c22fa64a7d96929535ec1c3da090e420c00/nall/path.hpp#L101) definition. I saw that nowhere is that function used and the userData function is used to create a new directory in the [locate](https://github.com/ares-emulator/ares/blob/a7ce0c22fa64a7d96929535ec1c3da090e420c00/desktop-ui/desktop-ui.cpp#L9) function. Is this the supposed directory? Can I replace .local/share/ares/settings.bml with .config/higan/settings.bml ?

**Comment by LukeUsher** [comment]
ares and higan have a different user-interface and therefore the settings configuration is different, and are not interchangeable with each other
