### ISSUE TITLE
[MD] Striker: Incorrect whistle sound effect

### ISSUE THREAD

**Issue by BiZkViT96** [higan-emu/ares#625]
The whistle at the beginning of the match sounds incorrect.

Real hardware https://youtu.be/D-HfGgy5D9o

Kega doesn't have this bug.

Striker (Europe)
SHA1 9917c35a263cc9bd922d55bf59d01bc2733b4e24

Tested on ares nightly 2022-06-19

PS: If you are interested, MiSTer MD core also has some [issue](https://github.com/MiSTer-devel/Genesis_MiSTer/issues/200) with the whistle. This report is inspired by that bug report.

**Comment by FitzRoyX** [comment]
fixed by #723
