### ISSUE TITLE
[N64] Garbled mess of colored squares upon loading games. 

### ISSUE THREAD

**Issue by mysterystain** [higan-emu/ares#634]
I can't recall exactly when this issue began. It didn't start until I started fiddling with Ares v128. This also began after Fallout76 to Steam migration, though I don't know if that is relevant but figured I'd mention it anyway. 

The issue first began with m64p (parallel). As soon as it began for m64p, I checked Ares and got the same. 
I restarted my computer, thinking that would fix it and it did for the time. It had stopped for a period of time.
It began again but instead of restarting PC, I would just close the window and just restart the program and try loading a rom again.
After doing that several times, it'd finally load and be fixed for the time being. Usually the rest of the day. 
This had worked for a time but has since seemed to stop working as no amount of doing so seems to brute force passed it now.

OS: Windows10
CPU: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz, 3801Mhz, 4 Core(s), 4 Logical Processor(s)
GPU: NVIDIA GeForce GTX 1060 3GB
Ares v128

![Legend of Zelda, The - Ocarina of Time (USA) (Rev 1) 2022-07-07 14-54-23](https://user-images.githubusercontent.com/108964567/178087641-d90a522f-a588-467a-af6a-ba292a1d89a6.png)
![turok_dinosaur_hunte-000](https://user-images.githubusercontent.com/108964567/178087642-4ca85462-21cc-43b5-823c-ae99a5ed3766.png)

Zelda screenshot is from Ares v128 (don't know why it's stretched). 
Turok screenshot from m64p.

**Comment by FitzRoyX** [comment]
Under settings>video try checking or unchecking "Vulkan". Also try deleting your config.

**Comment by mysterystain** [comment]
I tried the unchecking/rechecking Vulkan but that didn't work. It hasn't happened since my last system restart.
As for this config, where would Ares put this? I seem to be having difficulty finding it. 
I can be a bit of a ditz so it's possible I'm just not noticing it.

**Comment by remutro** [comment]
If this also impacts m64p, I would think this is related to either video drivers, or cache getting corrupted, or something along those lines. Restarting Windows making it work for a while further indicates it isn't the app itself. If it effects Vulkan in multiple app/games, not sure what ares will be able to do about it.

**Comment by LukeUsher** [comment]
agreed; this does not sound like an ares issue

**Comment by mysterystain** [comment]
Dang, sucks to be me, then.
