### ISSUE TITLE
[N64] Crashing on rom load when using vulkan.

### ISSUE THREAD

**Issue by tomster785** [higan-emu/ares#637]
As the title says, whenever I attempt to load an N64 rom with vulkan enabled, the emulator crashes and closes. With vulkan disabled however, the games load just fine.

I have a GTX 1080 with fully up to date drivers, and I've also tested with the previous release, the current release, and a nightly release too.

**Comment by Shideravan** [comment]
> As the title says, whenever I attempt to load an N64 rom with vulkan enabled, the emulator crashes and closes. With vulkan disabled however, the games load just fine.
> 
> I have a GTX 1080 with fully up to date drivers, and I've also tested with the previous release, the current release, and a nightly release too.

I'm using a GTX 1070 but can't reproduce. Vulkan is working fine for me in the latest nightly release and with v129
![image](https://user-images.githubusercontent.com/12163923/180586329-d0288281-f1dc-4dfa-bc5e-b6677d19dbd6.png)

**Comment by tomster785** [comment]
I'm really sorry, it turns out I'm a massive moron and I'm very embarrassed to admit what I'm about to say.

I updated/restarted windows and it works now. I don't know if it's the update, or the restart that did it. But either way, I really should have tried both of those things before raising an issue. I can't apologise enough, this has been one of my more stupid moments in life haha.

I'm going to take myself into a corner and have a word with myself now, sorry for wasting people's time.
