### ISSUE TITLE
[MD] Comix Zone: Graphical glitches in episode 2

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#644]
In episode 2, some glitches are happening when fighting against enemies in snow
https://youtu.be/ZrtAk_0JW-4

Savestate:
[Comix Zone (U) [!].zip](https://github.com/ares-emulator/ares/files/9173073/Comix.Zone.U.zip)

ares d52a3b9dfc0fcd6086ea0ed38e38af30c62be4d9

**Comment by remutro** [comment]
@Shideravan - This should be retested with the most recent versions of Ares (v131 right now). There have been many Mega Drive improvements and it is believed to be fixed.

**Comment by ceed0** [comment]
Still present on v131.

**Comment by BiZkViT96** [comment]
Fixed

**Comment by BiZkViT96** [comment]
Not a emulator bug. Exists on real MD. Confirmed by TascoDLX.
