### ISSUE TITLE
[A26] Ares crash after loading Atari 2600 savestates in a new session

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#646]
Atari 2600 games when running, support save states well. But if you close ares and load the game and load savestate, ares will crash.

**Comment by FitzRoyX** [comment]
You using the latest build or 129 official? Because I can't reproduce on the latest build. Invertego fixed the a26 crashing issues shortly after v129 was released.

**Comment by Shideravan** [comment]
Yes, it's not reproducible in the latest build anymore.
