### ISSUE TITLE
[PS1] Tactics Ogre (USA) - Stuck on "Loading"

### ISSUE THREAD

**Issue by CDogs-Fan** [higan-emu/ares#647]
When starting a "New Game" from the main menu, the game goes to a loading screen, but gets stuck on "Loading".

Game:  Tactics Ogre (USA).cue

**Comment by jeffythedragonslayer** [comment]
Does the animation next to "Now Loading..." freeze or does it continue animating?

https://youtu.be/77mcWA9etG0?t=159

**Comment by invertego** [comment]
It looks like this has been fixed in the interim; it doesn't repro on the latest build of ares.

**Comment by CDogs-Fan** [comment]
Sorry for the late reply.  I just tried the latest version of Ares and the game is now able to progress beyond the loading screen.  Unfortunately, I've run into a new problem with loading a saved game.  I'll write more about this problem in a new post.
