### ISSUE TITLE
Flatpak release: unable to save games ("The current save path is read only" error)

### ISSUE THREAD

**Issue by brandonbeaumia** [higan-emu/ares#664]
In the Flatpak distribution of Ares, I can't save my games due to a persistent `The current save path is read only` error. The filesystem permission via `flatpak info --show-permissions dev.ares.ares` is listed as `home:ro` (read only) instead of just `home`. Should it be `home` instead so we have write access or is there something else I'm missing?

Alternatively, the filepicker could show hidden files so we can select `~/.var/app/dev.ares.ares`, even if that's not an ideal place for them. I can't type the path in the interface or choose it through the picker on Pop!_OS 22.04.

**Comment by LukeUsher** [comment]
The flatpak build of ares isn't an official distribution, we just link to it for convenience

Consider filing an issue against https://github.com/flathub/dev.ares.ares

**Comment by brandonbeaumia** [comment]
I was not aware, sorry! Posting there now, thank you.
