### ISSUE TITLE
MSU-1 autodetect not implemented

### ISSUE THREAD

**Issue by brandonbeaumia** [higan-emu/ares#666]
Ares currently requires specific filenames for MSU-1 games to work (`msu1.data.rom` and `msu1.track-0.pcm` (etc)). Autodetecting MSU-1 would save some headache.

**Comment by LukeUsher** [comment]
Fixed in [fe8afe0](https://github.com/ares-emulator/ares/commit/fe8afe05defd5744c46285deaf97ed37f30a58b1)
