### ISSUE TITLE
[PS1] Ray-Ray CD-ROM (Japan) crashes after watching a video

### ISSUE THREAD

**Issue by drachenschanze** [higan-emu/ares#667]
Choose Raystorm > Movie > Raystorm movie. Watch or skip it.

 Then return to this menu and the game will crash 100% of the time. 

![Capture](https://user-images.githubusercontent.com/96800307/184397042-4a0e7d02-fc26-4ec0-bc88-d701c1ff94df.PNG)

**Comment by HeroponRikiBestest** [comment]
Already open https://github.com/ares-emulator/ares/issues/570
