### ISSUE TITLE
[MEGADRIVE] Black screen at the start - Triple Play 96 (USA)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#681]
Emulator : Ares 1.29
Nightly build 2022-08-20 21:03:27 UTC
Options : Default
Game : Triple Play 96 (USA)
System : Megadrive / Genesis

Black screen at the start. No Sega logo.

**Comment by BiZkViT96** [comment]
Same as #407, no?

**Comment by Shideravan** [comment]
![image](https://user-images.githubusercontent.com/12163923/192723448-ec7745be-d1f4-4a06-8573-cec8dfd6ec73.png)
It's working in most recent version of ares
