### ISSUE TITLE
[MEGADRIVE] Black screen at the start - Triple Play - Gold Edition (USA)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#682]
Emulator : Ares 1.29
Nightly build 2022-08-20 21:03:27 UTC
Options : Default
Game : Triple Play - Gold Edition (USA)
System : Megadrive / Genesis

Black screen at the start. No Sega logo.

**Comment by LukeUsher** [comment]
Duplicate of #242
