### ISSUE TITLE
[32X] Doom_E_32X_Resurrection_v2.2 - Artefacts on top of the screen...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#696]
Emulator : Ares 1.29
Nightly build 2022-08-30 08:56:16 UTC
Options : Default
Game :  Doom_E_32X_Resurrection_v2.2
System : 32X

**Describe the bug**
Artefacts on top of the screen

**To Reproduce**

**Expected behavior**
No artefacts

**Screenshots**
https://media.discordapp.net/attachments/223537796562812928/1014457889647230998/unknown.png

**Additional context**

**Comment by LukeUsher** [comment]
Should be resolved after 2e38fa5fc6db1d3c7aa38df49c63d67e6291eeeb

**Comment by BenjaminSiskoo** [comment]
Seems perfect, several other 32X games had the same problem, I'll test it later :) tahnks for the fix

![image](https://user-images.githubusercontent.com/12481242/189223155-ea97dc5f-c75e-491d-9abc-eb193479eeec.png)
