### ISSUE TITLE
[GBA] Aero the Acro-Bat - Rascal Rival Revenge (Europe) is not booting...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#717]
Emulator : Ares 1.29
Nightly build 2022-09-04 10:16:23 UTC
Options : Default
Game : Aero the Acro-Bat - Rascal Rival Revenge (Europe), Aero the Acro-Bat - Rascal Rival Revenge (USA), Aero the Acro-Bat - Rascal Rival Revenge (USA) (Beta)
System : GBA

**Comment by FitzRoyX** [comment]
This worked prior to the input polling changes for Advance Wars.

**Comment by LukeUsher** [comment]
> This worked prior to the input polling changes for Advance Wars.

that is very odd and doesn't make sense to me because the input polling is a front-end change and did not change the actual emulation code in any way: this to me, implies that there is an underyling bug somewhere that has now been exposed.

**Comment by FitzRoyX** [comment]
You're right, it's further up the PR history. Let me track down the real breaker.

**Comment by FitzRoyX** [comment]
It was the gba eeprom changes.

**Comment by LukeUsher** [comment]
Reopened this and #687

The gba eeprom emulation needs a larger rework in order to fix one without breaking the other.

**Comment by LukeUsher** [comment]
fixed in 972495df89353a73bee91a3fe917853f8733d515
