### ISSUE TITLE
[32X] Sound problem in game with FIFA Soccer 96 (Europe) (En,Fr,De,Es,It,Sv)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#731]
Emulator : Ares 1.29
Nightly build 2022-09-10 23:02:19 UTC
Options : Default
Game : FIFA Soccer 96 (Europe) (En,Fr,De,Es,It,Sv)
System : 32X

Crackles or delay with the sound (I don't know the exact word in english. Before going in game black screen but you can hear the sound.

**Comment by BenjaminSiskoo** [comment]
Improvements with this game and ares 2022-09-23 11:58:46 UTC : 

![image](https://user-images.githubusercontent.com/12481242/191964733-bb03a0d7-8244-4fc5-ba89-14a93cc9f4f3.png)

The game is playable but the sound is still not correct.

FPS goes up to down,

**Comment by remutro** [comment]
Fixed in latest nightly build (after release of 130.1).

Game runs at a solid 60 fps as well.
