### ISSUE TITLE
[32X] Messed text screen with Golf Magazine Presents - 36 Great Holes Starring Fred Couples (Europe)... 

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#732]
Emulator : Ares 1.29
Nightly build 2022-09-10 23:02:19 UTC
Options : Default
Game : Golf Magazine Presents - 36 Great Holes Starring Fred Couples (Europe)
System : 32X

After choosing your pad, Ares seems to crash.

![image](https://user-images.githubusercontent.com/12481242/189520952-f60f68ff-6169-4215-bbc2-95aa7264eadd.png)

**Comment by remutro** [comment]
If you hit right just once and hit start, you can get in-game.

**Comment by BenjaminSiskoo** [comment]
Ares 2022-09-23 11:58:46 UTC

Improvements with this game, the text is still messed, but you can go in game.

![image](https://user-images.githubusercontent.com/12481242/191965595-c780f5be-a2f9-471f-a053-b2c37f5cabe2.png)

**Comment by BenjaminSiskoo** [comment]
Fixed today with : 2022-09-23 15:33:06 UTC
