### ISSUE TITLE
[32X] Engine sound of the motocross is not right with Motocross Championship (Europe)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#733]
Emulator : Ares 1.29
Nightly build 2022-09-10 23:02:19 UTC
Options : Default
Game : Motocross Championship (Europe)
System : 32X

In game, when you start the race, the sound of the engine of the motocross is not correct.

**Comment by remutro** [comment]
Fixed in latest nightly build (after release of 130.1).
