### ISSUE TITLE
[32X] Music is not working with NBA Jam - Tournament Edition (World)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#734]
Emulator : Ares 1.29
Nightly build 2022-09-10 23:02:19 UTC
Options : Default
Game : NBA Jam - Tournament Edition (World)
System : 32X

There is a contiuous sound, I guess the music is not played properly.

**Comment by remutro** [comment]
Sound issue fixed in latest nightly build (after release of 130.1).

You will still get an SH2 processor exception going in-game. This doesn't happen in SH2 CPU interpreter mode, but you won't be able to run the game at full speed.
