### ISSUE TITLE
[32X] Black screen at the start with WWF Raw (World)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#738]
Emulator : Ares 1.29
Nightly build 2022-09-10 23:02:19 UTC
Options : Default
Game : WWF Raw (World)
System : 32X

![image](https://user-images.githubusercontent.com/12481242/189522531-d872dd52-c694-4ca2-a4f9-54c05770fa84.png)

**Comment by remutro** [comment]
Set second controller to "Nothing" and reset. Game is playable.

**Comment by BenjaminSiskoo** [comment]
I can't see the option 

![image](https://user-images.githubusercontent.com/12481242/191966715-94069980-5085-43f9-a432-9e5e1402c72b.png)

**Comment by remutro** [comment]
Load the WWF game, underneath the Mega 32X Menu item, select Controller Port 2 and set the option to "Nothing". Underneath the Mega 32X menu item again, after changing controller port 2, select the reset option. Then the game is fully playable. A note has been added to the compatibility database. There is something funny going on with the game trying to identify the multi-tap accessory that is messing things up for now.

**Comment by invertego** [comment]
This is working as of 8b734146be0e1ac6604e941eca50bc765f480a7c, after which the game is able to proceed past the multi-tap check.

**Comment by BenjaminSiskoo** [comment]
Yup it works, FPS are not stable but it works :)
