### ISSUE TITLE
[32X] Crackles sounds with World Series Baseball Starring Deion Sanders (USA)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#739]
Emulator : Ares 1.29
Nightly build 2022-09-10 23:02:19 UTC
Options : Default
Game : World Series Baseball Starring Deion Sanders (USA)
System : 32X

Right after the sega logo, you can hear some crackles...

**Comment by remutro** [comment]
Fixed in latest nightly build (after release of 130.1).
