### ISSUE TITLE
[32X] Crackles sounds and GFX artefact with Virtua Racing Deluxe (USA)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#740]
Emulator : Ares 1.29
Nightly build 2022-09-10 23:02:19 UTC
Options : Default
Game : Virtua Racing Deluxe (USA)
System : 32X

Right after the sega logo, you can hear some crackles.
GFX artefacts on the sega logo.

![image](https://user-images.githubusercontent.com/12481242/189522728-c150c04f-d484-40f5-aac8-f7fe3157e3e8.png)

**Comment by BenjaminSiskoo** [comment]
GFX problem was fixed yesterdy. But sthe sound is not fixing.

**Comment by BiZkViT96** [comment]
Has the sound been fixed? I don't hear any sound problems.

ares nightly 2023-03-03

**Comment by BenjaminSiskoo** [comment]
soudns good :) thanks for pointing that
