### ISSUE TITLE
[32X] Kind of whistles with Virtua Fighter (Japan, USA)... 

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#742]
Emulator : Ares 1.29
Nightly build 2022-09-10 23:02:19 UTC
Options : Default
Game : Virtua Fighter (Japan, USA), Virtua Fighter (Europe)
System : 32X

Kind of whistles.

**Comment by remutro** [comment]
Fixed in latest nightly build (after release of 130.1).

**Comment by remutro** [comment]
Fixed in latest nightly build (after release of 130.1).

Note the Europe ROM has really odd behavior with an AI component (distorts itself, instant ring outs, etc.)
