### ISSUE TITLE
[32X] Crackles sounds and freeze with Soulstar X (USA) (Proto)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#744]
Emulator : Ares 1.29
Nightly build 2022-09-10 23:02:19 UTC
Options : Default
Game : Soulstar X (USA) (Proto)
System : 32X

![image](https://user-images.githubusercontent.com/12481242/189523257-db692115-b551-42bb-b4c1-74af502bba80.png)

**Comment by BiZkViT96** [comment]
How i understand all the problems with the crackling sound come from the poor performance of the 32X core in general.

**Comment by BenjaminSiskoo** [comment]
Ares .0132

![image](https://user-images.githubusercontent.com/12481242/224538883-26d7d248-9552-494d-9eaa-e94c63e785f6.png)
 Missing hud and the ship is not displayed

**Comment by fedex81** [comment]
Hello,
FYI I've [fixed](https://github.com/fedex81/helios32x/blob/master/src/main/java/s32x/dict/S32xDict.java) the issue with the missing 32x layer by adding a framebuffer mirror:

Undocumented mirroring (see soulstar) 
24000000 - 24020000 DRAM 
24020000 - 24040000 OVERIMAGE 
24040000 - 24060000 DRAM MIRROR

**Comment by LukeUsher** [comment]
Fixed in 0bea9d3a2
