### ISSUE TITLE
[NES] Black screen at the start with Kyatto Ninja Teyandee (J)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#748]
Emulator : Ares 1.29
Nightly build 2022-09-13 11:01:54 UTC
Options : Default
Game : Kyatto Ninja Teyandee (J)
System : NES

![image](https://user-images.githubusercontent.com/12481242/189894243-57dbf75a-c38a-4f8a-a49e-a3e7190c674e.png)

**Comment by BiZkViT96** [comment]
I can't reproduce it
![2022-09-13 19_37_25-Cat Ninden Teyandee (Japan)](https://user-images.githubusercontent.com/88586431/189903372-85e4b5e4-1674-4c95-b900-b56b3f90196a.png)

SHA1 3CF526AAA338F62B5AECFAEA4ED9D92200C736FA

**Comment by BenjaminSiskoo** [comment]
Is it usefull ?

![image](https://user-images.githubusercontent.com/12481242/189904433-477e2340-a7d1-4562-9373-160dd98c9879.png)

**Comment by BiZkViT96** [comment]
The version that loads fine
![2022-09-13 19_51_21-Tools](https://user-images.githubusercontent.com/88586431/189906198-11ff411a-cd53-47af-8a92-bc0cf883f378.png)

**Comment by BenjaminSiskoo** [comment]
I found a release of this game. It works. Is there a website about right sha nes games ?
