### ISSUE TITLE
[NES] Black screen at the start with Impossible Mission II (U) [!]...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#749]
Emulator : Ares 1.29
Nightly build 2022-09-13 11:01:54 UTC
Options : Default
Game : Impossible Mission II (U) [!]
System : NES

![image](https://user-images.githubusercontent.com/12481242/189897228-e9309371-c2d9-4071-9d21-38b9c3b5d72d.png)

**Comment by remutro** [comment]
Two Things:

- This game is unlicensed (label should be added)
- This game relies on unimplemented opcode 77
