### ISSUE TITLE
[NES] Black screen at the start with Wolf Spirit (World) (v1.1) (Demo) (Aftermarket) (Homebrew)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#750]
Emulator : Ares 1.29
Nightly build 2022-09-13 17:07:05 UTC
Options : Default
Game : Wolf Spirit (World) (v1.1) (Demo) (Aftermarket) (Homebrew)
System : NES

![image](https://user-images.githubusercontent.com/12481242/190028373-8c94afc5-954e-4b79-b23c-5afd501a6d73.png)

**Comment by invertego** [comment]
This should have the `game-is-unlicensed` label. The ROM is using the homebrew [UNROM 512](https://www.nesdev.org/wiki/UNROM_512) mapper.

**Comment by asiekierka** [comment]
Game available here: https://valdirsalgueiro.itch.io/wolf-spirit - has been fixed by https://github.com/ares-emulator/ares/pull/1225
