### ISSUE TITLE
[NES] Black screen at the start with 2A03 Puritans (World) (Aftermarket) (Unl)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#751]
Emulator : Ares 1.29
Nightly build 2022-09-13 17:07:05 UTC
Options : Default
Game : 2A03 Puritans (World) (Aftermarket) (Unl)
System : NES

![image](https://user-images.githubusercontent.com/12481242/190102922-c7d53247-6996-499c-b535-c2c2a06d97f7.png)

**Comment by asiekierka** [comment]
ROM is broken on Mesen too; seems to rely on UNROM-512 initialization details which are not guaranteed on real console.

**Comment by asiekierka** [comment]
Oh, no. It's just a mislabeled mapper 31. That's what you get from not downloading straight from the author, folks!

Proper download: http://rainwarrior.ca/projects/nes/2a03puritans.nes

**Comment by BenjaminSiskoo** [comment]
I close the br ?
