### ISSUE TITLE
[NES] Black screen at the start with 2600 AD (World) (Demo) (Aftermarket) (Homebrew)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#757]
Emulator : Ares 1.29
Nightly build 2022-09-13 17:07:05 UTC
Options : Default
Game : 2600 AD (World) (Demo) (Aftermarket) (Homebrew)
System : NES

![image](https://user-images.githubusercontent.com/12481242/190105159-ae81d47c-99a7-49cf-9767-ce1e8a64732f.png)

**Comment by asiekierka** [comment]
Game available here: https://itch.io/jam/nesmaker-byte-off-2020/rate/762071

Fixed by https://github.com/ares-emulator/ares/pull/1225
