### ISSUE TITLE
[NES] Black screen at the start with Action 53 Function 16 Volume One (World) (Aftermarket) (Homebrew)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#758]
Emulator : Ares 1.29
Nightly build 2022-09-13 17:07:05 UTC
Options : Default
Game : Action 53 Function 16 Volume One (World) (Aftermarket) (Homebrew)
System : NES

![image](https://user-images.githubusercontent.com/12481242/190105872-1bfbe40c-bea3-4aa4-a6b5-936f0285df8f.png)

**Comment by asiekierka** [comment]
Fixed by https://github.com/ares-emulator/ares/pull/1226

Official download: https://action53.itch.io/vol1
