### ISSUE TITLE
[NES] Left display is not rightwith Addams Family, The - Pugsley's Scavenger Hunt (Europe)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#759]
Emulator : Ares 1.29
Nightly build 2022-09-13 17:07:05 UTC
Options : Default
Game : Addams Family, The - Pugsley's Scavenger Hunt (Europe)
System : NES

![addamsares](https://user-images.githubusercontent.com/12481242/190107366-364e7a00-3021-46cc-a364-bd6c0dd3091c.gif)
![addamsnestopia](https://user-images.githubusercontent.com/12481242/190107371-cb6fae6e-0556-4bd2-94e7-a5de0cc8917f.gif)

**Comment by LukeUsher** [comment]
Please compare against real hardware, not emulators.

It looks like the game might be using the "blank left column" feature of the nes, and we have no idea if nestopia is correct or not here.

**Comment by BenjaminSiskoo** [comment]
I understand, I saw several videos on youtube, but i don't know if it'sp played on original hardware or not. I don"t have the orginal game to test it on my nes.

**Comment by BiZkViT96** [comment]
Did you just test two different roms? You can't do that. Beta and release versions are different. Even the text is different.
![2022-09-14 20_58_51-Addams Family, The - Pugsley's Scavenger Hunt (Europe)](https://user-images.githubusercontent.com/88586431/190175165-bb21edc6-e921-4d1b-8945-333cf3e5f2e4.png)

**Comment by LukeUsher** [comment]
Closing as invalid, @BiZkViT96 is right: you are comparing two different game roms here.

**Comment by BenjaminSiskoo** [comment]
Yes it's a mistake, error is human
