### ISSUE TITLE
[NES] Grey screen at the start withAdventures of Lex and Grim, The (World) (Aftermarket) (Homebrew)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#760]
Emulator : Ares 1.29
Nightly build 2022-09-13 17:07:05 UTC
Options : Default
Game : Adventures of Lex and Grim, The (World) (Aftermarket) (Homebrew)
System : NES

Grey screen at the start butr you can hear some sound

![image](https://user-images.githubusercontent.com/12481242/190108204-a6d68ecd-dc7a-498b-b0e7-8552aaf25fc5.png)

**Comment by BenjaminSiskoo** [comment]
Emulator : Ares 1.33
Nightly build2023-09-19 09:35:10 UTC

Small improvements : it's going in game :
![image](https://github.com/ares-emulator/ares/assets/12481242/1e3992dd-1110-4d1a-a0cc-ecc570bf3d0a)

**Comment by invertego** [comment]
Sour investigated this game and shared conclusions here: https://github.com/SourMesen/Mesen/issues/137

Given that it wouldn't work on real hardware, I think it's out of scope for ares as well.
