### ISSUE TITLE
[NES] Black screen at the start with AfterWorld DELUXE (World) (Aftermarket) (Homebrew)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#761]
Emulator : Ares 1.29
Nightly build 2022-09-13 17:07:05 UTC
Options : Default
Game : AfterWorld DELUXE (World) (Aftermarket) (Homebrew)
System : NES

![image](https://user-images.githubusercontent.com/12481242/190110224-07e2a8df-410b-4e56-906d-3dbbd90f0b5e.png)

**Comment by asiekierka** [comment]
Another NESmaker game... like all of them, probably fixed by https://github.com/ares-emulator/ares/pull/1225
