### ISSUE TITLE
[NES] Black screen at the start with Alex Islands (World) (Aftermarket) (Homebrew)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#762]
Emulator : Ares 1.29
Nightly build 2022-09-13 17:07:05 UTC
Options : Default
Game : Alex Islands (World) (Aftermarket) (Homebrew)
System : NES

![image](https://user-images.githubusercontent.com/12481242/190111133-2fb03741-5d71-41e8-b3e5-aa0670c759dc.png)

**Comment by asiekierka** [comment]
Another NESmaker game, found at https://itch.io/jam/exotic-system-jam/rate/1361975 , fixed by https://github.com/ares-emulator/ares/pull/1225
