### ISSUE TITLE
[HIRO] "Emulators" options aren't being showed in menu anymore

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#763]
**Describe the bug**
As result, the option to not group emulators by manufacturer or even doesn't show some systems aren't available anymore.

**To Reproduce**
1. Go to 'Configuration'
2. Click on 'Emulator' in old version. The option isn't present anymore in recent builds.

**Expected behavior**
To have the option and to choose to not group emulators or doesn't show some of them.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/12163923/190246527-65ae354d-64a3-444d-a3bd-f04b19239a24.png)

After:
![image](https://user-images.githubusercontent.com/12163923/190246576-95f3ccb5-6c08-41e5-abc5-7b4c5a302aaa.png)

**Additional context**
I'm not sure exactly in what build this regression in mia happened. But I'm certain it was in v129 cycle.

**Comment by LukeUsher** [comment]
Not a regression: this functionality was removed to simplify the codebase, to prevent having to implement future menu-related features multiple times for each configuration.

**Comment by Shideravan** [comment]
I still prefer to just click once to select a system the old way. This makes some clicks unnecessarily redundant when doing mass testings.
Maybe we need to rethink the interface then.

**Comment by remutro** [comment]
I'm not sure why this additional menu item is needed, but if it was removed then we should comment out the systems that don't work in source so users don't bang their heads against the wall trying to figure out why nothing happens with these systems. 

For now, this applies to "Mega CD 32X" & "Neo Geo MVS".

**Comment by Shideravan** [comment]
Maybe a keyboard shortcut for open rom for each system emulated may help to improve usability as a more direct menu option is now removed.
Eg.: Ctrl + S open a SNES rom
       Ctrl + F open a Famicom rom
       Ctrl + P open a PlayStation game
       Ctrl + N open a Nintendo 64 rom
       ...
       Also, these shortcut can be configurable alongside other shortcuts

**Comment by LukeUsher** [comment]
As above, this was an intentional change to simplify the codebase.
