### ISSUE TITLE
[PCE] Valkyrie no Densetsu: Graphical bug

### ISSUE THREAD

**Issue by BiZkViT96** [higan-emu/ares#771]
This is the same problem that was described in [#204](https://github.com/ares-emulator/ares/issues/204)

For some reason despite the fact that PR https://github.com/ares-emulator/ares/pull/699 from @invertego fixed a bug in the original Japanese rom, the bug remained in translated version.

Works fine on Mednafen 1.31.0-UNSTABLE August 22, 2022
![2022-09-18 03_19_41-Valkyrie no Densetsu (T+Eng) (Japan)](https://user-images.githubusercontent.com/88586431/190875385-7dbeaec1-717d-462a-b691-d3f2d91cecce.png)

Patch from https://www.romhacking.net/translations/2637/
I applied (RAW) Valkyrie no Densetsu (English v1.0).ips to ROM with SHA1: 2054898ae28f962d2e20cdaca62e8b88e932f304 As it says in the instructions.

Valkyrie no Densetsu (T+Eng) (Japan)
SHA1 aaa4b32bc980f04b54932bd6792955fa25ebc22c

Tested on ares nightly 2022-09-17

**Comment by invertego** [comment]
The patched ROM works if "Pixel Accuracy Mode" is checked in video settings. The PR you linked makes the base game work even when pixel accuracy mode is disabled, but it needs to be able to detect the game from the ROM's hash, and patched versions will have different hashes.

**Comment by BiZkViT96** [comment]
Makes sense. Is it possible to add the translated rom to the database? Or is it against the rules?

**Comment by LukeUsher** [comment]
It is infeasible to add every possible rom hack/translation to the game database; the database is reserved for commercial releases only.

Pixel accuracy mode will have to be used for the time being.
