### ISSUE TITLE
[A26] Sea Monster: ares crashes when you start the gameplay

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#785]
**Describe the issue**
The game starts and runs the attract mode. But when you press "Start" button to start the game, ares crashes immediately.

```
Name: Sea Monster (USA).a26
Size: 4096 bytes (4 KiB)
SHA256: 0af02f4cc3642e486937d00c2fdd152042a32d2d2f1c72d0c2ff9b2031d85116
```

**Comment by jeffythedragonslayer** [comment]
What OS are you on?  Would be nice if we could get a core dump.

**Comment by Shideravan** [comment]
It's fixed in the latest ares version.
