### ISSUE TITLE
[N64] Aleck64 Conversions that are not in the database

### ISSUE THREAD

**Issue by meowthed** [higan-emu/ares#787]
Seems that only 3 games are able to boot for these series of Aleck64 conversions, which are picked up by Ares' database: Eleven Beat, Star Soldier, and ViviD Dolls. 

**Describe the issue**
Aside from the games mentioned, the rest boot to a black screen.

**Rom Information**
Specify the impacted rom filename and any associated hashes (sha256 preferred)

```
file: Aleck Bordon Adventure 4th Story - Tower & Shaft (English Translated, Rev 1).n64
sha256: A3F477038F87FDE98AECECE8E46E14DC7744E7D2518BBEFF7744FE443ED207A3
file: Don-chan Puzzle Hanabi de Doon! (JP, Rev 1.1).n64
sha256: 6DE2DDADD075F7B3BE5C4795A64FEAB7272579C1941FDAB0ED5494396307885B
file: KuruKuru Fever (JP, Rev 1.1).n64
sha256: 3C782FBBB38868136978FCAF2D7ECA5A5C536EC39CE13F0A270637CA9363CE39
file: Magical Tetris Challenge (English Translated, Rev 2).n64
sha256: A77E59A23FD736D41862FB6BDFA4F03AD3694D1B20FA635B34AE0151979CE568
file: Mayjinsen 3 (JP).z64
sha256: D66C2C1339194C08C6EF3521BE131FCFF8508ECCB0CE581D699BF83B11C61001
file: Shin Super Real Mahjong Series Hi-Pai Paradise (JP).z64
sha256: FA9AD138C0FE335D931752E2981664F2F05DF63F3D48E57E393F44993200797B
file: Shin Super Real Mahjong Series Hi-Pai Paradise 2 - Onsen ni Ikouyo! (JP).n64
sha256: 885B98AE8172FA6957E7D025DC6FF79CDD0799197D9D0307FB39D128E09EA4F8
file: Super Real Mahjong Vs. (JP, Rev 2).n64
sha256: 41E09C40AC5587DD96D19FF34DEB8CA8250E0E10FB2D84153E331589371BC36B
```

**Comment by remutro** [comment]
None of these entries are in the internal database, or our compatibility database. The fact that some load and run is kind of lucky. We usually only add licensed/released games to our database/compatibility lists (base on no-intro/redump dat's).

If ares were to introduce aleck64 based games, then the correct way would be to actually implement the Aleck64 jamma based arcade system, not hacked up roms.

The same goes for iQue based games, the actual iQue should be implemented so ROM hacks are not necessary.

**Comment by meowthed** [comment]
hmm, having to implement the Aleck64 system instead should be fine, though as of the time of writing, arcade dumps for this system are MAME-compliant .zip files. We could try to run them using the .u3 files that are inside these zip files but then there are some games that use .u3 and .u4 that require some sort of merge.

Since it's not really something that ares needs to support at this time, I'm closing it as not planned.
