### ISSUE TITLE
[NG] ADPCM-B is not yet implemented

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#795]
With the recent improvements in neo geo core, some game already is playable. But the sounds need improvements as there's a part of the sound chip not yet implemented.

**Comment by LukeUsher** [comment]
> Before submitting an issue, please use the search to make sure an issue doesn't already exist.
> 
> **Describe the issue** With the recent improvements in neo geo core, some game already is playable. But the sounds still need some improvement in all games tested.

innaccurate is a bad description here: there's an entire part of the sound chip that is not emulated yet, which naturally is a known issue because we haven't built it yet.

**Comment by Shideravan** [comment]
> > Before submitting an issue, please use the search to make sure an issue doesn't already exist.
> > **Describe the issue** With the recent improvements in neo geo core, some game already is playable. But the sounds still need some improvement in all games tested.
> 
> innaccurate is a bad description here: there's an entire part of the sound chip that is not emulated yet, which naturally is a known issue because we haven't built it yet.

Alright. I changed the description to reflect this.

**Comment by LukeUsher** [comment]
Fixed in 1b1e7f8f2ce5d6d464dded9fed6e72d6096a1519
