### ISSUE TITLE
[MD] ESPN Sunday Night NFL (U): The game stop to respond to the commands in heads or tails screen

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#798]
The game doesn't advance after this screen.

**Describe the issue**
When you go to this screen, the game doesn't respond anymore

**Rom Information**
Specify the impacted rom filename and any associated hashes (sha256 preferred)

```
Name: ESPN Sunday Night NFL (U) [!].bin
Size: 2097152 bytes (2048 KiB)
SHA256: cb4dcf1bd44d9a511bce99dd42ac9509808c3ec74a59d7e6ccb5756fd26b41e1
```
![image](https://user-images.githubusercontent.com/12163923/192682687-8fcb8ffc-590c-4c92-b057-c91fe670e6f7.png)

**Comment by BiZkViT96** [comment]
If the second controller is connected, the game expects PvP. Unplug the second controller.
![2022-09-28 13_02_22-ESPN Sunday Night NFL (USA)](https://user-images.githubusercontent.com/88586431/192700975-eeeb945d-7929-4bf0-8b6e-817706a208c6.png)

**Comment by Shideravan** [comment]
> If the second controller is connected, the game expects PvP. Unplug the second controller. ![2022-09-28 13_02_22-ESPN Sunday Night NFL (USA)](https://user-images.githubusercontent.com/88586431/192700975-eeeb945d-7929-4bf0-8b6e-817706a208c6.png)

This is a very weird behavior for a game. Anyway, if it's a behavior that happens on real hardware, then this issue can be closed.
