### ISSUE TITLE
[MD] Ballz: Sprite flickering

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#799]
**Describe the issue**
In the fight, when some moves are performed, some sprites may flick.

**Rom Information**
Specify the impacted rom filename and any associated hashes (sha256 preferred)

```
Name: Ballz (UE) [!].bin
Size: 2097152 bytes (2048 KiB)
SHA256: 7a303995125b6c301bce4f9b8ffbce3afb2548537e65559e8f667b93483770a6

```

**Comment by LukeUsher** [comment]
I don't think this is a bug, it looks like the game is just hitting the megadrive sprite limit; all footage of this game that I can find shows the same issue.

**Comment by LukeUsher** [comment]
confirmed not a bug; the game just hits the sprite limits of the hardware, confirmed in varous youtube videos + testing on other emulators known to be accurate.
