### ISSUE TITLE
[A26] Spider Fighter (USA): Screen shakes when you shoot

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#805]
Before submitting an issue, please use the search to make sure an issue doesn't already exist.

**Describe the issue**
The screen is shaking when you fire your weapon.

**Rom Information**
Specify the impacted rom filename and any associated hashes (sha256 preferred)

```
Name: Spider Fighter (USA).a26
Size: 4096 bytes (4 KiB)
SHA256: 423277fa64aad16916e6992ed82d8cd72dabdda080b625cb169abbcceb14f203
```
Ares b9cd02ddee07579b33b816b5c3a2ef77726e1abe

**Comment by LukeUsher** [comment]
This is common on many atari 2600 games; but weather you see it or not depends on what display you're using.
The hardware doesn't generate a TV sync signal, the games have to do so themselves, and sometimes, the games miss the vblank window slightly causing the display to wobble.

Real hardware verification would be nice but this is most likely not a bug.

**Comment by Shideravan** [comment]
I checked some captures of Spider Fighter, but in none of them this kind of shaking happens in this game
https://www.youtube.com/watch?v=K99Z5GdhVCQ
https://www.youtube.com/watch?v=2IDviUEVER0

The game's commercial: https://www.youtube.com/watch?v=WDHTtq2sOwk

**Comment by Shideravan** [comment]
The problem with screen shaking is solved at [pp](https://github.com/ares-emulator/ares/commit/8ae96164ef823d14e75a05dbdcdbb3e2537c037e).
There's an issue with "Copyright 1983" and "Activision" logo, but seems better to open a new issue about this.
