### ISSUE TITLE
[AES] Kizuna Enconter: Graphical errors

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#818]
**Describe the issue**
Most of game's sprite are messy

**Rom Information**
Specify the impacted rom filename and any associated hashes (sha256 preferred)

```
Name: kizuna.zip
Size: 18364080 bytes (17 MiB)
SHA256: 95773b40b1135caf8ffa86d09dbd5839b9e3b23d74a852f66fa01caf86bde0cd

```
![image](https://user-images.githubusercontent.com/12163923/193358166-dbfbcc0e-2317-49ca-a571-5ceec70c3516.png)
ares v130

**Comment by LukeUsher** [comment]
Fixed in recent Neo geo work
