### ISSUE TITLE
[NG] Fatal Fury 3: Bank error before start the fight

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#819]
**Rom Information**
Specify the impacted rom filename and any associated hashes (sha256 preferred)

```
Name: fatfury3.zip
Size: 21150034 bytes (20 MiB)
SHA256: f1752cc1acbc0a0eb1aaa77244218e9565715653547d69ade7c3019b0feb4f23
```
![image](https://user-images.githubusercontent.com/12163923/193357717-14c5328e-7daa-45b9-8e52-0315f63d10a8.png)
ares v130

**Comment by remutro** [comment]
@Shideravan Please note that this core is still marked as experimental. And please check the compatibility database (here: https://ares-emu.net/compatibility/25 ). All games have already been checked and status known. No need to open a unique issue for games with KNOWN problems and flood the issues list at this time.

If you find a new issue not reflected in our database, then that is OK. Please note there is a meta issue with scaling and gridlines appearing. It's known (and reflected in notes for games). 

And don't expect to find MVS ONLY releases in the AES list, or prototypes (biggest problem here is file naming). MVS currently DOES NOT WORK in Ares.

**Comment by Shideravan** [comment]
Ok, I'll not open an issue. Then please update all the compatibility lists with the latest ares version.

**Comment by remutro** [comment]
Just a note - version numbers don't automatically get bumped, unless set to "nightly", at which point when the next release is cut they are automatically set to the new release. But version numbers across the board don't increase unless someone has actually tested with the new release. All these processes are actively discussed on the Discord.
