### ISSUE TITLE
Unable to build on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by freq-mod** [higan-emu/ares#825]
**Describe the bug**
It may be the problem of OpenSUSE being OpenSUSE, rather than an actual problem with ares, but I'm stuck at this point - compilation hangs at 
```

In file included from ../hiro/core/core.cpp:8,
                 from ../hiro/hiro.cpp:5:
../hiro/core/../gtk/header.hpp:34:12: fatal error: cairo.h: No such file or directory
   34 |   #include <cairo.h>
      |            ^~~~~~~~~
compilation terminated.
```

So, cairo-devel is missing? Wrong - cairo-devel has been installed. Inspection of /usr/include/cairo proves that cairo.h is present on a system: 
![Przechwycenie obrazu ekranu_2022-10-04_10-12-23](https://user-images.githubusercontent.com/32672779/193769087-8815379b-abd1-46ee-bc1e-de3d20664652.png)

**Comment by LukeUsher** [comment]
Are you attempting to build with GTK2 or GTK3?

If gtk2, can you check the output of `pkg-config --cflags gtk+-2.0`, the path to cairo should be included in the output/
If gtk3, you should compile with `make hiro=gtk3` otherwise it will be assuming you're using gtk2

On my system the output of `pkg-config --cflags gtk+-2.0` is the following

```
-pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16
```

**Comment by freq-mod** [comment]
OK, turns out installing gtk-2.0-0 wasn't the right package, gtk2-devel was the one missing. Now ares compiles and works, thanks for the hint!
