### ISSUE TITLE
AUR ares-emu-git package: no sound and auto fast forward

### ISSUE THREAD

**Issue by freq-mod** [higan-emu/ares#826]
**Describe the bug**
Decided to test ares on Garuda Linux, installed https://aur.archlinux.org/packages/ares-emu-git and it doesn't work as intended:

-there is no sound at all (for ten times I started the program, once "failed to open audio device" appeared, then it didnt occur)
- Rock Man X2 runs at some sort of fast forward I can't disable with any hotkey; 75-93 FPS. The game is playable, though
- Various messages appear in console like: "Failed to load module "appmenu-gtk-module" or 

**Expected behavior**
Under openSUSE, locally built program functions 100% as intended.

**Comment by LukeUsher** [comment]
The high speed is directly related to the lack of working sound: audio is used to synchronise the emulation to the correct speed.

Having libao and openal as dependeneis means this situation should never occur though: something weird is going on.
What audio drivers are available in the settings pane?

**Comment by freq-mod** [comment]
For some reason, the audio device was set to none. After changing it to ALSA, it started working. So, perhaps the issue was that AUR package was set to none as default?
