### ISSUE TITLE
[Master System] Shaking screens with Zaxxon 3-D (World)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#828]
Emulator : Ares 1.30.1
Nightly build 2022-10-04 22:04:32 UTC
Options : Default
Game : Zaxxon 3-D (World)
System : Master System

Shaking screen from left to right.

![zaxxon](https://user-images.githubusercontent.com/12481242/193949833-264a143b-c785-455a-8f54-e593422f5c59.gif)

**Comment by Shideravan** [comment]
I think this is caused by the way the Sega Master System's 3D glasses work. Note that this is common in all 3D mode games that are compatible with the 3D glasses.
In Zaxxon, to "solve" just press start on the title screen and select 2D mode on the mode selection screen.

**Comment by LukeUsher** [comment]
Not a bug but just 3D games working as expected. 

They alternate between frames focused for your left eye, then your right eye. 

The glasses contain a shutter that rapidly opens and closes each frame, so the correct eye sees the correct frame. 

This is the exact behaviour of real hardware if you are not wearing the sega 3D glasses.
