### ISSUE TITLE
[MS] OutRun (UE): The game doesn't run (the core will show only the bios)

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#829]
**Describe the issue**
After load the file, the core shows the bios instead of the game.
![image](https://user-images.githubusercontent.com/12163923/193962761-04fe1b99-f49d-47b4-bd2d-52b36b449a66.png)

**Rom Information**
Specify the impacted rom filename and any associated hashes (sha256 preferred)

```
Name: OutRun (UE) [!].sms
Size: 262656 bytes (256 KiB)
SHA256: 67733680cbf0ee7a669a955f142f5d5d0f3fac16c59ecf36b101dfd07d57da14
```
ares v130.1

**Comment by Shideravan** [comment]
Other dump, namely:

```
Name: Out Run (World).sms
Size: 262144 bytes (256 KiB)
SHA256: 069c130135d8b61393d89f26b233509d6f9de76b0fbac53087e698a7fda0ba88
```
Runs normally

**Comment by LukeUsher** [comment]
what naming scheme/database are your roms verified against? No-Intro database not contain a rom named OutRun (UE). Is there a chance it could be a bad dump?

Only the following are known, valid Outrun roms for the Master System
[OutRun (World)](https://datomatic.no-intro.org/index.php?page=show_record&s=26&n=0258)
[OutRun Europa (Europe, Brazil) (En)](https://datomatic.no-intro.org/index.php?page=show_record&s=26&n=0260)
[OutRun 3-D (Europe, Brazil) (En)](https://datomatic.no-intro.org/index.php?page=show_record&s=26&n=0259)
[OutRun 3-D (Europe, Brazil) (En) (Beta)](https://datomatic.no-intro.org/index.php?page=show_record&s=26&n=0626)

**Comment by LukeUsher** [comment]
Update: I did manage to find a rom that matches your hash; but it is not part of no-intro, and on examining in a hex editor it is definitely a bad dump

It is 0x200 bytes too large, which means it has a non-standard header or footer and is not a clean dump from a real cartridge; which is why ares doesn't recognise it.

To avoid wasting our time, PLEASE verify your roms against no-intro or redump databases before submitting bug reports. 

This rom would not boot on a real Sega Master System with a flash cart either.

**Comment by Shideravan** [comment]
FYI: This dump is part of GoodSets and was checked with GoodTools, which list this as a valid dump.
Another name variation is:
```
Name: OutRun (UJEB) [!].sms
Size: 262656 bytes (256 KiB)
SHA256: 67733680cbf0ee7a669a955f142f5d5d0f3fac16c59ecf36b101dfd07d57da14
```
This probably using a different header.
Most of GoodSet roms works fine with ares tho.

**Comment by LukeUsher** [comment]
That doesn't mean it's correct: I found the rom matching these hashes and manually inspected it with a hex editor, it is 100% a bad dump

GoodTools is massively out of date and can't really be trusted.

It may work with other emulators if they detect the 512 byte header and remove it; but fixing badly dumped roms automatically is outside of the scope of the project.

Note that the [!] marker in GoodTools doesn't mean it is a valid dump, it also doesn't mean it's not a bad dump, just that it was *thought* to be a good dump at the time it was being checked.

There are a lot of bad and broken roms in GoodTools sets.

**Comment by Shideravan** [comment]
Good to know. I will get rid of them to avoid false positives.

**Comment by LukeUsher** [comment]
To be specific: the 512 byte header was added by older dumping tools, such as the "Super Magic Drive", it is not part of the original cartridge and should not be included in any rom dumps.

It is only required for playing games using a Super Magic Drive copier device and serves no other purpose.

The Super Magic Drive is a mega drive copier; but it uses this special header to detect if it needs to switch to SMS mode.
