### ISSUE TITLE
[Request] Master System FM Sound support

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#830]
**Describe the solution you'd like**
Master System has support for FM sound (released in Japan only, but compatible even with some western releases).
Would be good to has an option to switch between PCM (default) and FM sound.

**Additional context**
There's an add on for the Sega MarkIII
https://segaretro.org/FM_Sound_Unit

Japanese Master System had FM Unit built in
![image](https://user-images.githubusercontent.com/12163923/193964036-14bd58ac-bd5d-4696-9518-383ce820e87e.png)
https://segaretro.org/Sega_Master_System

**Comment by LukeUsher** [comment]
FM is already fully supported, but just like real hardware it only works on the Japanese region, and only for games that support it. 

If you set the ares region to “prefer Japanese” fm hardware will be present always. 

Otherwise we attempt to detect Japanese roms and emulate the correct hardware
