### ISSUE TITLE
[FC] Namco 163 expansion audio not implemented

### ISSUE THREAD

**Issue by freq-mod** [higan-emu/ares#832]
**Describe the issue**
This bug most likely affects all games utilizing Namco's N163 mapper, although I only tested MT2. Namco 163 provides up to 8 wavetable sound channels in addition to Famicom's built-in PSG. However, in ares, no expansion audio can be heard, only FC's PSG. It's odd, cosidering VRC6, VRC7 and 5B seem to work as intended.

**Rom Information**

```
file: Digital Devil Story - Megami Tensei II (Japan).nes
sha256: da319d0b060b1f5a63d3996b10fd3e05b4af8eab48809364451689c30cf1e6e5
```

**Comment by LukeUsher** [comment]
Not so much a bug as a missing feature: ares's emulation for Namco 163 does not implement the board variants that contian expansion audio. 

N163 has 128-bytes of internal memory, which can either be used as battery backed ram, or as expansion audio. Ares only implements the former configuraton at present.
