### ISSUE TITLE
[MS] Desert Speedtrap: Sometimes you can't get more collectables after loadstate

### ISSUE THREAD

**Issue by Shideravan** [higan-emu/ares#841]
**Describe the issue**
When you save and loadstate, sometimes you can't grab stars anymore
![image](https://user-images.githubusercontent.com/12163923/194934702-0e535198-c110-413e-be31-fe40bcfe7db1.png)

**Rom Information**
Specify the impacted rom filename and any associated hashes (sha256 preferred)

```
Name: Desert Speedtrap Starring Road Runner and Wile E. Coyote (Europe, Brazil) (En,Fr,De,Es,It).sms
Size: 262144 bytes (256 KiB)
SHA256: eef6c62696aedc9c775d591a34c3393e2db23f369c69dfde6ed26e9f402fedf9
```
ares v130.1

**Comment by Shideravan** [comment]
It's even possible to further glitch the game using save/load states
![image](https://user-images.githubusercontent.com/12163923/194935377-1a913201-8b85-41c4-89bf-2deb3ecd7374.png)

**Comment by FitzRoyX** [comment]
It might be worth noting that this game did something among MS games that caused some unique graphical issues, and it was fixed in ares_v120wip10:

"latch VDP background nametable address and scroll registers [fixes Desert Speedtrap]"
