### ISSUE TITLE
[FC] Suikoden - Tenmei no Chikai (J): graphics corruption at times ETROM

### ISSUE THREAD

**Issue by FitzRoyX** [higan-emu/ares#846]
This is basically a report for encoded-byte who just improved ExROM, and who I have no other way of contacting.

![Suikoden - Tenmei no Chikai (Japan) 2022-10-10 19-21-21](https://user-images.githubusercontent.com/57089001/195244949-4189b517-db39-48a5-a050-d691f6317ba5.png)
![Suikoden - Tenmei no Chikai (Japan) 2022-10-10 19-23-26](https://user-images.githubusercontent.com/57089001/195244955-ad734e44-d1c3-4cae-8d1d-e1a884fcffbd.png)
![Suikoden - Tenmei no Chikai (Japan) 2022-10-10 19-28-01](https://user-images.githubusercontent.com/57089001/195244958-62198563-27bb-4396-ae40-108b2877c47a.png)

**Comment by encoded-byte** [comment]
Thanks for testing and reporting. Yes, it seems that scanline detection is not perfect yet, I will look into fixing it. I'm on discord now.
