### ISSUE TITLE
[MegaDrive] Sonic 3 & Knuckles: Oddly Pitched Audio

### ISSUE THREAD

**Issue by Jaklyy** [higan-emu/ares#858]
Tried playing sonic 3 on ares and noticed some odd pitches and audio in the sfx and music, most notably the roll sound (roll sound issue also applies to sonic 1 and 2)
(could potentially be due to model differences in what ares emulates vs what most emulators/official releases base their audio off of, I'm not aware of the differences between each model, and whether that could be the reason why the audio sounds off to me)

Using the v130.1 release of Ares (though i tested on latest commit and noticed the same issue) and the latest nightly build of blastem for the comparison, blastem chosen simply due to being on hand and sounding "right" compared to what im used to.

Roll Sound: Blastem (right) first, Ares (left) second.

https://user-images.githubusercontent.com/102590697/197631008-ec0f705b-1ecd-451e-b099-4ba542a08687.mp4

Ares sound much higher pitched and more like a whine.

Knuckles breaking out of the ground: Ares (left) first, Blastem (right) second.

https://user-images.githubusercontent.com/102590697/197631612-b01662cf-f895-4f86-9f6f-10f1aa7215ad.mp4

Ares sounds slightly muffled.

Beginning of Special Stage theme: Blastem first video, Ares second.

https://user-images.githubusercontent.com/102590697/197632094-fc2a4ce6-a2f9-44ff-8299-a75ee1998c2f.mp4

https://user-images.githubusercontent.com/102590697/197634120-239d0a62-08b0-4d6b-9bad-bbe835272682.mp4

Ares sounds slightly twangier? It's like a silent part of the background is breaking out? Hard to describe.

End of Act Jingle: Blastem first video, Ares second.

https://user-images.githubusercontent.com/102590697/197634848-77a0e5d7-d7ad-4b72-975b-ab5b691071b0.mp4

https://user-images.githubusercontent.com/102590697/197634861-e5ec64d1-0805-41be-8740-578f39ac081e.mp4

Ares starts slightly too high pitched

**Rom Information**
Sonic_Knuckles_wSonic3.bin
![image](https://user-images.githubusercontent.com/102590697/197627095-383aaea5-3de7-4e62-a0c2-38db4c519e0b.png)
Rom sourced from the steam release of SEGA Mega Drive & Genesis Classics (which means Japanese Sonic 3 stitched onto International Sonic and Knuckles)

**Comment by HeroponRikiBestest** [comment]
Having compiled after the latest commit, this issue still seems to be the case. Comparing to real hardware, the roll does sound noticeably high-pitched, wheras other things (i.e. the spin dash) seem to be correct.

https://youtu.be/kFryKuCuA00?t=151

https://user-images.githubusercontent.com/50224630/228043088-b7ef83a5-6e18-4c0c-9ad3-def064b17666.mp4
