### ISSUE TITLE
SM83 instruction decode bug

### ISSUE THREAD

**Issue by raddad772** [higan-emu/ares#861]
SM83 instruction.cpp

switch(opcode.bit(6,7) << 3 | opcode.bit(0,2)) {

should be

switch(opcode.bit(6,7) >> 3 | opcode.bit(0,2)) {

**Comment by invertego** [comment]
The extracted bits are right shifted automatically. See here:
https://github.com/ares-emulator/ares/blob/c756ae6ea3fc8a953ca83c8fcafa2b6b98d65483/nall/primitives/bit-range.hpp#L162

**Comment by LukeUsher** [comment]
Correct, not a bug, just a misunderstanding on how ares' custom data types function.

**Comment by raddad772** [comment]
Ok, I hear that. However I think this kind of defeats the idea of clear code that is its own documentation. maybe put in a comment there saying the effect is the opposite of what is written?On Oct 26, 2022, at 4:08 AM, Luke Usher ***@***.***> wrote:﻿
Correct, not a bug, just a misunderstanding on how ares' custom data types function.
