### ISSUE TITLE
N64: Analog and Dpad Left/Down not working in macOS M1 (but Up/Right work)

### ISSUE THREAD

**Issue by suchipi** [higan-emu/ares#862]
**Describe the bug**
I have connected a Dualshock 4 controller to my M1 Macbook Air. I am able to assign inputs to it as expected via ares's configuration window. However, once I am in-game, pressing the inputs I have assigned to analog left and analog down do not move the character/cursor/etc as expected; it behaves as if I had not pressed the input at all.

**To Reproduce**
1. On an M1 macOS machine, such as the MacBook Air M1 2020:
1. Connect a Dualshock 4 controller to the system via bluetooth. To make the controller enter pairing mode, hold down the PS and Share buttons until the light starts flashing.
1. Open Ares. I used ares 130.1.
1. Click on 'ares' -> 'Preferences...'
1. Click on the 'Input' item in the list view on the left
1. Click the 'Virtual Gamepads' dropdown and change its value to 'Nintendo 64'.
1. Assign input mappings to L-Up, L-Down, L-Left, L-Right, A, and Start. I tried mapping these buttons to different combinations of analog axes, buttons, and POV hats, but the unwanted behavior was present in all cases.
1. Close the "Configuration" window
1. In the menu bar, click 'Load' -> 'Nintendo' -> 'Nintendo 64..."
1. Open a ROM; I used "Paper Mario (USA)". Mine was a .z64 file with md5 `a722f8161ff489943191330bf8416496`. From this point forward in the instructions, I will assume you are using the same game, but it should be possible to adapt these instructions to any game that uses L-Up, L-Down, L-Left, and L-Right.
1. Press the input you assigned to "Start" a few times to get past the intro and title screen.
1. At the file select screen, click on a file. It will ask you to input a name; a keyboard will appear.

**Expected behavior**
Pressing the inputs assigned to L-Up, L-Down, L-Left, and L-Right cause the pointer cursor to move Up, Down, Left, and Right, respectively.

**Actual behavior**
Pressing the inputs assigned to L-Up and L-Right work as expected, but pressing the inputs assigned to L-Left and L-Down have no apparent impact on the position of the cursor.

**Additional context**
I am using macOS Monterey 12.6. My system has 8GB of RAM. I am using ares v130.1, obtained from [ares-macos.zip in its GitHub release](https://github.com/ares-emulator/ares/releases/tag/v130.1). I moved the `ares.app` found therein to `/Applications` prior to launching it.

When the rom boots up, ares says "Vulkan Enabled: using paraLLEl-RDP"

I have verified that it is not an issue with the controller by using [Joystick Show](https://apps.apple.com/us/app/joystick-show/id515886877?mt=12). All inputs, axes, and hats are displayed in that app and show correctly.

**Comment by suchipi** [comment]
I have also encountered the same behavior with "Super Mario 64 (USA)", a z64 rom with md5 `20b854b239203baf6c961b850a4a51a2`.

**Comment by Screwtapello** [comment]
Can you post a screenshot of what the table of mappings looks like in the Preferences dialog after you've finished mapping things?

**Comment by suchipi** [comment]
Sure thing:
<img width="714" alt="Screen Shot 2022-10-28 at 9 40 54 PM" src="https://user-images.githubusercontent.com/1341513/198811863-317bc70f-934a-442a-8976-ff47a5701f2b.png">
<img width="718" alt="Screen Shot 2022-10-28 at 9 41 11 PM" src="https://user-images.githubusercontent.com/1341513/198811936-01c2d54a-3aa6-488d-a62b-176d095689be.png">

(Two screenshots cause I had to scroll down to see the rest.)

**Comment by jackhunter64** [comment]
I have noticed the same issue with a Steelseries Nimbus+ and a Switch Online replica N64 controller, on the current version of Ventura and the last version of Monterey.

**Comment by estefan3112** [comment]
Same here on a Mac M1 mini/Monterey with a wired PS4 Controller: analogue left and down do not work in N64 emulation. I tested the latest stable build, the nightly build and an own compile. Other Ares emulators just work fine so far.

**Comment by estefan3112** [comment]
Many thanks! Joypad works for me now in today's Nightly Build!
