### ISSUE TITLE
[UX] Feature to re-load the current ROM from disk (for homebrew/romhack development)

### ISSUE THREAD

**Issue by Reonu** [higan-emu/ares#870]
**Is your feature request related to a problem? Please describe.**
I make Super Mario 64 romhacks by using [HackerSM64](https://github.com/HackerN64/HackerSM64/). I try for all my hacks to be console compatible, but I'm constantly booting up my ROM in an emulator, and I only boot it up on console every once in a while to make sure everything is running fine. Therefore it's important for me for my emulator of choice to catch as many crashes and problems as possible. 

Up until now, I was using Parallel Launcher, but I've recently discovered how much more accurate Ares is in comparison, so I've switched to it. Parallel Launcher has a "Hard reset" button that re-loads the ROM from disk entirely, which is useful when iterating builds. I miss having a button like this.

**Describe the solution you'd like**
A button in the UI, and preferably a configurable keybind, to re-load the ROM from disk entirely. 

**Describe alternatives you've considered**
Maybe it would be cool to have an optional feature in where Ares is constantly checking if the currently running ROM has changed on disk and automatically re-loads it if so. In fact the more I think about it the more this sounds like an even better way to handle it.

**Additional context**

**Comment by LukeUsher** [comment]
Hotkey and menu option (Tools -> Reload Game) have been provided as of [69e5025](https://github.com/ares-emulator/ares/commit/69e5025e7a96feda96ca60303ae6c1580a771517)
