### ISSUE TITLE
Ares v130.1 Flatpak doesn't find installed shaders

### ISSUE THREAD

**Issue by Duckeenie** [higan-emu/ares#880]
I can see that the shaders are installed at /var/lib/flatpak/app/dev.ares.ares/x86_64/stable/mymountpoint/files/share/ares/Shaders but in the application the only entries in the shader menu are none and blur.

**Comment by LukeUsher** [comment]
We don't create/maintain the flatpak; you'd be better off creating an issue over at flathub: https://github.com/flathub/dev.ares.ares
