### ISSUE TITLE
clone cd images file support for cd based system

### ISSUE THREAD

**Issue by anonyme-x22** [higan-emu/ares#882]
**Is your feature request related to a problem? Please describe.**
Cannot load my clone cd of a pc engine cd

**Describe the solution you'd like**
Support of clone cd image at least for pc engine cd but if possible for all cd based system would be welcome

**Describe alternatives you've considered**
no alternative clone cd are the best one for cdda + data image files

**Additional context**

**Comment by LukeUsher** [comment]
We are not likely to add support for any proprietary/vendor specific formats. 

We already support bin/cue, which is preferred by redump as preservation quality, and chd which supports lossless compression.

**Comment by Screwtapello** [comment]
Also, last I heard CloneCD could be configured so that when imaging a disc, it would write out a CUE file alongside the IMG, CCD and SUB files, which would make it compatible with ares anyway.

**Comment by anonyme-x22** [comment]
Hi,

_We are not likely to add support for any proprietary/vendor specific formats.

We already support bin/cue, which is preferred by redump as preservation quality, and chd which supports lossless compression._

Yes it's a total non sense because img with the right cue already works, they just have a little job to natively support ccd. Img = Bin. 
Totally unbelievable! if its sentence were true ihe should also remove the bin cue support...
Img/Bin best preferred by redump as preservation quality (not only bin) 

I don't he realize what he is saying!
 
Rgds,

**Comment by Screwtapello** [comment]
I think most of the effort of ares' BIN/CUE support went into understanding CUE files, not BIN files. There's not much reason to also support CCD files, when the format is not notably better than CUE, and the only software that makes CCD files can also make a CUE file at the same time.

**Comment by anonyme-x22** [comment]
Yeah that's true but to make the cue if don't done before you need to redump the cd!
So adding CCD/Cue support is just more confortable especially that i'm now sure that a cue/img is 100% the same as a ccd/img.
