### ISSUE TITLE
Z80 LD_rr_inn should set WZ to addr+1

### ISSUE THREAD

**Issue by raddad772** [higan-emu/ares#885]
WZ should be (addr + 1) at the end of the function. so

auto Z80::instructionLD_rr_inn(n16& x) -> void { Q = 0;
  WZ = operands();
  x.byte(0) = read(WZ);
  WZ++
  x.byte(1) = read(WZ);
}

this will return the correct result.

**Comment by LukeUsher** [comment]
Do you have a source for this so we can verify it?

**Comment by raddad772** [comment]
Sorry. I was told this on the ZX Spectrum Discord server as a reason my emulator wasn't passing some real nitty-gritty tests. I report these to Ares because I partly ported a bunch of Ares logic for the Z80 core I use and a lot of the things I run into, apply back to Ares. I'll ask there if anyone has a source, but it's what you do to pass the same tests as a real Z80

**Comment by LukeUsher** [comment]
Thanks, if it passes tests I'll accept that as proof enough

**Comment by raddad772** [comment]
https://github.com/redcode/Z80/wiki/MEMPTR
here you go

**Comment by LukeUsher** [comment]
Fixed in 7c57dfa7bc4ac48ba4b35282ca6252cb671eb137
