### ISSUE TITLE
Z80 interrupted LDIR, CPIR, OTDR, etc. have wrong flags

### ISSUE THREAD

**Issue by raddad772** [higan-emu/ares#886]
Basically, when OTDR, LDIR, etc. are interrupted by either an interrupt or being overwritten, flags have certain values that are overwritten if it completes properly.

There's a little bit to it, and it's described in-depth here:
https://zxe.io/depot/documents/technical/Undocumented%20Z80%20Flags%20rev1.0%20%282018-08-21%29%28Banks%2C%20David%29%28en%29%5B%21%5D.pdf
[edit: updated URL]

**Comment by jeffythedragonslayer** [comment]
How did you discover that ares has this wrong?

**Comment by raddad772** [comment]
I semi-ported the Ares Z80 core to generate Z80 tests with in JavaScript.
My Z80 core passed all 1k tests per-opcode, and did not show this behavior.
The tests track the before, after, and per-cycle states of the Z80, so I knew that if my core passed the tests, the tests do not show the behavior.

I then updated my tests to show the behavior and put an Issue in with Ares, as I have done for many other things.

https://github.com/raddad772/jsmoo/blob/main/misc/code_generation/z80_test_generator.js

**Comment by raddad772** [comment]
Also, see
https://github.com/raddad772/jsmoo/tree/main/misc/tests/GeneratedTests/z80
for the output

**Comment by rasky** [comment]
Fixed by cff8b5531016a0d061a549fcc4e2296a5dc86b78
