### ISSUE TITLE
MacOS can't assign firmware

### ISSUE THREAD

**Issue by barcoboy** [higan-emu/ares#890]
Running the latest nightly version from 3 days ago on MacOS Ventura 13.0 on a MacBook Pro 16 inch 2019. 

Trying to assign the firmware for Colecovision emulation, when I hit the assign button in the Firmware settings page, I get the following message box:

The open file operation failed.
The open file operation failed to connect to the open and save panel service.

**Comment by jlawrence124** [comment]
+1 on this issue. M2 Macbook Air running Ventura

**Comment by LukeUsher** [comment]
This seems to be a widespread issue on macOS 12 and 13 for many applications, it looks like even python ran into it (see: https://bugs.python.org/msg403603)

It sounds like it is no longer valid to open a file dialog using `[NSOpenPanel runModal]`, and that `[NSApp runModalForWindow:panel]` must be used instead, see the relevant patch to python (https://bugs.python.org/file50343/openfile.patch)

Unfortunately, the newest macOS I have access to is Catalina, so we would need to wait for a developer with access to later macOS versions to fix and verify.

**Comment by jlawrence124** [comment]
Is there a config file that we can edit to change the firmware assignment in the meantime?

**Comment by remutro** [comment]
As a temporary workaround, you can manually add the path to your settings.bml file.

**Comment by barcoboy** [comment]
Tried this, but I'm still getting:

Error: firmware is missing or invalid.
Colecovision - BIOS (World) is required to play this game.
Would you like to configure firmware settings now?

Tried several different firmware downloads that said they were the official Colecovision BIOS files.

What is the name of the file supposed to be?  I see in settings.bml it has listed "BIOS.World", but even naming the file to that it does not work.

**Comment by remutro** [comment]
This is currently what I have defined for the ColecoVision in my settings.bml file:

```
ColecoVision
  Visible: true
    Path: D:/Coleco/Coleco - ColecoVision (20200926-011306)/
  Firmware
    BIOS.World: D:/Coleco/Coleco - ColecoVision (20200926-011306)/[BIOS] ColecoVision (USA, Europe).zip
```

This BIOS is from the No-Intro set (which is what Ares focuses on for cartridge/bios based files/hashes/names). 

Inside the zip file is a single file with the name "[BIOS] ColecoVision (USA, Europe).col"

The SHA256 hash of my *.col file is:    990bf1956f10207d8781b619eb74f89b00d921c8d45c95c334c16c8cceca09ad

**Comment by barcoboy** [comment]
Ah, that was my problem.  I wasn't specifying the path in the "BIOS.World:" parameter, but just the filename, because I thought it would use the one specified in the "Path:" parameter above it.  Once I copied and pasted the path into the "BIOS.World:" parameter, everything worked fine.

**Comment by shinra-electric** [comment]
Still an issue

<img width="965" alt="Screenshot 2023-02-14 at 17 41 10" src="https://user-images.githubusercontent.com/50119606/218805694-a0793948-d508-459f-a92c-daae38624b2a.png">
