### ISSUE TITLE
[GBC ] Pokemon Blue Version

### ISSUE THREAD

**Issue by voidflower-xcii** [higan-emu/ares#894]
This is a smaller bug, but I figured I'd point it out regardless. When loading Pokemon Blue Version under the GBC instead of the GB and playing with the default color palette given (red and blue), if you go to heal your Pokemon at a heal center the pokeballs are displayed as red/white when they should be blue/white, and they don't play their animation when they're healing (a sort of rapid fade between blue and white). Instead they remain static like the screenshot shown.

![Screenshot 2022-12-14 100023](https://user-images.githubusercontent.com/120467626/207646774-0d343d69-38f5-4f78-8600-708cf636d0cd.png)

I think this bug occurs on any color palette chosen. I'd need to double check.

File: Pokemon - Blue Version (USA, Europe) (SGB Enhanced).gb
CRC32: D6DA8A1A
MD5: 50927E843568814F7ED45EC4F944BD8B
SHA-1: D7037C83E1AE5B39BDE3C30787637BA1D4C48CE2

**Comment by LukeUsher** [comment]
ares does not fully support DMG mode on a GBC right now, so issues like this are expected; there are a lot of differences between a GBC in GBC mode, and a GBC in DMG mode which are not emulated at the moment.

Please play DMG games either using DMG emulation, or Super Gameboy emulation

**Comment by voidflower-xcii** [comment]
> Please play DMG games either using DMG emulation, or Super Gameboy emulation

Is there a specific way to play through Super Gameboy with Ares? I can't seem to get the game to launch. The SGB1 / SGB2 bios file paths are not listed under the firmware config.

**Comment by LukeUsher** [comment]
> > Please play DMG games either using DMG emulation, or Super Gameboy emulation
> 
> Is there a specific way to play through Super Gameboy with Ares? I can't seem to get the game to launch. The SGB1 / SGB2 bios file paths are not listed under the firmware config.

"Super Gameboy" is a snes game, so you would launch the Super Gameboy rom via the snes emulation, after which it will prompt you to attach a gameboy cartridge

Unlike most emulators, ares fully emulates the Super Gameboy, so all enhanced features work as expected, even Space Invaders; which is an interesting case of a gameboy cart containing a snes rom that gets uploaded when using a super gameboy.

**Comment by LukeUsher** [comment]
![image](https://user-images.githubusercontent.com/740003/207739416-4fe14358-767d-4368-b7b4-f99ef7aac1e8.png)
Should be resolved in the latest commit (c60f91e5d560a04a40a7a4b60a5550165b11288f) a new nightly build will be available shortly
