### ISSUE TITLE
[SFC] Sonic the Hedgehog (Homebrew/Port) 1UP Monitor Crash

### ISSUE THREAD

**Issue by ChromiusMixin** [higan-emu/ares#905]
**Describe the bug**
A bug within a homebrew port of Sonic the Hedgehog's Green Hill Zone act 3 that causes a crash upon breaking open a 1UP Monitor.

**To Reproduce**
1. Break open a 1UP monitor and let the 1UP jingle play.
2. Game will crash shortly after resuming invincibility jingle or Green Hill Zone BGM

**Expected behavior**
The game should simply continue as normal after the 1UP jingle plays.

**Footage**
[Video capture on Youtube](https://www.youtube.com/watch?v=u4vmHlnQz8M)

**Additional context**
This is a gameplay/audio-complete homebrew port of Sonic the Hedgehog's Green Hill Zone act 3 excluding the boss.
It includes fully functional item monitors, badniks, stage gimmicks and gameplay physics for Sonic as well as all audio associated with these gameplay elements.

**EDIT**
Game also crashes shortly after collecting 100 rings to get a 1UP. It's not specifically tied to the 1UP monitor.

**Comment by invertego** [comment]
I couldn't get this to repro at all. ChromiusMixin was able to repro at first, but after additional attempts it stopped occurring. Given that this is pretty much a tech demo, there is a strong possibility this is just a game bug.

**Comment by PeterSamuels** [comment]
Cannot reproduce either

**Comment by LukeUsher** [comment]
Could not reproduce
