### ISSUE TITLE
Sega GigaDrive, Mark V, TeraDrive, Amstrad Mega PC and Mega Plus

### ISSUE THREAD

**Issue by ReNardier** [higan-emu/ares#913]
https://en.wikipedia.org/wiki/Fantasy_video_game_console
https://game.watch.impress.co.jp/docs/interview/599091.html
https://game.watch.impress.co.jp/docs/interview/599346.html
https://game.watch.impress.co.jp/docs/interview/599347.html
https://game.watch.impress.co.jp/docs/interview/599434.html
translation https://web.archive.org/web/20131206004815/http://www.siliconera.com/2013/12/03/emulating-megadrive-3ds-isnt-easy-enter-3d-sonic-hedgehog
https://gbatemp.net/threads/research-m2s-3d-gigadrive-emulator.475800/
https://www.reddit.com/r/emulation/comments/yocnir/the_sega_mark_v_on_the_sega_genesis_mini_2/
https://en.wikipedia.org/wiki/Sega_TeraDrive
https://en.wikipedia.org/wiki/Amstrad_Mega_PC
i think that at least the gigadrive and the mark V could be nice

**Comment by LukeUsher** [comment]
Fantasy consoles that never actually existed will likely never be implemented, these are far outside of the scope of ares.

Implementing TeraDrive or MegaPC involves emulating an entire IBM PC, and not enough is known about the interaction between the MD and PC components to make it viable at this time.

I'll leave it open for now, but this is most likely a wontfix, at least for the considerable future.

**Comment by ReNardier** [comment]
i get think that linking that wikipeida article has been a mistake from my part, could you please read the siliconera article to see that the gigadrive isn't just some fanfiction machination?

**Comment by LukeUsher** [comment]
> i get think that linking that wikipeida article has been a mistake from my part, could you please read the siliconera article to see that the gigadrive isn't just some fanfiction machination?

GigaDrive hardware never actually existed, it's an fantasy more advanced model that M2 created for their 3D classics line.

**Comment by asiekierka** [comment]
## GigaDrive/Mark V

The problem with emulating something like the "Gigadrive" is that, technically speaking, you need to also emulate all the bugs and timing differences in the M2 emulator, if any, which don't correspond to a new console. It's not really bolting on some registers to a Mega Drive emulator - not if you want to accurately emulate the Gigadrive ;-)

As such, I feel the effort to emulate the Gigadrive inaccurately is not worth it, and emulating it accurately would essentially necessiate an entirely new emulator. This also applies to the "Mark V" - an emulator which adds "Mark V" features to an accurate Mega Drive core would *not* necessarily be an accurate "Mark V" emulator.

## TeraDrive

This would be very interesting to emulate, but Ares would need to gain Intel 80286 and PC hardware emulation first.

## Amstrad Mega PC

Not worth it - the Mega Drive and PC components only share the monitor and speakers; it's essentially equivalent to running a PC emulator and Mega Drive emulator simultaneously, to use that analogy.

**Comment by LukeUsher** [comment]
Closing as wontfix

**Comment by Kawa-oneechan** [comment]
So much for A3X support lol
