### ISSUE TITLE
Sega CD / Mega CD - All roms FREEZE after loading

### ISSUE THREAD

**Issue by Relat1v1ty** [higan-emu/ares#914]
**Describe the bug**

_For Sega CD / Mega CD roms - they never load, they only freeze after the BIOS runs and the "SEGA" logo with Sonic animates.
This happens regardless of which SegaCD/MegaCD BIOS you use._

**To Reproduce**
_1. Go to 'Load'
2. Mouse on 'Sega' > 'Mega CD'
4. Load any Sega CD Rom (in this case, in .Cue format)_

**Expected behavior**

•The BIOS will run with music. You may press 'Start' here, or simply wait.
•The Sega logo with Sonic shooting stars on it will animate with the Sega sound bite, but then the game will freeze at this point, always.

**Screenshots**

_•The BIOS will run with music. You may press 'Start' here, or simply wait._
![image](https://user-images.githubusercontent.com/121585717/209885100-969c9a3a-9f26-4cd8-a7d7-26fbd80a3e50.png)

_•The Sega logo with Sonic shooting stars on it will animate with the Sega sound bite, but then the game will freeze at this point, always._
![image](https://user-images.githubusercontent.com/121585717/209885166-1c38ba37-2ded-4fbb-ad6b-ddcf12e27f8a.png)

**Additional context**

_•This happens with every SegaCD ROM I try.
•I tried various SegaCD USA BIOS, always properly setup in the Firmware section of the Ares Emulator (USA BIOS in the USA BIOS section, etc.).
•UPDATE: Some exceptions (including the game Snatcher), where it will actually pass the Sega logo by almost 1 second into the game initial credits screen, but THEN freeze._

**Comment by voidflower-xcii** [comment]
I'm unable to replicate this. 

![Screenshot 2022-12-30 030215](https://user-images.githubusercontent.com/120467626/210056117-4024259b-2df4-47bd-9c90-38c9024d0369.png)

I also double checked with the JPN and EU bios and they boot games properly too. You need to use the v2.00 bios I believe, but it would seem you're doing that already? All three of the ones I have are in .bin format. My only guess would be a bad bios?

Here is the hash for the (U) bios I'm using.
MD5: ECC837C31D77B774C6E27E38F828AA9A
SHA-256: 4ACDA6CED2951F4FC34B42CC08C7510B8EDC1F716B17CE4F84920751A98B9204

**Comment by remutro** [comment]
I haven't been able to reproduce this either. I don't have this particular game, but I tested a few like Sonic CD and Popful Mail and they worked just fine. We actually have a tester starting to work through the Mega CD library right now and they haven't reported an issue like this.

**Comment by Relat1v1ty** [comment]
Thanks for all your help, fellows, but I'm still running into trouble, even when trying on a different computer (laptop instead of my normal desktop).
I've been fighting with this today when I had time, trying other BIOS files, and trying some other ones that I found, including one with the same hash MD5: ECC837C31D77B774C6E27E38F828AA9A.
An example: when I run Lunar: The Silver Star, the first couple of splash screens do show, but it then freezes after the 2nd one (below).

Could there be another setting I'm missing? I left all settings at default, just adding the Sega CD BIOS file for US. I also tried adding BIOS files for all 3 regions (US, JAP, EU), this did not help. Could there be something I'm overlooking?

Note: This does not happen on other emulators that I've tried, but naturally, it's Ares I am most interested in, not the others.

![image](https://user-images.githubusercontent.com/121585717/210122426-fdfd00d1-005c-4c78-bab1-af1ef713d5e9.png)
![image](https://user-images.githubusercontent.com/121585717/210122435-a2d5cf94-491a-46d1-9d63-b0d876cd4466.png)
![image](https://user-images.githubusercontent.com/121585717/210122410-2e7d392b-85f1-4e85-ad97-52f8156538aa.png)

**Comment by remutro** [comment]
Hmm... I just tried Silver Star and it worked fine. I watched all the intro videos and got at least as far as adding Luna to my party and opening the chest in the basement. Based on where it is freezing for you, it looks like it can't proceed with playing the video/animation parts, does that sound right to you? I also checked Snatcher and it goes in-game without issue as well. What OS are you running, and what do you have for a CPU?
![lunar](https://user-images.githubusercontent.com/84990500/210141455-4da6711c-6e47-4ac6-a311-05b5de95038a.png)

**Comment by LukeUsher** [comment]
Silver Star is known to have issues if audio tracks are incorrectly formatted. This impacts backup copies on real hardware too. 


If you’re using a bin/cue make sure all the filenames listed in the cue sheets are correct, perhaps verify all the cue metadata including pregaps, etc against redumps example cuesheets.

**Comment by remutro** [comment]
In my instance, Silver Star is a single *.bin file, with the *.cue file indicating that the data track comes first, and then there are about 51 audio tracks after that start roughly about 1 hour 12 minutes into the *.bin file. I don't have multiple files for each track.

**Comment by Relat1v1ty** [comment]
Hello again,
My apologies for the delays in getting back to you, and I say thank you for your time and attention, in earnest.

You are absolutely right, it does appear that the video/animation specific parts are the issue for me, indeed.
To answer your question, the OS I'm currently using is Windows 10 Pro (legally activated), and my CPU details are conveyed below:
![image](https://user-images.githubusercontent.com/121585717/210157448-d99a14be-6a9e-4763-ada2-d3d4a0bb4ad1.png)

It also does appear that the cue file I'm using with my bin ROM image is also correct, audio tracks starting about 1 hour and 12 minutes into the single bin file:

![image](https://user-images.githubusercontent.com/121585717/210157461-0fa71a8e-c3b4-4a73-97ca-225defbe8714.png)

I've also tried a different ROM of the same game, where each audio track is it's own bin file, and I'm still running into the same issue, it freezes as it tries to play video/animation:

![image](https://user-images.githubusercontent.com/121585717/210157585-a5748320-f272-42e7-9ce0-582c39a2d803.png)

Please forgive my ignorance (I hope not to cause anyone any inconvenience); do different CPUs have an effect on emulators running OK?

**Comment by remutro** [comment]
Your cue file matches mine for the single *.bin version, so that seems to be OK. I only asked about CPU because if it were old enough (like 10+ years) then it is possible there may be features the emulator relies on that weren't present at the time. But you have a very recent CPU, so that shouldn't be it. 

I'm kind of stumped. Hoping someone else has a few more ideas here. Not sure what else could interfere with playing videos, but I'll try to research this a little bit more.

Edit: What drivers do you have selected in Settings > Drivers in Ares?

**Comment by voidflower-xcii** [comment]
Well, I decided to try testing a few more games and I can now say the same problem applies to me as well. Sonic CD for example is freezing at the Sega screen as described. Snatcher gets past it and freezes at the copyright screen. I even have the same problem with Lunar where it hangs on a black screen after the title fade.

What's really odd is I haven't had a chance to sit at my computer the past few days as I've been sick. This is leading me to wonder if perhaps something outside of ares could potentially be affecting it, like perhaps a Windows update or nVidia driver update? I'm usually always using the latest nightly.

Edit: I decided to check all my bios files for the hell of it, and... I found one that works for me. @Relat1v1ty perhaps you can try this one if you haven't already? The other v2.00 bios I have doesn't want to work.

Sega CD (U) - Model 2 v2.00w (1993).bin
SHA-256:	B1C2036B79467514EAAA69C76E5BA83801621E821059CAA53CB921A0B21E3AF4

**Comment by Relat1v1ty** [comment]
Hi @voidflower-xcii,
Your solution did the trick!
I was wondering if I was the only person in the world to experience this issue, it's great to see the issue actually can be replicated and solved.

You are right, running BIOS Sega CD (U) - M2 v2.00w.bin is the only BIOS (so far) that will allow SegaCD videos to not halt the emulator.

Can this be conveyed as a known issue? Do you feel Ares will support other BIOS versions in the future?


Happy new year, everyone, here's to a great 2023!
![image](https://user-images.githubusercontent.com/121585717/210183224-041b3e3a-bc87-4814-a4e5-6da73ab20221.png)

**Comment by remutro** [comment]
That's weird, but I'm glad you got it working. For the record, I'm using the following BIOS and don't have any problems:

Sega CD 2 (USA) (v2.00).md
SHA256: fb477cdbf94c84424c2feca4fe40656d85393fe7b7b401911b45ad2eb991258c
