### ISSUE TITLE
[Mega 32x] Knuckles Chaotix's PWM drums are too quiet in Ares v131

### ISSUE THREAD

**Issue by ghost** [higan-emu/ares#919]
**Describe the issue**
Basically, in the latest version of Ares, the PWM drums of Knuckles Chaotix play in a significantly lower volume than in real hardware, sometimes being almost inaudible. I'm providing a example of the bug in action along with an actual hardware recording i found on YouTube to provide info about how it should sound like.

Example of the bug:

https://user-images.githubusercontent.com/104454752/210138588-b34524b2-78ea-4baa-a371-5d638bf362cc.mp4

Actual hardware recording:

https://www.youtube.com/watch?v=4_TlgFunnlQ
**Rom Information**
```
file: knuckles.32x
sha256: 70e1a92a982f2684be3bc315267e545fb9c530d533fd62b6d38bb625541ed957
sha1: 0c2fff7bc79ed26507c08ac47464c3af19f7ced7
```

**Aditional Information**
I'm using the Flatpak binary version of Ares v131 in PopOS 22.04.

**Comment by Yui12** [comment]
Issue seems to be fixed in v139 when I played the game.
