### ISSUE TITLE
Compilation issue v131

### ISSUE THREAD

**Issue by smileaf419** [higan-emu/ares#927]
I’m able to compile 130.1 with no issues via:
make -j5 hiro=gtk3

In v131 I get:
Compiling ares/n64/cpu/cpu.cpp ...
Compiling ares/n64/vulkan/parallel-rdp/parallel-rdp/command_ring.cpp ...
Compiling ares/n64/vulkan/parallel-rdp/parallel-rdp/rdp_device.cpp ...
Compiling ares/n64/vulkan/parallel-rdp/parallel-rdp/rdp_dump_write.cpp ...
Compiling ares/n64/vulkan/parallel-rdp/parallel-rdp/rdp_renderer.cpp ...
Compiling ares/n64/vulkan/parallel-rdp/parallel-rdp/video_interface.cpp ...
Compiling ares/n64/vulkan/parallel-rdp/vulkan/buffer.cpp ...
Compiling ares/n64/vulkan/parallel-rdp/vulkan/buffer_pool.cpp ...
Compiling ares/n64/vulkan/parallel-rdp/vulkan/command_buffer.cpp ...
Compiling ares/n64/vulkan/parallel-rdp/vulkan/command_pool.cpp ...
Compiling ares/n64/vulkan/parallel-rdp/vulkan/context.cpp ...
Compiling ares/n64/vulkan/parallel-rdp/vulkan/cookie.cpp ...
Compiling ares/n64/vulkan/parallel-rdp/vulkan/descriptor_set.cpp ...
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:32:7: error: '__builtin_ia32_roundss' needs target feature sse4.1
  t = _mm_round_ss(t, t, _MM_FROUND_TO_POS_INF);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:281:12: note: expanded from macro '_mm_round_ss'
  ((__m128)__builtin_ia32_roundss((__v4sf)(__m128)(X), (__v4sf)(__m128)(Y),    \
           ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:43:7: error: '__builtin_ia32_roundsd' needs target feature sse4.1
  t = _mm_round_sd(t, t, _MM_FROUND_TO_POS_INF);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:356:13: note: expanded from macro '_mm_round_sd'
  ((__m128d)__builtin_ia32_roundsd((__v2df)(__m128d)(X), (__v2df)(__m128d)(Y), \
            ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:32:7: error: '__builtin_ia32_roundss' needs target feature sse4.1
  t = _mm_round_ss(t, t, _MM_FROUND_TO_POS_INF);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:281:12: note: expanded from macro '_mm_round_ss'
  ((__m128)__builtin_ia32_roundss((__v4sf)(__m128)(X), (__v4sf)(__m128)(Y),    \
           ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:43:7: error: '__builtin_ia32_roundsd' needs target feature sse4.1
  t = _mm_round_sd(t, t, _MM_FROUND_TO_POS_INF);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:356:13: note: expanded from macro '_mm_round_sd'
  ((__m128d)__builtin_ia32_roundsd((__v2df)(__m128d)(X), (__v2df)(__m128d)(Y), \
            ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:54:7: error: '__builtin_ia32_roundss' needs target feature sse4.1
  t = _mm_round_ss(t, t, _MM_FROUND_CUR_DIRECTION);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:281:12: note: expanded from macro '_mm_round_ss'
  ((__m128)__builtin_ia32_roundss((__v4sf)(__m128)(X), (__v4sf)(__m128)(Y),    \
           ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:65:7: error: '__builtin_ia32_roundsd' needs target feature sse4.1
  t = _mm_round_sd(t, t, _MM_FROUND_CUR_DIRECTION);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:356:13: note: expanded from macro '_mm_round_sd'
  ((__m128d)__builtin_ia32_roundsd((__v2df)(__m128d)(X), (__v2df)(__m128d)(Y), \
            ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:54:7: error: '__builtin_ia32_roundss' needs target feature sse4.1
  t = _mm_round_ss(t, t, _MM_FROUND_CUR_DIRECTION);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:281:12: note: expanded from macro '_mm_round_ss'
  ((__m128)__builtin_ia32_roundss((__v4sf)(__m128)(X), (__v4sf)(__m128)(Y),    \
           ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:65:7: error: '__builtin_ia32_roundsd' needs target feature sse4.1
  t = _mm_round_sd(t, t, _MM_FROUND_CUR_DIRECTION);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:356:13: note: expanded from macro '_mm_round_sd'
  ((__m128d)__builtin_ia32_roundsd((__v2df)(__m128d)(X), (__v2df)(__m128d)(Y), \
            ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:76:7: error: '__builtin_ia32_roundss' needs target feature sse4.1
  t = _mm_round_ss(t, t, _MM_FROUND_TO_NEG_INF);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:281:12: note: expanded from macro '_mm_round_ss'
  ((__m128)__builtin_ia32_roundss((__v4sf)(__m128)(X), (__v4sf)(__m128)(Y),    \
           ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:87:7: error: '__builtin_ia32_roundsd' needs target feature sse4.1
  t = _mm_round_sd(t, t, _MM_FROUND_TO_NEG_INF);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:356:13: note: expanded from macro '_mm_round_sd'
  ((__m128d)__builtin_ia32_roundsd((__v2df)(__m128d)(X), (__v2df)(__m128d)(Y), \
            ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:76:7: error: '__builtin_ia32_roundss' needs target feature sse4.1
  t = _mm_round_ss(t, t, _MM_FROUND_TO_NEG_INF);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:281:12: note: expanded from macro '_mm_round_ss'
  ((__m128)__builtin_ia32_roundss((__v4sf)(__m128)(X), (__v4sf)(__m128)(Y),    \
           ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:87:7: error: '__builtin_ia32_roundsd' needs target feature sse4.1
  t = _mm_round_sd(t, t, _MM_FROUND_TO_NEG_INF);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:356:13: note: expanded from macro '_mm_round_sd'
  ((__m128d)__builtin_ia32_roundsd((__v2df)(__m128d)(X), (__v2df)(__m128d)(Y), \
            ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:7:7: error: '__builtin_ia32_roundss' needs target feature sse4.1
  t = _mm_round_ss(t, t, _MM_FROUND_TO_NEAREST_INT);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:281:12: note: expanded from macro '_mm_round_ss'
  ((__m128)__builtin_ia32_roundss((__v4sf)(__m128)(X), (__v4sf)(__m128)(Y),    \
           ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:21:7: error: '__builtin_ia32_roundsd' needs target feature sse4.1
  t = _mm_round_sd(t, t, _MM_FROUND_TO_NEAREST_INT);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:356:13: note: expanded from macro '_mm_round_sd'
  ((__m128d)__builtin_ia32_roundsd((__v2df)(__m128d)(X), (__v2df)(__m128d)(Y), \
            ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:7:7: error: '__builtin_ia32_roundss' needs target feature sse4.1
  t = _mm_round_ss(t, t, _MM_FROUND_TO_NEAREST_INT);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:281:12: note: expanded from macro '_mm_round_ss'
  ((__m128)__builtin_ia32_roundss((__v4sf)(__m128)(X), (__v4sf)(__m128)(Y),    \
           ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:21:7: error: '__builtin_ia32_roundsd' needs target feature sse4.1
  t = _mm_round_sd(t, t, _MM_FROUND_TO_NEAREST_INT);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:356:13: note: expanded from macro '_mm_round_sd'
  ((__m128d)__builtin_ia32_roundsd((__v2df)(__m128d)(X), (__v2df)(__m128d)(Y), \
            ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:98:7: error: '__builtin_ia32_roundss' needs target feature sse4.1
  t = _mm_round_ss(t, t, _MM_FROUND_TO_ZERO);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:281:12: note: expanded from macro '_mm_round_ss'
  ((__m128)__builtin_ia32_roundss((__v4sf)(__m128)(X), (__v4sf)(__m128)(Y),    \
           ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:109:7: error: '__builtin_ia32_roundsd' needs target feature sse4.1
  t = _mm_round_sd(t, t, _MM_FROUND_TO_ZERO);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:356:13: note: expanded from macro '_mm_round_sd'
  ((__m128d)__builtin_ia32_roundsd((__v2df)(__m128d)(X), (__v2df)(__m128d)(Y), \
            ^
In file included from ../ares/n64/cpu/cpu.cpp:11:
../ares/n64/cpu/algorithms.cpp:98:7: error: '__builtin_ia32_roundss' needs target feature sse4.1
  t = _mm_round_ss(t, t, _MM_FROUND_TO_ZERO);
      ^
/usr/lib/clang/15.0.6/include/smmintrin.h:281:12: note: expanded from macro '_mm_round_ss'
  ((__m128)__builtin_ia32_roundss((__v4sf)(__m128)(X), (__v4sf)(__m128)(Y),    \
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
Compiling ares/n64/vulkan/parallel-rdp/vulkan/device.cpp ...
20 errors generated.
make[1]: *** [../nall/GNUmakefile:265: obj/ares-n64-cpu.o] Error 1

**Comment by Screwtapello** [comment]
Does it change if you add `local=true` or `local=false` after `hiro=gtk3`?

**Comment by remutro** [comment]
This error probably means your CPU is fairly old now, what do you have?
`error: '__builtin_ia32_roundss' needs target feature sse4.1`
This specific intrinsic was modified in this commit (in v131):  https://github.com/ares-emulator/ares/commit/fbc921ade9cc42505e3c0c7525b8e9d8b89c1c71

Screwtape's suggestion is a good one, make sure 'local=true' is specified at compile time. If it still fails, it's possible an additional guard against SSE 4.1 usage is needed/missing (similar to this commit: https://github.com/ares-emulator/ares/commit/50dd52bb47fca646a7cbd491aabb8b890de2ad5d).

If the problem can't be worked around at the moment, you could exclude the N64 core from compilation. It's probably easier to remove n64 from this line in desktop-ui/GNUmakefile:
`cores := a26 fc sfc n64 sg ms md ps1 pce ng msx cv gb gba ws ngp`
Although you can specify all cores you do want at compilation time, just a little more of a pain when excluding just one.

**Comment by smileaf419** [comment]
CPU is rather old, 10-15 years I’d say.
Local=true failed as well
Local=false worked. Computer is more of a server than anything else and my monitor for some reason isn’t working. So I can’t test anything beyond compilation right now. :/

With local=false I’m now getting:
/usr/bin/ld: warning: type of symbol `glGenVertexArrays' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glBindVertexArray' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glGenBuffers' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glBindFramebuffer' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glFramebufferTexture2D' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glDeleteBuffers' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glDeleteVertexArrays' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glDetachShader' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glDeleteShader' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glDeleteFramebuffers' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glDeleteProgram' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glGetUniformLocation' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glUniformMatrix4fv' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glBindBuffer' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glBufferData' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glGetAttribLocation' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glEnableVertexAttribArray' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glVertexAttribPointer' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glBindFragDataLocation' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glDisableVertexAttribArray' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glCreateProgram' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glGenFramebuffers' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glCreateShader' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glShaderSource' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glCompileShader' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glGetShaderiv' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glAttachShader' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glGetShaderInfoLog' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glLinkProgram' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glGetProgramiv' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glGetProgramInfoLog' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glValidateProgram' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glUseProgram' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glUniform1i' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glUniform4f' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glGetUniformiv' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glUniform1f' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glUniform2f' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glUniform2fv' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o
/usr/bin/ld: warning: type of symbol `glUniform4fv' changed from 2 to 1 in /tmp/lto-llvm-6faba6.o

**Comment by Screwtapello** [comment]
Yeah, I get those "type of symbol changed" warnings too, they don't seem to cause problems in practice.

**Comment by smileaf419** [comment]
According to build logs, the symbol warnings were not there in 130.1 so figured I’d mention it, glad I’m not alone :)
Patch allows me to build normally. Appreciate the help!
