### ISSUE TITLE
[N64] Debug console output (printf/osSyncPrintf) is broken in libultra games.

### ISSUE THREAD

**Issue by ArthCarvalho** [higan-emu/ares#936]
Games made using libultra (n64's official SDK) console output functionality won't work correctly on the latest Ares compiled with console=true option (also was not working properly in previous versions either). The output functions properly in games made using libdragon (the open source SDK) but both commercial (such as the OoT Debug Rom) and homebrew games made using libultra will have this same problem when the console output is enabled.

Every printf (osSyncPrintf) command appends the whole console buffer at once all over again instead of only appending what the current output was supposed to be.

To better explain what is happening, this is a line of code I'm using in my homebrew project to output a memory address:

`osSyncPrintf("_heap_start(%08x)", _heap_start);`

which is expected to output:
`_heap_start(80139510)`

will actually output:
![image](https://user-images.githubusercontent.com/153105/213260145-58933563-daa5-4677-ac4e-e4971c5eb14b.png)

There is a single osSyncPrintf() call, if the game calls another osSyncPrintf() again everything that is already on the buffer will output all over again, creating a snowball that quickly halts the emulated game to a stop and eventually crashes the emulator.

**Comment by rasky** [comment]
Fixed by https://github.com/ares-emulator/ares/commit/8a71af4be1883f13df10fd0e76d4d1678afd1954
