### ISSUE TITLE
[SNES] Text is not visible

### ISSUE THREAD

**Issue by Max833** [higan-emu/ares#950]
1. Configuration -> video -> enable "Pixel Accuracy Mode" (it is working with the scanline renderer, though)
2. Start ROM "SNES Burn-in Test Cartridge (Unknown) (Rev D) (1)"
3. Click on "5. Burn-in test"
4. After the first check you can't see the text, just sprites:

![image](https://user-images.githubusercontent.com/53529402/216154015-edbf4bbe-540b-43a0-91c8-3cd3ae3c0b6e.png)

**Expected behavior**
There is text. In mesen and bsnes it looks like this:

![image](https://user-images.githubusercontent.com/53529402/216154122-5aca972c-00bd-4ab2-aa39-7f392eab51ec.png)

**Comment by remutro** [comment]
Something else must be going on here. I've tried this multiple times with and without pixel accuracy and it displayed just fine every time for me. Something must be different?

![butnin](https://user-images.githubusercontent.com/84990500/216165515-c8c0dbb5-c4cf-4b07-b821-80595abebb4f.png)

**Comment by Max833** [comment]
You are right. I have tested this with an older version. It is working with the newest. 

Thank you!
