### ISSUE TITLE
[General issue] Input delay when fast forwarding

### ISSUE THREAD

**Issue by Max833** [higan-emu/ares#958]
### Describe the bug
The default audio driver WASAPI has issues when using fast forward. What I mean by that is that every time the fast forward key is released, there is an input delay for like a second where the game stops completely. This issue does not occur with XAudio 2.1.

### To Reproduce
1. Start a SFC ROM and fast forward a little bit.

**Comment by Shideravan** [comment]
Seems related with #638

**Comment by Shideravan** [comment]
@Max833 Is it happening even in the last nightly version of ares for you?
https://github.com/higan-emu/ares/releases/tag/nightly

I cannot reproduce it anymore.
Maybe it is fixed now?

**Comment by windwakr** [comment]
Still happens even on the latest nightly.
