### ISSUE TITLE
[SNES] Can't disable Controller Port 2

### ISSUE THREAD

**Issue by Max833** [higan-emu/ares#969]
**Describe the bug**

There are some games where you have to disable controller port 2 or you can't play further. A game like this is "Kessen! Dokapon Oukoku IV - Densetsu no Yuusha-tachi". It looks like it hangs after the first character selection screen. Right here:

![image](https://user-images.githubusercontent.com/53529402/218282670-b4c32a07-b88b-4299-802f-5140ddabc807.png)

But it just waits for Controller 2. The issue is that you can't disable P2 permanently, it gets re-activated after a restart. You can change the controller 2 to "nothing" after you boot a game, but this doesn't do anything.

**To Reproduce**
1. Start the game and and press "A" until you get to the position on the image.

**Additional context**
It does work with bsnes.

**Comment by remutro** [comment]
I noticed this while working on another piece of functionality that is somewhat related. Initially I thought passing in "Nothing" to the allocate method was something special, but it only sets the name of the peripheral. So after disconnecting the port and changing the peripheral name to "Nothing", it immediately connects the port again. Not sure why really, but I can probably address this if I can complete the other thing I'm working on. 

Note that identification of what option is currently in use so the menu can be marked appropriately currently depends on ports being connected, including when they should be nothing.

**Comment by TascoDLX** [comment]
See commit 2ce9d210 for implementation done on md core. Should only need to deallocate the device on disconnect via callback.

**Comment by Max833** [comment]
@LukeUsher and @TascoDLX: The issue that you can't disable P2 is fixed now, thank you very much!

But the controller port 2 gets still re-activated every time I unload and start the game again. Is this the way it is intended?
