### ISSUE TITLE
Save States Freezing or Reseting Game on Load in WonderSwan Color

### ISSUE THREAD

**Issue by LightAcolyte** [higan-emu/ares#974]
Whenever I try to load a save state in the WonderSwan Color emulator the game either resets or it freezes (the game freezes, not the emulator) in which case I end up needing to reset anyway to continue playing. Is there a version of ares where loading save states was working? I've tried with a couple different games at this point.

**Comment by invertego** [comment]
Regressed in c95a27d66a454fbc10b98aa0d1cdeb65fe15e19e

It looks like the cpu.hpp additions are not being serialized. @asiekierka, mind taking a look?

**Comment by remutro** [comment]
@invertego @asiekierka - this is addressed in: https://github.com/ares-emulator/ares/pull/975

**Comment by asiekierka** [comment]
Sorry, and thank you!

**Comment by LightAcolyte** [comment]
Thanks very much for fixing for the future! Until then, it looks like save states are working OK in v130.1 so I can use that.

**Comment by asiekierka** [comment]
Has it been fixed in the latest nightlies?

**Comment by remutro** [comment]
This should be addressed in the latest nightly build: https://github.com/ares-emulator/ares/releases/tag/nightly

@LightAcolyte - Could you please confirm that latest ares build resolves this issue? It's working fine for me on the handful of games I tested.

**Comment by LightAcolyte** [comment]
Yes, I can confirm that the nightly build has saving states, and loading those newly-saved states, working correctly. Unlike some previous releases, new save states made in the current build are the only ones compatible to load from in the current build. 

Hence, save states working in v130.1 will not load in the current nightly build, but loading a saved game from RAM and then making new save states and loading them does work. I'm not sure if that is behavior as-intended?

**Comment by remutro** [comment]
Yes, there is no backwards compatibility support for save states unfortunately. Older versions should be detected as incompatible however. Once the major components of a system are implemented in a core, save state format really shouldn't change, but cores with development work actively in progress could result in previous save states becoming invalid in newer emulator versions.

Thank you for confirming these work again in the latest nightly build and reporting the issue!

**Comment by LightAcolyte** [comment]
Thanks for fixing it so quickly!

**Comment by asiekierka** [comment]
Note that the format will keep changing in the WonderSwan version for a while longer, as research is actively ongoing.
