### ISSUE TITLE
[Enhancement] 7zip support

### ISSUE THREAD

**Issue by RinMaru** [higan-emu/ares#979]
computers are fast nowadays and 7zip for rom files NOT CDs should be a standard it would be great to support them, so we not unloaded 6GB of data that been compressed to 800MB with zip

**Comment by BiZkViT96** [comment]
This has already been [discussed](https://discord.com/channels/976404869386747954/976411026620837898/1021019496275791873) and @LukeUsher does not want to add 7z support. dupe #388

**Comment by RinMaru** [comment]
> This has already been [discussed](https://discord.com/channels/976404869386747954/976411026620837898/1021019496275791873) and @LukeUsher does not want to add 7z support. dupe #388
