### ISSUE TITLE
[General] Compilation issue on Linux Mint 21 on latest.

### ISSUE THREAD

**Issue by HeroponRikiBestest** [higan-emu/ares#982]
**Describe the bug**
On Linux Mint 21, the emulator fails to compile, with `../nall/platform.hpp:22:10: fatal error: 'atomic' file not found` appearing on several files, and `/usr/include/glib-2.0/glib/glib-typeof.h:39:10: fatal error: 'type_traits' file not found` appearing on ares/ares/memory/fixed-allocator.cpp.

**To Reproduce**
Try and compile the program on Linux Mint 21.

**Expected behavior**
I expected the program to compile successfully.

**Screenshots**

**Additional context**
```
bestest@bestest-ThinkPad-T14-Gen-1:~$ gcc --version
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Compiling with clang also throws the same errors.
```
bestest@bestest-ThinkPad-T14-Gen-1:~/ares$ clang --version
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
I have not had compilation issues on any other program. Just recently, I compiled ScummVM without issue, but that goes for every other program I've tried. If there is any other program someone would want me to try compiling, please let me know.

**Comment by remutro** [comment]
This can be resolved by installing the 'libstdc++-12-dev' package. This seems like an issue with the packaging/installation on this specific distro, so not sure if this is something ares should try to workaround. There is more information in the following:

[https://stackoverflow.com/questions/74543715/usr-bin-ld-cannot-find-lstdc-no-such-file-or-directory-on-running-flutte/](url)

**Comment by invertego** [comment]
Our makefile now defaults to clang if you have it installed, so your clang install is borked, probably thanks to this:

https://bugs.launchpad.net/ubuntu/+source/clang/+bug/1997600

The output of `clang -v` would help diagnose, but it's likely clang is selecting something other than gcc-11 and you're missing the requisite libstdc++-N-dev package for that version, probably libstdc++-12-dev in this case.

**Comment by HeroponRikiBestest** [comment]
Output of clang -v
```
bestest@bestest-ThinkPad-T14-Gen-1:~/duckstation/build-release/bin$ clang -v
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

**Comment by HeroponRikiBestest** [comment]
The issue linked was correct, installing libstdc++-12-dev fixed it. I didn't test it, but in that case id imagine specifying g++ would have fixed it as well.

**Comment by LukeUsher** [comment]
Closing as this was not so much an ares issue but a broken build environment
