### ISSUE TITLE
crackling in 20 ms audio latency in Linux

### ISSUE THREAD

**Issue by petran79** [higan-emu/ares#983]
I use Ares on both Ubuntu 22.04 and Windows 10, using the same external USB sound card. 
I notice that in Windows 10, when I set the latency to the lowest value, 20 ms, games play fine.
However in Ubuntu if I set the latency below 40 ms, there is crackling in the sound to the point of being non-audible.
Independently of audio frequency values.

Is it an Alsa limitation? Does Pipewire play fine at 20ms?

**Comment by jeffythedragonslayer** [comment]
What sound card are you using?

FYI, Pipewire appears to have an environment variable called `PIPEWIRE_LATENCY` which you can configure.

**Comment by petran79** [comment]
An external sb katana v1.
It seems problem was due to alsa because I tried compiling  and it did not include pulse in options as a result. Probably some dev libraries were missing.

I installed flatpak version and pulse is present and crackling disappeared
